### ISSUE TITLE
Not really an issue, but a question/suggestion?

### ISSUE THREAD

**Issue by LTman86** [extesy/hoverzoom#10]
One feature I liked in Imagus/Hoverzoom that I would like to see in Hoverzoom+ is the ability to scroll through albums using the mouse wheel instead of the left/right keyboard buttons. Could you incorporate this into the code?

**Comment by extesy** [comment]
Does hoverzoom support this? If so, I wonder why is it not working in hoverzoom+ since this version is a fork. I'll take a look.

**Comment by LTman86** [comment]
One thing I just found out, Imagus can open gifs with audio from gifyoutube.com, where Hoverzoom+ can't, not sure if Hoverzoom can since I don't remember seeing those when I used Hoverzoom. Is that something you can patch in to support? No big deal if you can't, RES can help me there since gifs with audio aren't that common.

**Comment by extesy** [comment]
Please see the discussion in #24.
