### ISSUE TITLE
Add support for : moddb.com

### ISSUE THREAD

**Issue by eqagunn** [extesy/hoverzoom#1003]
**What is the URL of the website**
https://www.moddb.com/mods/back-to-saturn-x/images

**Why we should add support for the website?**
Browsing images requires the whole page to reload and is quite slow. Being able to HoverZoom them via thumbnails would be great.

**Comment by GrosPoulet** [comment]
@eqagunn a new plug-in for moddb.com (and indiedb.com) will be available in next release of HZ+ (1.0.196)

**Comment by extesy** [comment]
Fixed in [6c39fd4](https://github.com/extesy/hoverzoom/commit/6c39fd4d4227db30d25d3170ceb686004ce897eb)
