### ISSUE TITLE
Dark Mode for hover zoom options page please

### ISSUE THREAD

**Issue by Axer128** [extesy/hoverzoom#1028]
**Describe the solution you'd like**
Either auto detect browser dark mode setting and adjust, or add user toggle to support dark mode please (auto/dark/light). As browser wide extensions are not allowed to modify other extension pages, it ends up as the only glaringly bright white page on my browser while using dark reader. (many other popular extensions have already added dark mode to their options page, like uBlock origin)

**Describe alternatives you've considered**
The only alternate way to achieve this is to turn on the experimental chrome flag dark web contents, since it's a flag built in, its allowed to modify extension pages, but it breaks a ton of websites and fights against dark reader so not viable for most.

**Comment by GrosPoulet** [comment]
Good idea @Axer128, i'll give it a shot this week-end

**Comment by GrosPoulet** [comment]
@Axer128 : i added a Dark Mode option (#1034).
It'll be available in next release of HZ+ (1.0.197)

**Comment by extesy** [comment]
Fixed by 1aac3f3c5fbe9e2c676c03084eb4dc79292e5589.

**Comment by Axer128** [comment]
Awesome thanks!
