### ISSUE TITLE
We should remove the screenshots from the FAQ

### ISSUE THREAD

**Issue by wvxwxvw** [extesy/hoverzoom#1032]
We have to remove screenshots from the FAQ, it is illogical, there is a localized text description with exact description of the parameter, and a screenshot in English is attached. It just takes up space on the page.

**Comment by extesy** [comment]
The reason FAQ exists is because people have raised issues or asked questions about the existing functionality.

**Comment by wvxwxvw** [comment]
You didn't get it. It's not about the FAQ, but about useless screenshots in it. They are simply not needed if there is a text description. And the screenshots are in English, dut the parameters themselves are localized. Have you not forgotten that your addon is localized? )
