### ISSUE TITLE
How to support HoverZoom on my website?

### ISSUE THREAD

**Issue by Nesh108** [extesy/hoverzoom#105]
Hello there!

I am making a small website and I would like to support HoverZoom since I absolute love it!

I tried the following:

- Adding the image file extension to the endpoint (e.g. http://my_website/image/lolcat.png)
- Adding the appropriate headers (e.g. Content-Type: image/png and Content-Length : 101010)
- Checking the status code (I tried with 200 and 304, as returned from some imgur pages)

Since nothing seemed to work, I thought I would ask you directly.

How can I support HZ?

Btw, I am testing this by running my backend locally (localhost), creating a simple HTML page with just:

```
<html>
<body>
    <a href="http://localhost:4000/image/lolcat1.png">image</a>
</body>
</html>
```

When I try to hover, nothing works.

Just to be complete, the API requires a Basic Auth but, when testing, the browser has already access to the image.

Thanks in advance!

**Comment by extesy** [comment]
@Nesh108 Please open the Chrome's dev console and check if there are any error messages.

**Comment by Nesh108** [comment]
@extesy no error whatsoever. I am not sure if that's supposed to happen, but nothing changes in the Network tab either.

P.S. HZ on Reddit works normally.

**Comment by Nesh108** [comment]
@extesy I was taking a super quick look at the code in `js/hoverzoom.js` and I noticed this comment:

```
// Only zoom jpg images, to prevent zooming on images that are part of the site design
```

Is that correct? If so, would it be enough to just change my endpoint to ending with `.jpg`? Or is hoverzoom smarter and actually check the `Content-Type` as well?

**Comment by Nesh108** [comment]
Anything? It should be quite easy to support this tool since it can already handle so many websites.

**Comment by extesy** [comment]
I haven't looked into this yet. It might be that Chrome is just not loading this extension for localhost pages. In any case, the extension operates on urls by scanning page html code after it's loaded, so headers don't matter.
