### ISSUE TITLE
[feature request] Add option to show image size/resolution

### ISSUE THREAD

**Issue by cocoonkid** [extesy/hoverzoom#1051]
**Is your feature request related to a problem? Please describe.**

I need to have an additional extension to quickly see the image size/resolution of an image. And it's not as pretty as hover zoom.

![image](https://user-images.githubusercontent.com/43231640/196004283-d5dd8462-9df9-47b4-8673-13fb42fd0539.png)

**Describe the solution you'd like**

I'd be so nice if I could see the pixel size at the bottom of the zoomed image as well.

**Describe alternatives you've considered**
Using the image size info extension. But it is not as neat.

Thanks for this extension, it's an everyday helper.

**Comment by extesy** [comment]
@cocoonkid Have you tried enabling these options?
![image](https://user-images.githubusercontent.com/65872/196004664-bd2b4490-a0d8-4da7-8e70-81de5a397f70.png)

**Comment by cocoonkid** [comment]
omg. I'm so sorry. I swear I scanned the options to see if it already exists before I came here and complained :-)

Thanks a bunch!
