### ISSUE TITLE
Videos Not Playing Without Clicking First

### ISSUE THREAD

**Issue by forthemame** [extesy/hoverzoom#1053]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Gifs / vids don't play unless you click on the website (see image link for example).  I know there's a setting to change this, but maybe it's within the Chrome browser, not the extension?

## Url of the page where the problem occurs (not the image url)
Any; reddit.com for example

## Steps to reproduce the problem (include image url here)
1. I think just hovering over gifs / vids without clicking on the website first
2. Picture of the message: https://imgur.com/a/AuEYpzs
3.

## OS version, extension version
Windows 10

**Comment by extesy** [comment]
@forthemame This is a browser's restriction, see https://developer.chrome.com/blog/autoplay/ for details. You can run Chrome with ` --autoplay-policy=no-user-gesture-required` command line parameter to work around this.
