### ISSUE TITLE
issues in Google Image search results page

### ISSUE THREAD

**Issue by richardhauer** [extesy/hoverzoom#106]
When I have the image search results "open" after clicking a certain image on the main tile page, the hover image of the main image seems to get stuck in cache - I assume its URL is not updating or is set via CSS or something that is confusing hoverzoom.

Additionally, clicking the left & right navigation chevrons to adjust the Google Image search context to the next result causes the zoom to fail altogether on the main image.

The additional "related image" tiles still seem to work though.

Chrome v51 on Win10 x64

![image](https://cloud.githubusercontent.com/assets/225807/16482262/517b356c-3ef2-11e6-82de-9a71c653e024.png)

**Comment by GrosPoulet** [comment]
Fixed in [v1.0.185](https://github.com/extesy/hoverzoom/releases/tag/1.0.185)
