### ISSUE TITLE
dont work on ebay please fix it !

### ISSUE THREAD

**Issue by Werner-St** [extesy/hoverzoom#1072]
ebay has changed the integration of the graphics, please readjust the hoverzoom. THANKS

https://www.ebay.de/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313&_nkw=Tischmultimeter&_sacat=92074&LH_TitleDesc=0&_dmd=2&rt=nc&_odkw=Tischmultimeter&_osacat=92074&_sop=12

**Comment by extesy** [comment]
Fixed! Will be available in the next release.
