### ISSUE TITLE
Add support for : fandom.com

### ISSUE THREAD

**Issue by pityalvarez** [extesy/hoverzoom#1077]
**What is the URL of the website**
https://www.fandom.com/

**Why we should add support for the website?**
I just need to see simple images shown in the wiki, it doesn't seem complex, it would be awesome for everyone

**Comment by GrosPoulet** [comment]
Hi @pityalvarez 
I added a plug-in for fandom.com, it'll be available in next release of HZ+ (1.0.203).

**Comment by extesy** [comment]
Fixed in 5b54127a9f1ce5f436563fb8e8ba0f1f525b6945.

@GrosPoulet can you please close issues as fixed when you implement the requests?
