### ISSUE TITLE
V.reddit videos have no sound

### ISSUE THREAD

**Issue by gutt2** [extesy/hoverzoom#1078]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## V.reddit videos all have sound muted, greyed out sound icon

##old.reddit.com

## Steps to reproduce the problem (include image url here)
1.go to reddit 
2.Hover over v.redd video
3.No sound

**Comment by vient0** [comment]
Have the same issue with Reddit videos. It stopped working since today's update. When pressing T to open the video on a different tab it also reproduces without sound and shows a Not Secure on the URL bar.

![image](https://user-images.githubusercontent.com/71467566/216447038-f9809c22-525d-49e7-b5b6-b6ec98ae5dc6.png)

**Comment by gutt2** [comment]
I don't get how there's not more people with this problem..tried on 3 different pc's with different browsers.

**Comment by TheMikeyR** [comment]
I also have this issue

**Comment by DavidW-GIT** [comment]
Also having the same issue.

**Comment by bopeuph** [comment]
Same.  Glad it's not just me.

**Comment by walker164** [comment]
Same same. I hit the thumbs up 🤷‍♀️

**Comment by Ironspider3000** [comment]
Same, also YouTube videos/shorts have the audio button greyed out.

**Comment by gutt2** [comment]
Anyone know how to message the developer directly or tweet at him or something?

**Comment by vient0** [comment]
I just started using version [1.0.200](https://github.com/extesy/hoverzoom/releases/tag/1.0.200). Everything works correctly on that one.

**Comment by gutt2** [comment]
> I just started using version [1.0.200](https://github.com/extesy/hoverzoom/releases/tag/1.0.200). Everything works correctly on that one.

I tried, how did you install it?

**Comment by vient0** [comment]
I followed [these steps](https://support.whatfix.com/docs/how-to-install-a-whatfix-chrome-extension-from-a-zip-file).

**Comment by gutt2** [comment]
> I followed [these steps](https://support.whatfix.com/docs/how-to-install-a-whatfix-chrome-extension-from-a-zip-file).

That worked bro...thanks a bunch!  Gonna leave this open since it's not fixed through update.

**Comment by extesy** [comment]
Apologies, dear users! One of the recent commits seems to have broken audio. Let me fix that and I'll publish a hotfix release.

**Comment by extesy** [comment]
I just checked that after https://github.com/extesy/hoverzoom/commit/58b1ac9e8854d7fdae8aaa8c5add1905fd093bdf the audio works on reddit and instagram. Pushing the new release.
