### ISSUE TITLE
failure to play audio from old.reddit videos

### ISSUE THREAD

**Issue by Hyperious** [extesy/hoverzoom#1081]
**Describe the bug**
Videos will play when hovered over, but lack sound. This is with sound turned on and at 100% volume. Opening the video in RES will play audio just fine

**To Reproduce**
1. Go to 'old.reddit.com/r/AnySubThatHasVideoContent'
2. Hover over the post to try and play the video with Hoverzoom
3. See video play, but with lack of audio

**Expected behavior**
Hovered over videos used to play their sound before the recent update on the 1st

**Screenshots**
not really possible with an audio issue

**Desktop (please complete the following information):**
 - OS: Win 10 64x
 - Browser chrome 109.0.5414.120 (Official Build) (64-bit)
 - Version 1.0.201

**Additional context**
This happens with any video link on old.reddit, not just stuff hosted on their CDN. Gyfcat vids, streamable vids, even youtube videos will just play the video without audio. This is only happening on old.reddit, and nowhere else.

**Comment by extesy** [comment]
Hi @Hyperious, thank you for the report. There was a regression in `1.0.201` which was reported in #1078 and fixed in `1.0.202`. Can you please check if the issue still reproduces after you receive `1.0.202` update?

**Comment by Hyperious** [comment]
yup, will check and report back. Current version downloadable through chrome is the 1.0.201 version, so just waiting for .202

**Comment by Hyperious** [comment]
yup, that did it
