### ISSUE TITLE
Add support for : commons.wikimedia.org

### ISSUE THREAD

**Issue by Taizunz** [extesy/hoverzoom#1083]
**What is the URL of the website**
https://commons.wikimedia.org/

**Why we should add support for the website?**
Hover Zoom already supports direct image URLs from wikimedia, but not file pages.
Example:
File page - https://commons.wikimedia.org/wiki/File:Mary_Stuart_Young6.jpg
Direct file link - https://upload.wikimedia.org/wikipedia/commons/0/02/Mary_Stuart_Young6.jpg

When people share or hyperlink to media from wikimedia, they often link to the file page and not the longer direct link, which Hover Zoom doesn't know how to show.

**Comment by GrosPoulet** [comment]
Hi @Taizunz 
I updated **Wikimedia** plug-in, it'll be available in next release of HZ+ (1.0.203)

**Comment by vitaly-zdanevich** [comment]
Hi, still nothing for me, for example this page https://commons.wikimedia.org/wiki/Category:Mogilyovskiye_gubernskiye_vedomosti

**Comment by extesy** [comment]
@vitaly-zdanevich Those are pdf files - they are documents, not images.

**Comment by vitaly-zdanevich** [comment]
Inside every link they have jpg previews in different sized.
