### ISSUE TITLE
Add support for reddituploads.com images

### ISSUE THREAD

**Issue by jaredatch** [extesy/hoverzoom#109]
👍

**Comment by extesy** [comment]
Already supported. If it doesn't work for some images, then please provide urls to reproduce the problem.

**Comment by jaredatch** [comment]
You're right, sorry about that!

[Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US) was blocking the reddituploads domain.
