### ISSUE TITLE
Gallery should not be completely reopened when cycled (regression)

### ISSUE THREAD

**Issue by jason-e** [extesy/hoverzoom#1092]
**Describe the bug**
Pull request #908 changed how rotating through galleries is handled. Instead of just changing the current item URL, it completely removes and recreates the viewer, which is not only wasteful but results in a jarring disappear+fade-in animation *every* time the gallery is rotated. This makes for a pretty uncomfortable and inefficient viewing experience, and I'm surprised this was seemingly not addressed all this time. That commit also removed the only call to `nextGalleryImageOnLoad()`, but did not remove that function, resulting in orphaned code in the codebase this whole time as well.

**To Reproduce**
1. Make sure "fading animation duration" is non-zero (default is 0.2s)
2. Browse any gallery, such as [this one](https://www.reddit.com/r/Justrolledintotheshop/comments/1182zve/still_happens_even_in_2023/)
3. Cycle through the gallery
4. Observe the entire viewer being removed and fading back in every time the gallery is cycled

**Expected behavior**
The image should just change, without removing the viewer or doing any kind of animation.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 109

**Comment by extesy** [comment]
@GrosPoulet Can you please take a look? You authored #908 so you have more context.

**Comment by GrosPoulet** [comment]
Hello @jason-e
I guess this issue was not reported before because it disturbs no one ... but you :wink:
#908 was a fix for "mixed" galleries (= with pictures & videos), as you can find on Instagram for instance. 
Anyway you're right: recreating viewer is not needed when switching from one picture to another picture.
I'll give it a look this week-end.
