### ISSUE TITLE
Markers on Wikipedia Maps Don't Show

### ISSUE THREAD

**Issue by Powowowowow** [extesy/hoverzoom#1110]
On Wikipedia pages that include maps with markers on them, Hover Zoom expands the blank map and leaves the markers behind.

example page: https://en.wikipedia.org/wiki/Achilleion_(Troad)

1. Take note of markers on map image
2. Hover over the image and see the markers have disappeared

img url: https://en.wikipedia.org/wiki/Achilleion_(Troad)#/media/File:Turkey_adm_location_map.svg

Windows 10 Pro 10.0.19045 Build 19045
Brave Browser
Hover Zoom+ version 1.0.202

**Comment by GrosPoulet** [comment]
Hi @Powowowowow 
There are distinct images: 
- one for blank map
- one or more for markers (red dots)

HZ+ can zoom either blank map or marker, but not both at the same time.
