### ISSUE TITLE
Despite the update, it still doesn't work on ebay.de!

### ISSUE THREAD

**Issue by Werner-St** [extesy/hoverzoom#1113]
Despite the update, it still doesn't work on ebay.de !

[## Url of the page where the problem occurs (not the image url)](https://www.ebay.de/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313&_nkw=tischmultimeter&_sacat=0&LH_TitleDesc=0&rt=nc&_odkw=tischmultimeter&_osacat=0&LH_PrefLoc=3)

Please Fix it........
All Os Version , all Browser  Version

**Comment by extesy** [comment]
Duplicate of the existing issue.

**Comment by Werner-St** [comment]
It was already faulty in version 1.0.202 and is not yet correct in the new version 1.0.203!
