### ISSUE TITLE
Stopped Working on tumblr Blogs

### ISSUE THREAD

**Issue by Rhaevyn** [extesy/hoverzoom#112]
For some reason Hover Zoom has stopped working on my blogs.  It works on the dashboard feed, but not within actual blogs.  I have removed it and added Hover Zoom + several times, rebooted, you name it.  It has just stopped functioning in my blogs.  Still works on Pinterest, Google images searches, etc., but not on my blogs.

**Comment by extesy** [comment]
@Rhaevyn please provide url of the page where I can reproduce the problem.

**Comment by Rhaevyn** [comment]
http://goth-witch-rhaevyn.tumblr.com/

Date: Mon, 25 Jul 2016 10:06:25 -0700

**Comment by extesy** [comment]
Ok, I can reproduce the problem. Will take a look.

**Comment by extesy** [comment]
Tumblr works now.
