### ISSUE TITLE
Images still saves twice

### ISSUE THREAD

**Issue by ye8cv** [extesy/hoverzoom#1134]
Using version 1.0.205  of HoverZoom and chrome version 109.0.5414.129
I've checked the new advanced checkbox "Allow downloading images using an action key". 

**Steps to reproduce the behavior:**
1. Hover over an image
2. Image pops up
3. Press "S" for save 
4. Images is downloaded twice. One as xxxx.jpg and the second as xxxx(1).jpg

**Expected behavior**
Expect only one file of the image to be saved. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 -  Windows 8.1
 - Chrome 109.0.5414.129
 - HoverZoom 1.0.205

**Additional context**
I've checked the new advanced checkbox "Allow downloading images using an action key". Without checking this checkbox, nothing gets downloaded.

**Comment by maurie13** [comment]
the same experience - but the pic is saved three times

Windows 10
Chrome 109.0.5414.129
HoverZoom 1.0.205

**Comment by miklosUX** [comment]
Yep. Same here. At least we're down to one less. Used to save 3 images at once :))))
With any luck, we'll be down to just one saving soon...
macOS Ventura 13.3.1
Chrome 112.0.5615.137 (Official Build) (x86_64)
HoverZoom 1.0.205

**Comment by miklosUX** [comment]
Looks like the issue has been fixed.  👏🏻 Cheers to the dev!

**Comment by ye8cv** [comment]
Yes, I noticed also that it has now been fixed. Hurray! =)
