### ISSUE TITLE
Add support for : gcsurplus.ca

### ISSUE THREAD

**Issue by csilvest** [extesy/hoverzoom#1138]
**What is the URL of the website**

Generally: https://www.gcsurplus.ca

Specific example: https://www.gcsurplus.ca/mn-eng.cfm?snc=wfsav&sc=ach-shop&jstp=sly&hpsr=&hpcs=5500&vndsld=0&saleType=A

**Why we should add support for the website?**
HoverZoom speeds up browsing this auction site by a factor of 10 or more.  

Thanks!

**Comment by csilvest** [comment]
Seems that HoverZoom will work on a few of the images on the referenced page.  Perhaps 1 in 6 will work.  Not sure what the difference is between the ones that HoverZoom can pull up vs. those it can't.

**Comment by GrosPoulet** [comment]
@csilvest i added a plug-in for gcsurplus.ca, it'll be available in next release of HZ+ (1.0.206)
