### ISSUE TITLE
any plan for Microsoft Edge support?

### ISSUE THREAD

**Issue by rakion99** [extesy/hoverzoom#114]
this will be awesome if made, some where i readed that should be easy to port it to microsoft edge but idk

**Comment by extesy** [comment]
No immediate plans, sorry. Edge extensions have just been released so there is not much information or examples available.

**Comment by rakion99** [comment]
well looks like will be easy already tryed by myself and tested with imgur, redd.it giphy and working fine, but gfycat dont work

**Comment by extesy** [comment]
@rakion99 If you know how to implement this support, feel free to open pull request.

**Comment by flawrist** [comment]
Which version is the latest for Edge 109?

**Comment by extesy** [comment]
@sergeevabc All releases are uploaded simultaneously to Chrome, Firefox and Edge web stores. The rest is up to Google, Mozilla and Microsoft as to when they approve these updates.

**Comment by flawrist** [comment]
@extesy 

Олег, я физически не могу установить версию из магазина, т.к. она, очевидно, не совместима с Chrome/Edge v109. См. сообщение об ошибке на скринтоже ниже. Поэтому я спросил, какая версия HoverZoom+ всё же будет работать на указанной версии браузера? Эту версию расширения я и поищу в сети, мне нужен номер.

![](https://github.com/user-attachments/assets/999c3c99-ba35-47bc-b701-0eac89d0ea7a)

**Comment by extesy** [comment]
@sergeevabc Edge extensions should be installed from Edge store, not Chrome store - https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by flawrist** [comment]
Олег, вы меня не слышите. Пользователь (я) спросил разработчика (вас): какая версия расширения HoverZoom+ работает со 109-й версией браузера? В ответ что угодно, но не номер версии расширения.

Во-первых, пользователи Edge могут использовать магазин расширений Chrome, у меня оттуда стоит дюжина расширений и все работают. Во-вторых, вот скриншот из магазина Microsoft с той же самой ошибкой, сообщающей, что текущая (последняя) версия расширения уже не совместима со 109-й версией Edge.

![](https://github.com/user-attachments/assets/fe17d6bf-3437-4423-b04f-bf7f4391750b)

Если добавить HoverZoom+ из магазина Microsoft силой, использую служебную ссылку https://edge.microsoft.com/extensionwebstorebase/v1/crx?x=id%3Dbnibclmindjpdfiipicpdhljfblkpkml%26installsource%3Dondemand&response=redirect то браузер сообщает об ошибке, расширению нужен аж Edge 130.

![](https://github.com/user-attachments/assets/b2d3d3b3-2670-4daa-a92d-8ba8c6b41575)

Поэтому я ещё раз повторю свой вопрос: какая версия HoverZoom+ (какой у неё номер) будет работать с Edge 109?

У программистов обычно есть архив того, что они сделали в этой жизни. В вашем случае архив разных версий HoverZoom+. Внутри каждой версии расширения есть файл `manifest.json`, где переменная `strict_min_version` определяет минимальную версию браузера. Сейчас она 130, а нужно то расширение, где ≤109.

**Comment by extesy** [comment]
@sergeevabc `1.0.225`

**Comment by flawrist** [comment]
Вот, [нашёл 1.0.225](https://www.crx4chrome.com/crx/410193/). Работает. Спасибо, Олег.

![](https://github.com/user-attachments/assets/88b3592b-e923-40c2-aea7-bef7b69d1dd1)
