### ISSUE TITLE
Sometimes doesn't load picture

### ISSUE THREAD

**Issue by D0J0P** [extesy/hoverzoom#115]
Sometimes, I'll be browsing through Facebook, Reddit, or any other website, and I'll have the mouse over the picture. The loading bar keeps going for a while, and the picture never shows sometimes. 

This extension works most of the time, but every once in a while, I come across a picture that will never load, and I'll have to click on that picture to see it's full size, defeating the purpose of the extension itself. 

I love this extension, I just hate how unstable it works. 

Sorry I can't give more precise details as to when it happens exactly. It just happens when it feels like.

**Comment by extesy** [comment]
@D0J0P Reddit/Facebook/etc have links to many different image hosts. Not all of them are supported. Please provide specific examples of pages/images which don't work because it's impossible to implement generic hover support for absolutely every image host out there.
