### ISSUE TITLE
Save settings button not working in Firefox

### ISSUE THREAD

**Issue by skinley** [extesy/hoverzoom#116]
I cant save my settings, they just keep resetting to off. Any help?

**Comment by extesy** [comment]
@skinley Firefox was never supported, how did you even manage to install this extension in Firefox?

**Comment by extesy** [comment]
This is somebody else's port of this extension, it didn't come from this repo and I'm not affiliated with that extension. Please contact its author directly.

**Comment by 07416** [comment]
![12](https://user-images.githubusercontent.com/14923168/36632003-4ea1f01a-1989-11e8-9680-a71d106fe724.png)

Was there ever any issues with the "save button" itself? Do settings persist for the current session?
