### ISSUE TITLE
 Images are not hovering when activating hoverzoom on Microsoft Edge browser

### ISSUE THREAD

**Issue by bigplayer-ai** [extesy/hoverzoom#1162]
**Title:** Hoverzoom does not work as expected on Microsoft Edge
**Description:** Images are not hovering when activating hoverzoom on Microsoft Edge browser
**Environment:** Windows 11, Version 22H2 (OS Build 22621.1848), Microsoft Edge version 114.0.1823.51 (Official build) (64-bit)
**Steps to reproduce:**
1. Install hoverzoom extension on Microsoft Edge from the Microsoft Store
2. Go to any website that contains images, such as https://instagram.com
3. Hover over any image with the mouse cursor
4. Observe that the image does not enlarge or show any hover effect
**Expected behavior:** The image should enlarge and show a hover effect when hovering over it with the mouse cursor
**Actual behavior:** The image does not enlarge or show any hover effect when hovering over it with the mouse cursor
**Screenshot:** (Attach a screenshot of the issue if possible)

**Comment by extesy** [comment]
@bigplayer-ai Please provide a specific link because I've tried https://www.instagram.com/world_record_egg/ in Edge and it works for me.

**Comment by yann-mrt** [comment]
Happen to me as well more with LinkedIn or https://sarara.co/sarara-treehouses (that only example). With the  https://www.instagram.com/world_record_egg/ it is working well.

**Comment by extesy** [comment]
@yann-mrt This extension won't work with every single website on the internet, so not being able to zoom images on https://sarara.co/sarara-treehouses is expected.
