### ISSUE TITLE
Go to  https://www.flickr.com/photos/simpletones/   hoover zoom not working. 

### ISSUE THREAD

**Issue by silviu3marian** [extesy/hoverzoom#1169]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by extesy** [comment]
It's working for me. Please fill out all details in a bug template.

**Comment by silviu3marian** [comment]
Right. Sometimes , browser go into quirks mode , and HZ stop working. I m a beginner, but I noticed

**Comment by extesy** [comment]
@silviu3marian Issue details are still missing:
![image](https://github.com/extesy/hoverzoom/assets/65872/12bf7f88-63f2-457a-95b8-66c70b5b839f)
Please fill out all sections, otherwise I'll have to close this issue as invalid.
