### ISSUE TITLE
Not working on Facebook

### ISSUE THREAD

**Issue by euronate** [extesy/hoverzoom#118]
It stopped working on Facebook once again.  It seems like Facebook changed their site again which likely led to this problem.

**Comment by jeetjeet11** [comment]
having same problem too. worked earlier today, noticed it stopped working about 30 mins ago

**Comment by vanja-krk** [comment]
please, @extesy, can you elaborate this "update existing plugin". i cleared cache, uninstalled, reinstalled, still no go. please explain. 
thanks in advance.

**Comment by khamseen** [comment]
@vanja-krk it's a tag for the Dev, not for users. It means this is a bug which requires him to update an existing plugin, rather than a feature request which requires a new plugin to be created.

**Comment by zbigniewfr** [comment]
Still having problem with zooming photos on facebook. What should I do to make it work? Like @vanja-krk I cleared cache, reinstalled but with no luck...

**Comment by extesy** [comment]
It still works for me, so I apologize but I can't fix the bug that I can't reproduce. Make sure you are using hoverzoom+ and don't have original hoverzoom installed.

**Comment by zbigniewfr** [comment]
I'm using hoverzoom+ for sure ;) original not installed. Could you tell what things can be related with your extension. I mean for example can this be related with chrome version etc? If you can't reproduce the problem maybe I can help with some debuging? :)
