### ISSUE TITLE
Option to have middle mouse click as action key

### ISSUE THREAD

**Issue by fankulaa** [extesy/hoverzoom#1190]
I'm using mouse with one hand, to zoom in images using "Lock image on screen" feature you need both hands - for press some other key on keyboard without macros. 

That's very unintuitive and annoying.

##Would love option to have middle mouse click as action key.

**Comment by LiliaDoe** [comment]
I am working on updating right click as an action button and adding middle mouse as one. Would it feel better to press and hold to activate it or activate right away? I think press and hold will work better, but I can make it either. For image locking, it was instantly activated.

### Press and hold:
- Pros: 
    - You still have access to the button's normal function
    - Can have consistent behavior for all actions
- Cons: 
    - It doesn't activate immediately

### Instant activation:
- Pros:
    - It's immediate
- Cons:
    - Not every function could use this e.g. anything that needs to be held to work, like Zoom key and HZ+ Activate key
    - Will require you to hold down key longer than normal for it's normal function to work.
