### ISSUE TITLE
Add support for : edhrec

### ISSUE THREAD

**Issue by voodoofoo** [extesy/hoverzoom#1197]
https://edhrec.com

**Why we should add support for the website?**
At the moment in order to see what a card does you have to open the image in a new tab just to get a idea with what it does with all the text, where as with this extension would help make it easy to go through cards quicker

**Comment by GrosPoulet** [comment]
@voodoofoo #1204 addresses your request, you'll have to wait for next release of HZ+ to get it.
I'll create new plug-ins to support other cards-related websites such as TCGPlayer, MTGPics, ...

![edhrec](https://github.com/extesy/hoverzoom/assets/23529041/bd2f6d10-c1ce-40d8-a8b2-8dc007733c1e)
