### ISSUE TITLE
Add support for :  https://za.shein.com/

### ISSUE THREAD

**Issue by ladysheinsemporium** [extesy/hoverzoom#1203]
**What is the URL of the website**
https://za.shein.com/

**Why we should add support for the website?**
I use the images to create personalised shopping bundles for my business, I usually just downloaded the images as needed but they now seem to have added some sort of overlay which makes downloading the images time consuming and difficult.

Adding your Hover Zoom+ would go along way in making my job easier, much appreciated.

**To replicate select a garment with multiple images like:**
https://za.shein.com/SHEIN-Clasi-Graphic-Print-Sleeveless-A-line-Dress-p-14929480-cat-1727.html

**Comment by GrosPoulet** [comment]
@ladysheinsemporium Shein is already supported by HZ+, i can't see the overlay you're talking about.

![image](https://github.com/extesy/hoverzoom/assets/23529041/772a2857-8aed-4680-8a4b-34666f5ff761)

**Comment by ladysheinsemporium** [comment]
@GrosPoulet, the pics you shared are from the reviews below the item itself, at the top of the page you will see the actual item being sold where Hover Zoom doesn't seem to detect the pic.

The overlay I'm referring to is below, as soon as that is hidden you can right click and save pic as.

![image](https://github.com/extesy/hoverzoom/assets/142080878/3dcdaf1e-29c7-4076-89c5-ec79da935819)

**Comment by GrosPoulet** [comment]
@ladysheinsemporium i updated shein plug-in to enable zoom & save images. It'll be available with next release of HZ+ (1.0.210).

![image](https://github.com/extesy/hoverzoom/assets/23529041/0c09819d-db0b-4e77-bf20-77a8229c6d91)
