### ISSUE TITLE
Blacklisting sites doesn't seem to be working for me. 

### ISSUE THREAD

**Issue by leetwanker** [extesy/hoverzoom#121]
Hovering over [this link](https://www.theguardian.com/us-news/2016/aug/16/akai-gurley-new-york-police-shooting-settlement) on reddit, (but oddly not here... strange.)

Brings up [this picture](https://i.guim.co.uk/img/media/ffb7c2843afb9fb1176470245a0ed4c676d25587/0_238_3500_2099/3500.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&bm=normal&ba=bottom%2Cleft&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNS8yNS9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=6258ec7111826388197e27de4597b193). Hovering over this picture here still works even though guim.co.uk is blacklisted. 

[Hoverzoom Settings](http://pix.toile-libre.org/upload/original/1471412359.png)

Thanks

**Comment by leetwanker** [comment]
Another example:
[This link](https://www.thenation.com/article/if-you-want-to-know-the-truth-about-the-criminal-justice-system-talk-to-this-private-investigator/)
[This picture](https://www.thenation.com/wp-content/uploads/2015/10/prison_hand_rtr_img-1440x756.jpg)

**Comment by extesy** [comment]
@leetwanker Try removing trailing slash from your blacklisted domain name.

**Comment by leetwanker** [comment]
In my 2nd example I have thenation.com listed 3 different ways, all without a trailing slash and hovering over [this link](https://www.thenation.com/wp-content/uploads/2015/10/prison_hand_rtr_img-1440x756.jpg) still displays a picture. What happens when you hover over that link?

**Comment by extesy** [comment]
No, the problem is different from what you think. Firstly, http loading from https websites is not allowed by browser's security policy, see #84. Secondly, blacklisting used to work to blacklist source sites (where links originate from), not destination (where images are hosted). Now it works in both cases.
