### ISSUE TITLE
Fallout Fandom wiki show only one image on hover

### ISSUE THREAD

**Issue by plego97** [extesy/hoverzoom#1218]
## Describe the bug
When using hover zoom on a page with a gallery, after a few "hoverzooms" an image seems to get stuck and only that one will be shown on all hovers from that point on. In the example I give below, after hovering over the main image, all gallery images will show that image on hover. 

with the debug logging, I get the following message on hover: `hiding because https://static.wikia.nocookie.net/fallout/images/0/05/FOSO_Roger_Maxson.png/revision/latest?cb=20220828153526 !== https://static.wikia.nocookie.net/fallout/images/1/1b/UITex_YS_C_Bg_HeroShare_rogermaxson.png/revision/latest?cb=20220829103630`

## Example URL:
https://fallout.fandom.com/wiki/Roger_Maxson

## Steps to reproduce the problem
1. Open website
2. Hover over Main Image (in the sidebar)
3. Scroll down to the [Gallery](https://fallout.fandom.com/wiki/Roger_Maxson#Gallery) section
4. Hover over Image
5. The wrong image is shown

### Images
Main Image Works
![image](https://github.com/extesy/hoverzoom/assets/7893117/5b7e5795-5c59-4fe8-b71a-06c9b1bb28db)

Gallery Images show Main Image
![image](https://github.com/extesy/hoverzoom/assets/7893117/c22086b8-6bd3-410a-a032-c1679ddbde2d)

## Observations
I tried another [site in the fallout fandom](https://fallout.fandom.com/wiki/Brotherhood_of_Steel#Gallery) and there most of the time the main image is shown on hover, but sometimes a different image is shown (for me the first gallery image shows the fallout 1 title screen).

## System
Windows 11 22621.2134
Edge Version 115.0.1901.203 (Official build) (64-bit)
Hoverzoom+ Version 1.0.209 (last update: Sun, Aug 13, 2023)

**Comment by extesy** [comment]
Looks like a bug. Thank you for the detailed repro steps.
