### ISSUE TITLE
Stopped working on Streamable links

### ISSUE THREAD

**Issue by tropicoo** [extesy/hoverzoom#122]
It shows and closes endlessly the video.
[Link to reproduce](https://www.reddit.com/r/videos/comments/4yyckj/full_tokyo_2020_olympics_teaser_intro_xpost_from/).
Version: 1.0.89
Chrome Version 53.0.2785.70 beta-m (64-bit)

**Comment by extesy** [comment]
It's weird, it works for me using that link. I'm on Chrome 52, though. So maybe Chrome 53 introduced some bug?

**Comment by tropicoo** [comment]
It looks so. I've tried at work where I use OS X El Capitan & Chrome 52 and everything works good.

**Comment by extesy** [comment]
I will close this bug for now and will reopen if necessary when Chrome 53 is out of beta.
