### ISSUE TITLE
Not working on Flickr 

### ISSUE THREAD

**Issue by pwmcmaho** [extesy/hoverzoom#1238]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Nothing is happening when viewing images on the explore section of the Flickr website:

## Url of the page where the problem occurs (not the image url)
https://www.flickr.com/explore

## Steps to reproduce the problem (include image url here)
1.  Go to the website: https://www.flickr.com/explore
2.  Hover over an image
3.  Notice that hoverzoom does not appear to recognize or react to the image

## OS version, extension version
MacOS 11.17 (BigSur)
Firefox 117.0.1

**Comment by wlm2048** [comment]
I can add the following details, this is the error occurring in the logs:
VM62 flickr_a.js:106 [HoverZoom] Flickr API call failed. Photo ID: 53257554450. Error #100: Invalid API Key (Key has expired)

Win 11/Chrome 117/HZ 1.0.210

**Comment by GrosPoulet** [comment]
@wlm2048 I fixed plug-ins for Flickr, they'll be available in next release of HZ+ (1.0.211).
