### ISSUE TITLE
Add Bluesky support

### ISSUE THREAD

**Issue by elylv** [extesy/hoverzoom#1243]
Since lots of people are moving from Twitter/X, would be good to have Bluesky support.

Seems the URL for embedded images is of the format:
https://cdn.bsky.app/img/feed_thumbnail/plain/<img>
with the zoomed version being:
https://cdn.bsky.app/img/feed_fullsize/plain/<img>

And avatars being:
https://cdn.bsky.app/img/avatar/plain/<img>
but seemingly just the same resolution and scaled accordingly.

**Comment by extesy** [comment]
Unfortunately bluesky doesn't have public access and I can't even register an account so it will have to wait until the decide to open their service to public.

**Comment by GrosPoulet** [comment]
@elylv i added a plug-in for bsky.app, it'll be available in next release of HZ+ (1.0.214).
BTW, i have no account on Bluesky for in-depth testing, so if there is any glitch let me know.
