### ISSUE TITLE
HoverZoom spams API requests on Reddit

### ISSUE THREAD

**Issue by AthosBenther** [extesy/hoverzoom#1257]
**Describe the bug**
When loaded with Reddit on /all multiple requests are sent to reddit.com/by_id/t3_*.json?raw_json=1, causing reddits API to go 429 very fast.

**To Reproduce**

Open Chrome Dev Tools
Go to /all
Check blocks of multiple requests to t3_something.json
Repeat once or twice and requests start responding with 429.
This hinders othe webb api usages as adding or removing subreddits from the filter

**Expected behavior**
Don't spam reddits api with multiple requests.

**Screenshots**
![image](https://github.com/extesy/hoverzoom/assets/50505642/33e6ecb9-e92f-457f-aba2-913af3061714)

**Desktop (please complete the following information):**
Win 10 PRO 22H2
Chrome 118

**Additional context**
Adding `||www.reddit.com/by_id/t3*` to uBlocks filter list blocks those requests and solve the problems, ~~aparently to no interference to HoverZooms functionality~~ but you lose the ability to hover over albums

**Comment by but-a-thought** [comment]
I believe this is also starting to cause old reddit to stop loading pages for a bit with 429 error. Adding the block as suggested to uBlock seems to stop the 429 error occurring again.

You can see others having the same issue: https://www.reddit.com/r/help/comments/1dtxt1c/http_error_429/

**Comment by globus243** [comment]
> I believe this is also starting to cause old reddit to stop loading pages for a bit with 429 error. Adding the block as suggested to uBlock seems to stop the 429 error occurring again.
> 
> You can see others having the same issue: https://www.reddit.com/r/help/comments/1dtxt1c/http_error_429/

This resolves the 429 errors but breaks the album-feature. Albums are then no longer viewable with HoverZoom+ when blocking the request.

**Comment by xconverge** [comment]
Thank you very much @extesy, looks good to me!

**Comment by dr3** [comment]
This is happening for me again, getting 429s very quickly
