### ISSUE TITLE
gettyimages

### ISSUE THREAD

**Issue by MHrbi** [extesy/hoverzoom#1261]
the extension stopped working on gettyimages about 6 months ago.

https://www.gettyimages.com/

## Steps to reproduce the problem (include image url here)
1. https://www.gettyimages.com/detail/news-photo/novak-djokovic-attends-the-blue-carpet-prior-to-the-nitto-news-photo/1786270450
2.
3.

**Comment by GrosPoulet** [comment]
@MHrbi i rewrote GettyImages plug-in, it now supports images & videos. 
Update'll be available in next release of HZ+ (1.0.212)
