### ISSUE TITLE
Hovering over an <a> tag with a base64 string in href freezes page and maxes CPU out

### ISSUE THREAD

**Issue by saada** [extesy/hoverzoom#13]
## HTML
![screen shot 2015-07-08 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/1087987/8579426/63f0270a-2569-11e5-8781-96b50384fe9a.png)

## Profiler Output
![screen shot 2015-07-08 at 12 04 48 pm](https://cloud.githubusercontent.com/assets/1087987/8579456/96e235ea-2569-11e5-8618-3d1510978ab7.png)
[Click here to see the suspicious line of code](https://github.com/extesy/hoverzoom/blob/9964714299135520dfe8f524a488a430f58bdcdf/plugins/default.js#L9)

![screen shot 2015-07-08 at 12 10 41 pm](https://cloud.githubusercontent.com/assets/1087987/8579614/761f26fa-256a-11e5-9324-e288dd66823d.png)

## CPU Usage
![screen shot 2015-07-08 at 12 01 02 pm](https://cloud.githubusercontent.com/assets/1087987/8579373/0da8e300-2569-11e5-8cd7-e16c5cc1ffdd.png)

**Comment by saada** [comment]
Here's the code snippet that needs to be optimized for base64 strings

```js
$('a[href]').filter(function () {
  return this.href.match(/\/[^:]+\.(?:jpe?g|gif|png|webm|mp4|svg|webp|bmp|ico|xbm)(?:[\?#].*)?$/i);
})
```

**Comment by diversario** [comment]
Not sure if the same case but on Facebook, Google images and many other sites hoverzoom basically kills Chrome every time it engages. Takes up to 10 seconds to display an image (during which Chrome is unresponsive).
