### ISSUE TITLE
HoverZoom causes website and tab to freeze

### ISSUE THREAD

**Issue by martimlobao** [extesy/hoverzoom#1305]
**Describe the bug**
HoverZoom causes the page and tab to freeze when visiting a specific website: https://www.areaprivada.pt/VD_ClientPortal_UI/Login?code=Ok

**To Reproduce**
1. Go to 'https://www.areaprivada.pt/VD_ClientPortal_UI/Login?code=Ok'
2. Click on anything (e.g. the login box, or right click anywhere)
3. Nothing happens and tab is unresponsive
4. Repeat steps 1-2 with HoverZoom disabled or with "https://www.areaprivada.pt" added to the blacklist and everything works normally.

**Expected behavior**
The page is supposed to load and function normally.

**Desktop (please complete the following information):**
 - OS: macOS 14.3
 - Browser: Chrome
 - Version v121

**Comment by younesbram** [comment]
also happened to me on chatgpt, https://www.reddit.com/r/ChatGPTPro/comments/19cme2y/does_uploading_an_image_to_chatgpt_cause_anyone/

**Comment by extesy** [comment]
@martimlobao @younesbram Can you please confirm if this is still a problem in version `1.0.214.2`?

**Comment by martimlobao** [comment]
@extesy fixed it for me, thanks! 😃
