### ISSUE TITLE
Hoverzoom not working for Streamable.com links anymore

### ISSUE THREAD

**Issue by germaloney11** [extesy/hoverzoom#131]
I noticed on reddit. It just shows a loading picture sign twice for a split second and doesn't open the video in hoverzoom anymore.

**Comment by germaloney11** [comment]
I have Hover Zoom+ 1.0.89 which is the most up to date version.

**Comment by crashnburn713** [comment]
I am having this issue as well.

**Comment by germaloney11** [comment]
Thought it might be NSFW spoiler tags that had messed it up but I tried one's without tags in the title or flairs and it's still not working. However, strangely enough, I found one link that was working today:

Working: https://www.reddit.com/r/MMA/comments/4qmkvi/joe_rogan_on_how_to_tell_fighters_apart/

Not working: https://www.reddit.com/r/MMA/comments/54925c/gabi_garcia_vs_destanie_yarbrough_weighin/

https://www.reddit.com/r/MMA/comments/5469o4/a_moment_of_pure_savagery/

https://www.reddit.com/r/MMA/comments/54eokn/spoiler_one_of_the_most_anticipated_rematches/

**Comment by germaloney11** [comment]
It has stopped working again :(

**Comment by jritz611** [comment]
not working for me

**Comment by extesy** [comment]
Streamable is using multiple CDN urls now so it's no simple to figure out video url.
