### ISSUE TITLE
Website freezes and doesn't respond when an embedded video is visible

### ISSUE THREAD

**Issue by NilsLehrfeld** [extesy/hoverzoom#1310]
## Description of the problem
On the FL Studio forums, if a post is viewed, that has a Videofile attached to it, the site, and browser tab freeze completely.
To get back I have to either close the tab or spam click the back arrow.

From my testing this only seems to happen when an MP4 file is present. Embedded youtube links and images do not cause this problem.
Not sure if that is necessary information, but the videos seem to be embedded with MediaElement.js

## Url of the page where the problem occurs
https://forum.image-line.com/viewtopic.php?t=322537
https://forum.image-line.com/viewtopic.php?t=322630

## Steps to reproduce the problem
1. Open the Website (you don't need to have an account)
2. Scroll until an embedded MP4 video is visible.
3. The browser tab does not respond anymore.

## OS version, extension version
Windows 10 22H2 & macOS Ventura 13.6.4
Extension: 1.0.213
Browser: Edge

**Comment by extesy** [comment]
I've tried in Chrome and I don't see this behavior so it's probably an Edge-specific issue.

**Comment by NilsLehrfeld** [comment]
I also did some more testing, and whats odd is, that I installed chrome again on my windows machine, and after installing the extension the problem showed up again.

My first thought after that was, maybe it is something about my specific PC, but then I tested the behaviour with the chrome browser on my girlfriends PC and it also froze.

To best share what I experience, I have recorded the issue in a short video.

## Further discoveries
1. After not closing the frozen tab, the "Page Unresponsive" pop-up appears.
2. If left untouched for a relative short amount of time, the website catches up and then freezes and the cycle continues.

https://github.com/extesy/hoverzoom/assets/25098260/132ba274-1900-4629-877f-4de4a2ff9b5d

**Comment by NilsLehrfeld** [comment]
Okay I have one more thing to to share.
I have gotten Access to another computer, where I first did test both Edge and Chrome, once more with the same freezing result.

Since Firefox was also installed on that Computer, I was curious how it would behave.

## Different behaviour in Firefox
When the extension is active the website does not freeze completely. Instead it starts lagging. Mostly noticeable when trying to scroll fast, and very easy to notice when trying to click on stuff, due to a massive input delay.


https://github.com/extesy/hoverzoom/assets/25098260/c1455c6e-2a1b-489a-966c-654855eedf19

**Comment by extesy** [comment]
Thank you for the recordings, this is very helpful!

**Comment by extesy** [comment]
@NilsLehrfeld can you please confirm if this is still a problem in version `1.0.214.2`? No need to record new videos if this problem still exists.
