### ISSUE TITLE
Streamable links all of the sudden not working 

### ISSUE THREAD

**Issue by francis826** [extesy/hoverzoom#1313]
**HoverZoom is not working with streamable links**

Within the last couple of weeks HoverZoom has stopped working on streamable links.

**To Reproduce**
1. Go to https://old.reddit.com/r/nba/
2. Open dev console
3. Hover any streamable link (there are many on this page as streamable is the only allowed video links)
4. See console error:

```
Error handling response: TypeError: Cannot read properties of null (reading 'getAttribute')
    at chrome-extension://pccckmaobkjjboncdfnnofkonhgpceea/plugins/streamable_a.js:8:50
    at chrome-extension://pccckmaobkjjboncdfnnofkonhgpceea/js/hoverzoom.js:3788:27
```

**Desktop:**
 - OS: Windows 10 (Also reproducible on MacOS)
 - Browser: Chrome
 - Version: 121.0.6167.161 (Official Build) (64-bit)

**Comment by extesy** [comment]
Fixed in c07071a279de5f711dea047e50feee4299ad7c49
