### ISSUE TITLE
HoverZoom on TikTok - Chrome Browser

### ISSUE THREAD

**Issue by electrikcheez** [extesy/hoverzoom#1316]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Steps to reproduce the problem (include image url here)
1. Log into TikTok
2. Go to my personal profile
3. Go to my 'Liked' videos
4. Hover mouse of a 'liked' video
5. HoverZoom should display the hovered version on top of the video, but currently does not

**Comment by extesy** [comment]
It's fixed by https://github.com/extesy/hoverzoom/pull/1314, will be available in the next release.
