### ISSUE TITLE
Feature request: Allow "Enter" to be a key that locks the image on screen

### ISSUE THREAD

**Issue by dzek69** [extesy/hoverzoom#1318]
**Is your feature request related to a problem? Please describe.**
I'm coming from other extension with similar functions (Imagus probably, I already forgot), it has the same lock image on screen feature, but it was under the Enter Key (either by default or I set it like that). I'm so used to do it even after half a year of using Hover Zoom + I still press it instead of the alternative I selected because of absence of Enter key in the drodown.

**Describe the solution you'd like**
Allow Enter key to be selected from the dropdown.

**Describe alternatives you've considered**
I tried `Shift` - it's a big key, next to Enter, but it's "not it".

**Additional context**
I think it wouldn't be a big deal to add Enter. Fingers crossed!

**Comment by extesy** [comment]
Implemented by https://github.com/extesy/hoverzoom/commit/de95fae177778cfe10f7757c7aba991b53d9a70b
