### ISSUE TITLE
HoverZoom not working properly with google images

### ISSUE THREAD

**Issue by Alikaname** [extesy/hoverzoom#1321]
## Description of the problem
HoverZoom doesn't immediately work in google images when searching for something, it works only after I click on an image and close it.
Only the second image works to hover zoom for some reason.
## Url of the page where the problem occurs (not the image url)
any google image search
## Steps to reproduce the problem (include image url here)
1.google something and go to the images tab
2.hover the mouse over an image
3.no zoom happens

## OS version, extension version
Hoverzoom version: 1.0.214.2
Brave Version: 1.64.109 Chromium: 123.0.6312.58

**Comment by GrosPoulet** [comment]
@Alikaname i fixed Google Images plug-in (#1326), it'll be available in next release of HZ+.
@extesy it might qualify for a hotfix, up to you.
