### ISSUE TITLE
Add support for : King of the North auctions

### ISSUE THREAD

**Issue by csilvest** [extesy/hoverzoom#1332]
**What is the URL of the website**
https://kotnauction.com/

**Why we should add support for the website?**
Too painful to use this website without Hoverzoom.  Hoverzoom rocks, by the way!

**Comment by GrosPoulet** [comment]
@csilvest i added a plug-in for kotnauction.com, it'll be availabe in next release of HZ+ (1.0.216).

**Comment by csilvest** [comment]
Thank you!
