### ISSUE TITLE
Hoverzoom loads things from the previous Google images page

### ISSUE THREAD

**Issue by mauricecaaaaaben** [extesy/hoverzoom#135]
Screenshot:
https://gfycat.com/PowerlessSelfishAlpaca
Pages:
Original page: https://www.google.com/search?q=1920x1080+wallpaper&safe=strict&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiTt8zrkZrPAhUD3YMKHZqdD4EQ_AUICCgB&biw=1920&bih=950#imgrc=_
Issue page: https://www.google.com/search?q=1920x1080+wallpaper&safe=strict&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiTt8zrkZrPAhUD3YMKHZqdD4EQ_AUICCgB&biw=1920&bih=950#safe=strict&tbm=isch&q=1920x1080+windows+10+wlalpaerp&imgrc=_

**Comment by GrosPoulet** [comment]
It works fine now
