### ISSUE TITLE
Can't use in X.com

### ISSUE THREAD

**Issue by FogChamp** [extesy/hoverzoom#1351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by unclnis** [comment]
They've completed migration from twitter.com to x.com
All images are under the new domain. 

Happening for me as well. Win 11, Vivaldi 6.7.3329.31 with extension ver 1.0.216

**Comment by ibanks42** [comment]
I've created a pull request that fixes this #1352

**Comment by extesy** [comment]
Thanks for a PR, @ibanks42! The fix will be available in version `1.0.217`.
