### ISSUE TITLE
Add support for polona.pl

### ISSUE THREAD

**Issue by vitaly-zdanevich** [extesy/hoverzoom#1360]
**What is the URL of the website**
https://polona.pl/press/b846927e-a54c-45e9-a652-70f8566b7938/objects?page=0&size=24&sort=OLDEST

![image](https://github.com/extesy/hoverzoom/assets/3514015/c9374c18-1e77-44a7-af59-e99cf1cd8b64)

**Comment by GrosPoulet** [comment]
@vitaly-zdanevich i added a plug-in for polona.pl (#1367), it'll be available in next release of HZ+ (1.0.218)
