### ISSUE TITLE
AddOn don`t work at startpage.com

### ISSUE THREAD

**Issue by Werner-St** [extesy/hoverzoom#1361]
This AddOn don`t work at startpage.com pictures

the page was recently changed

https://www.startpage.com

OS: Win10

Browser: Firefox 126

**Comment by Werner-St** [comment]
Is this still done or will it never work on Startpage anymore?

**Comment by extesy** [comment]
Not done yet.

**Comment by GrosPoulet** [comment]
@Werner-St i fixed plug-in for startpage.com, fix'll be available in next release of HZ+ (1.0.220)
