### ISSUE TITLE
Add support for : Nextdoor.com

### ISSUE THREAD

**Issue by mk-sw** [extesy/hoverzoom#1362]
**What is the URL of the website**
https://nextdoor.com

**Why we should add support for the website?**

Nextdoor.com has a "For Sale or Free" section with photos of each item. The photos are small. Each item has to be opened individually to see a more detailed photo which is very time consuming.  Being able to see larger photo without having to open each item would save a lot of time.

**Comment by mk-sw** [comment]
Should be "New Plugin Request" instead of Enhancement.

**Comment by GrosPoulet** [comment]
@mk-sw i added a plug-in for **nextdoor.com**, it'll be available in next release of HZ+ (1.0.218).

![image](https://github.com/extesy/hoverzoom/assets/23529041/f8c05e0e-56ac-4475-881b-42da8d84914e)

**Comment by mk-sw** [comment]
Wonderful support. I'm impressed.
Thanks.
