### ISSUE TITLE
HoverZoom no longer working for redgifs links on reddit

### ISSUE THREAD

**Issue by 0neW0rld** [extesy/hoverzoom#1364]
**Describe the bug**
HoverZoom no longer working for redgifs links on reddit. Nothing happens when mousing over redgifs thumbnails or links. Other embeds still behave properly, such as those hosted via i.redd.it and preview.redd.it.

**To Reproduce**
1. Go to any NSFW subreddit
2. Mouse over any post with a redgifs link

**Expected behavior**
Zoomed video/gif should appear on mouse over

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version 1.67.119

**Additional context**
Neither reddit nor redgifs is in my site blacklist.

**Comment by extesy** [comment]
@0neW0rld I need specific links, not just "any subreddit"

**Comment by NonMuss** [comment]
> @0neW0rld I need specific links, not just "any subreddit"

I hope this will help some.
Subreddit - https://old.reddit.com/r/NakedOnStage/
Doesn't work on this specific one - https://old.reddit.com/r/NakedOnStage/comments/1ewum3y/les_indes_galantes_gif_9/

Doesn't work for redgifs on most that I've come across. I can link more if it will help.

**Comment by extesy** [comment]
Fixed by 8998271055bae2d79873a7d504965eb6c314e147. Will be available in the next release.
