### ISSUE TITLE
Imgur front page

### ISSUE THREAD

**Issue by am31008** [extesy/hoverzoom#1377]
**Describe the bug**
While scrolling front page of Imgur, anything with .mp4 video will not play in overlay or with multiple meme's attached (1/16 or 1/anything) will not scroll through properly.

**To Reproduce**
1. Go to 'www.imgur.com'
2. Find any item with a video or multiple attachments
3. Singular pictures will zoom as intended and even the first image of multiple post but will not scroll to the others within post.
4. ![image](https://github.com/extesy/hoverzoom/assets/73917480/5e8fa67a-0279-4dab-b65a-6aa1b53616ae)

**Expected behavior**
In example, it should be able to scroll through all 47 screenshots there.  There should be 
**Screenshots**
![image](https://github.com/extesy/hoverzoom/assets/73917480/b6ae124b-c51b-47fe-b35e-95766eab2f3c)
![image](https://github.com/extesy/hoverzoom/assets/73917480/16795098-ea4d-45ac-8edf-ec8df31de1fb)
![image](https://github.com/extesy/hoverzoom/assets/73917480/427b3545-761f-4ca1-9d41-df440958fdd2)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chorme
 - Version 126.0.6478.127

**Additional context**

**Comment by am31008** [comment]
Am I supposed to update my plugin or was that something to put on your "to-do" list?  I have removed and reinstalled this plug in several times through the Chrome extension store.

**Comment by am31008** [comment]
I currently have 1.0.218 installed on my PC.

**Comment by GrosPoulet** [comment]
@am31008 label "update existing plugin" means a fix is required on dev side, i'm working on it.

**Comment by GrosPoulet** [comment]
@am31008 i fixed Imgur plug-in, see #1403 
@extesy could you prepare next release of HZ+ please ? I'm done with fixes for this week :-)

**Comment by am31008** [comment]
You, my good person, are an absolute life saver.  It is already working.
