### ISSUE TITLE
Add support for : Raindrop.io

### ISSUE THREAD

**Issue by ilkka8** [extesy/hoverzoom#1378]
**What is the URL of the website**
[https://www.raindrop.io/](https://www.raindrop.io/)
[https://app.raindrop.io/](https://app.raindrop.io/)

**Why we should add support for the website?**
Raindrop is a popular bookmarking website, and it would make this tool much more easy to use.

**Comment by GrosPoulet** [comment]
@ilkka8 i added a plug-in for raindrop.io (only tested on website, not the app).
It'll be available in next release of HZ+ (1.0.218)
