### ISSUE TITLE
Add support for : https://uinotes.com

### ISSUE THREAD

**Issue by sylva98** [extesy/hoverzoom#1381]
**What is the URL of the website**
https://uinotes.com

**Why we should add support for the website?**
Describe why you need hoverzoom for that website

**Comment by GrosPoulet** [comment]
@sylva98 i added a plug-in for UInotes, it'll be available in next release of HZ+ (1.0.219).

![image](https://github.com/user-attachments/assets/efad0f13-fd04-4641-bcaf-07fd523ff996)

**Comment by extesy** [comment]
@GrosPoulet please let me know when you are done with the current batch of updates, so that I can cut a next release

**Comment by GrosPoulet** [comment]
@extesy I'm busy fixing Imgur plug-in but it is more complicated than expected, so you can publish next release right now if you like.
