### ISSUE TITLE
HoverZoom+ spams browser console with `Error: Promised response from onMessage listener went out of scope` errors

### ISSUE THREAD

**Issue by Atulin** [extesy/hoverzoom#1389]
**Describe the bug**
![image](https://github.com/user-attachments/assets/94455ef2-4399-410d-b65d-d16d837f2db8)

**To Reproduce**
1. Open console
2. See errors

**Expected behavior**
1. Open console
2. Don't see errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 130.0b3 (64-bit)

**Additional context**
```js
function init() {
    // Load options
    options = loadOptions();

    // Bind events
    chrome.runtime.onMessage.addListener(onMessage);
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//  Error happens here

    manageHeadersRewrite();
}
```

**Comment by extesy** [comment]
@Atulin link? I don't see these errors.

**Comment by Atulin** [comment]
Huh, it will be hard to provide a link since it happens on `https://localhost:5001`

**Comment by extesy** [comment]
Unless it happens with the supported use case (real web sites on the internet), I can't do anything about it.
