### ISSUE TITLE
No longer works on e621

### ISSUE THREAD

**Issue by KhedWolf** [extesy/hoverzoom#1397]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Hoverzoom used to work on e621, now it doesn't work anymore in the post index page nor the popular items page although it works fine if you open a specific's post page.

## Url of the page where the problem occurs (not the image url)
**⚠️ NSFW WARNING**

https://e621.net/posts?tags=rating%3As+score%3A%3E250

https://e621.net/popular

## Steps to reproduce the problem (include image url here)
1. Visit e621.net and click on posts or search with tags (alternatively, use the links above)
2. Hover on any post in the index page, the image doesn't enlarge

## OS version, extension version
Windows 11 Enterprise 23H2, Extension Version 1.0.218 on Librewolf Version 127.0.1-1 (64-bit)

**Comment by GrosPoulet** [comment]
@KhedWolf i fixed e621 plug-in, fix'll be available in next release of HZ+ (1.0.219).
