### ISSUE TITLE
i.reddituploads.com domain

### ISSUE THREAD

**Issue by JeffreyCA** [extesy/hoverzoom#140]
Hoverzoom+ currently does not work with the domain: https://i.reddituploads.com/
Example URL: https://i.reddituploads.com/a136ed37bb4b4ce2b8200f2506f1afb6?fit=max&h=1536&w=1536&s=480c59a7f3e925a2bcfa1fdae7d293da

Please consider supporting it, thanks.

**Comment by extesy** [comment]
@JeffreyCA Please provide a page on reddit itself where hoverzoom doesn't work with this domain.

**Comment by JeffreyCA** [comment]
Example: https://www.reddit.com/r/mildlyinteresting/comments/54af29/a_branch_of_my_rose_plant_mutated_to_become_super/

That was on the front page, but hovering over the title does not activate the image preview. I think it's because the title's URL redirects to the comments of that thread, rather than the URL of the image.

However, you can see beside the title it says "(i.redd.it)" instead of "self.mildlyinteresting":

![untitled](https://cloud.githubusercontent.com/assets/9157833/18811339/881ff1e0-827a-11e6-8e1d-71830dbad197.png)


To be specific, I don't think image posts from "i.redd.it" is working with hoverzoom+.

**Comment by rakion99** [comment]
for me its working fine
![01](https://cloud.githubusercontent.com/assets/1360084/18811946/66ae8784-8288-11e6-80c6-43cb96aa9365.png)

**Comment by JeffreyCA** [comment]
Ahh it was conflicting with the Reddit Enhancement Suite (RES) chrome extension, I disabled that and the image loads.
