### ISSUE TITLE
Add support for : e6ai.net

### ISSUE THREAD

**Issue by KyLeggiero** [extesy/hoverzoom#1401]
**What is the URL of the website**
https://e6ai.net/

**Why we should add support for the website?**
Hoverzoom+ already supports many other boorus. This is a new one! Should be simple to add and self-explanatory why it's good to add there

**Comment by GrosPoulet** [comment]
@KyLeggiero i added **e6ai.net** to the list of supported websites. This update will be available in next release of HZ+ (1.0.220).
If you find other boorus not supported by HZ+ do not hesitate to open a ticket.
