### ISSUE TITLE
Most Twitch clips failing to load

### ISSUE THREAD

**Issue by retraenn** [extesy/hoverzoom#1406]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
A lot of Twitch clips are not loading. The error I'm getting in my browser console is _NS_BINDING_ABORTED_.
I don't see a pattern to which clips work and which don't.
I'll include a broken and working example in the Steps below.
Here's a screenshot of the network tab error if it helps. https://i.imgur.com/nmCbOL4.png

## Url of the page where the problem occurs (not the image url)
https://www.twitch.tv/

## Steps to reproduce the problem (include image url here)
1. This **does not** work https://www.twitch.tv/vedal987/clip/FlaccidTolerantCardTBTacoLeft-PqdJYwZ7itEPYzLS
2. This one works. https://www.twitch.tv/geezgiselle/clip/ArtisticSuperPandaBCWarrior-J9kvPgtpeCCI3WUA

## OS version, extension version
Windows 10
Firefox 129.0.2
Hoverzoom 1.0.219

**Comment by DeadOblivion78** [comment]
I'm experiencing the same issues. I'm also experiencing error 429 as well as this causes reddit to temporarily not load.

**Comment by zekecounter** [comment]
same issue still persist 

go to https://www.reddit.com/r/LivestreamFail/

then hover ur mouse cursor on one of the posted clips, You will only get the loading icon.

**Comment by zekecounter** [comment]
> After messing around a little it looks like twitch returns no Clip URI for some reason on most clips.
> 
> I fixed the issue by changing Line 61 in plugins/twitch_a.js from `let clip_uri = t.clip_uri;` to `let clip_uri = r.data.clip.videoQualities[0].sourceURL;`
> 
> It doesn't seem to break anything else but this probably isn't the proper way of fixing the issue, I don't really know what I'm doing but thought I'd leave this here in case it helps.

how did u change this? i dont see an option in the extension that woud allow me to input this new change

**Comment by extesy** [comment]
@retraenn do you mind submitting a pull request for your fix?

**Comment by extesy** [comment]
Fixed by #1424, will be available in the next release. Thank you, @retraenn!
