### ISSUE TITLE
Add support for : Brave Image Search

### ISSUE THREAD

**Issue by ounrequitedo** [extesy/hoverzoom#1420]
**What is the URL of the website**
https://search.brave.com/images?q=doggie

**Why we should add support for the website?**
There is similar functionality for google image search, would be nice to get off the google train for image searches too, thanks.

**Comment by Eiion** [comment]
Came here to suggest the same, glad someone else already made the suggestion. Though this to me appears to be a browser wide issue, not just the image search. No matter the website I visit with Brave Hover Zoom does not work.

**Comment by GrosPoulet** [comment]
@ounrequitedo @Eiion  i added a plug-in for search.brave.com, it'll be available in next release of HZ+ (1.0.221)
Not tested on Brave browser, but works fine in Chrome
