### ISSUE TITLE
Redgifs links not working on reddit (403 response)

### ISSUE THREAD

**Issue by Frank-Belanger** [extesy/hoverzoom#1422]
**Describe the bug**
Links marked as v3.redgifs.com or redgifs.com are not working properly. The network response status code when hovering over these links gives a 403 forbidden response.

**To Reproduce**
1. Go to reddit.com, on any nsfw subreddit. For example, you may go on reddit.com/r/gonewildcouples
2. Open dev tools and go to network tab 
3. Hover over any link that shows as a "v3.redgifs.com" or "redgifs.com" link
4. See the error: 403 forbidden status code (net::ERR_BLOCKED_BY_ORB)
5. See the loading icon that never actually shows anything

**Expected behavior**
An actual video from hovering instead

**Screenshots**
![Annotation 2024-10-01 103818](https://github.com/user-attachments/assets/771cc38d-7459-4687-8535-77e2af8c7f68)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 129.0.6668.70 (64-bit)

**Additional context**
This may have something to do with RES (reddit enhancement suite) as the problem does not seem to be reproductible on windows 11

**Comment by extesy** [comment]
It works fine for me, maybe there's a conflict with some other extension.

**Comment by Frank-Belanger** [comment]
I have tried incognito with only hoverzoom for a active extension and it doesn't work. I am on the "old" reddit however

**Comment by pdmk** [comment]
Same here

It doesn't work for last month or so. Tested in Edge and Firefox.

Other extensions used: uBlock origin, Search by image, Smart HTTPS, Dark reader

**Comment by JohnPokoro** [comment]
Not working for me either, stoped around the same time as the others commenting.

I tried both Firefox (131.0 64 Bit) and Chrome (129.0.6668.90 64 bits)

Tested with all extensions disabled and with Ad Block 6.9.2, Reddit Enhancement Suite 5.24.7 on

**Comment by extesy** [comment]
Make sure you have the following option enabled in extension settings:
![image](https://github.com/user-attachments/assets/ac0dd2a1-dfaf-4fce-afd7-9d7af4de538e)

**Comment by dbasinge** [comment]
No change here.

> Make sure you have the following option enabled in extension settings: ![image](https://private-user-images.githubusercontent.com/65872/373919699-ac0dd2a1-dfaf-4fce-afd7-9d7af4de538e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjc5MDMsIm5iZiI6MTcyODIyNzYwMywicGF0aCI6Ii82NTg3Mi8zNzM5MTk2OTktYWMwZGQyYTEtZGZhZi00ZmNlLWFmZDctOWQ3YWY0ZGU1MzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE1MTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNDE3OWY4MDYxMDc5MGUzNTMyNTI2MjUyMGZjYmEzNzQxMmEzMmRmMzc2NWJkYmVkOGVmMTNhMDgzNDgxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wWLoeSuXGbeYEUPMu4M9q8EqKwW-IjD6Vr4vme_VUvk)

No change.

**Comment by pdmk** [comment]
> Make sure you have the following option enabled in extension settings: ![image](https://private-user-images.githubusercontent.com/65872/373919699-ac0dd2a1-dfaf-4fce-afd7-9d7af4de538e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzEyOTUsIm5iZiI6MTcyODIzMDk5NSwicGF0aCI6Ii82NTg3Mi8zNzM5MTk2OTktYWMwZGQyYTEtZGZhZi00ZmNlLWFmZDctOWQ3YWY0ZGU1MzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZTMxNGExZDE1MDIwMzE0OWFlYWJkNzkyNGYwMWI5MTQ4ZWZlMjNlMWI5OWMzMzRlMjcxNDdlMzE1YjE2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KOEuUWzV6ycjI-OFRawmG6RufwAE2IEif-SgMuzFv7c)

This worked for me! thanks

**Comment by extesy** [comment]
@dbasinge did you press "save" button after enabling it?

**Comment by dbasinge** [comment]
> @dbasinge did you press "save" button after enabling it?

Yes

**Comment by dbasinge** [comment]
> @dbasinge did you press "save" button after enabling it?

Changing network.http.sendRefererHeader to 1 seems to fix hoverzoom, breaks other sites though,.

https://github.com/extesy/hoverzoom/issues/1417#issuecomment-2354095982

**Comment by JohnPokoro** [comment]
> Make sure you have the following option enabled in extension settings: ![image](https://private-user-images.githubusercontent.com/65872/373919699-ac0dd2a1-dfaf-4fce-afd7-9d7af4de538e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjUxMjIsIm5iZiI6MTcyODI2NDgyMiwicGF0aCI6Ii82NTg3Mi8zNzM5MTk2OTktYWMwZGQyYTEtZGZhZi00ZmNlLWFmZDctOWQ3YWY0ZGU1MzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAxMzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMGY1NDQwMWQxMmM0NGU0YmJiMDdmNmYxZTc5ODEyNzQ1ZTk0MDE0ZWNiNzM5YzAzMTFlNjBmMmRjZWQwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BzUNf2k8mznPlavt8-iqXsGQXWQOlIIWgnTDu0_fzx4)

This worked for me (after clicking on Save) 👌
Thank you
