### ISSUE TITLE
HoverZoom not working properly on Flickr's search results

### ISSUE THREAD

**Issue by MikeBlackwell** [extesy/hoverzoom#1427]
**Describe the bug**
As of several days ago, HoverZoom is not working properly on Flickr's main search results, on two different Macs running two different operating systems, on both Firefox and Chrome. Still works correctly on download popup menu and works partially on thumbnails below images.

**To Reproduce**
1. Go to 'flickr.com'
2. Search for something (in this case, 'f-4 phantom')
3. Hover mouse over one of the search results
4. Bug: No enlarged version appears (attached images 1C and 1F)
5. Click on one of the images
6. Hover mouse over one of the thumbnails below the primary image, showing other items in the uploader's portfolio
7. Enlarged version appears, but isn't very big. (attached images 2C and 2F) The enlarged version used to fill the screen if the source image was large enough.
8. Click the Download popup menu (downward pointing arrow) to lower right of main image, and hover mouse over one of the sizes
9. No bug: HoverZoom works properly (attached images 3C and 3F)

**Expected behavior**
HoverZoom used to show full size enlargements of all images in Flickr search results. Now only works properly in the download popup menu.

**Desktop (please complete the following information):**
Two different Macs, a late 2012 Mac Mini running OS 10.12 and an Apple M2 Pro running OS 14.5 Sonoma. The older Mac (at home) is running the latest versions of Firefox and Chrome that the machine supports, but I don't have the version numbers in front of me. On the newer Mac (at work), Firefox is version 131.0.3 and Chrome is 129.0.6668.101.

**Screenshots**
Six screenshots are attached, though they may not have uploaded in numerical order as described herein. Images 1C and 1F show the search results from Chrome and Firefox, respectively. Not much to see here, as nothing is happening. Images 2C and 2F show the small thumbnail enlargements, and images 3C and 3F show the download popup menus, which are working properly.

<img width="1894" alt="1F  Screenshot 2024-10-14 at 10 29 50 AM" src="https://github.com/user-attachments/assets/88193007-4f74-4508-bcfd-dff4d5239365">
<img width="1895" alt="1C  Search results, Chrome" src="https://github.com/user-attachments/assets/a916e8d4-f4c6-41a0-8245-b46d15eafccd">
<img width="1894" alt="3F  Popup menu, Firefox" src="https://github.com/user-attachments/assets/76a8d3b4-adcc-49f7-904a-27ae39da88d0">
<img width="1894" alt="2F  Small enlargement of thumbnail, Firefox" src="https://github.com/user-attachments/assets/e1926aa2-61c8-4578-bf8b-ae1b41e3262e">
<img width="1895" alt="3C  Popup menu, Chrome" src="https://github.com/user-attachments/assets/0c4c04f4-798b-41e7-a608-0a7852639eeb">
<img width="1784" alt="2C  Small enlargement of thumbnail, Chrome" src="https://github.com/user-attachments/assets/a5d65a6d-c429-4b74-8878-62e8964ff1c9">

**Comment by extesy** [comment]
@MikeBlackwell Thank you for a detailed bug report. Web sites regularly change their designs which sometimes breaks hoverzoom, so it needs to be updated. This time it was Flickr's turn so please wait for the update.

**Comment by MikeBlackwell** [comment]
Any news on a fix for this yet?

**Comment by romulo-godoi** [comment]
I have the same problem

**Comment by extesy** [comment]
@GrosPoulet Can you help with this one? It looks like you wrote most of the flickr plugin.

**Comment by GrosPoulet** [comment]
@MikeBlackwell @romulo-godoi @extesy Issue fixed by #1485, this is a workaround as Flickr API can not be used anymore (for now...)
