### ISSUE TITLE
Hovering images doesn't work on eksisozluk.com

### ISSUE THREAD

**Issue by vault21** [extesy/hoverzoom#1429]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
eksisozluk.com owns an image deposit website where users can upload images and use a shortlink to use in their posts. this image website is quite similar to imgur and it uses a shortened URL (https://soz.lk). I could normally hover the mouse cursor to any link that starts with https://soz.lk and popup the hoverzoom popup frame to preview the image but it doesn't work anymore.

## Url of the page where the problem occurs (not the image url)
You can check this post as an example: https://eksisozluk.com/entry/165182991

In this post, someone wrote about Al Pacino and used links to include images in the post. "görsel" means image in Turkish so normally you could hover wherever it says "görsel" and be able to preview the image but it doesn't work anymore. Those "görsel" links use soz.lk short URL form but when you click and open the actual image deposit website, you'll see that short URL will be expanded as https://eksisozluk.com/img/

## Steps to reproduce the problem (include image url here)
1. Visit this post on eksisozluk.com as an example: https://eksisozluk.com/entry/165182991
2. Try to hover "görsel" to preview the image. It won't work.

**Comment by LiliaDoe** [comment]
Seems to work for me

**Comment by extesy** [comment]
@LiliaDoe It doesn't work for me in Chrome when I hover over any of the six "görsel" links at the bottom.

**Comment by LiliaDoe** [comment]
Hm, I see that too on Chrome

**Comment by LiliaDoe** [comment]
For some reason the ajax request isn't returning any data on chrome.

**Comment by LiliaDoe** [comment]
#1456 should fix this
