### ISSUE TITLE
Add support for : sh.reddit.com

### ISSUE THREAD

**Issue by michealespinola** [extesy/hoverzoom#1432]
**What is the URL of the website**
https://sh.reddit.com/

**Why we should add support for the website?**
`sh.` is the version of reddit that is under development to be the next public version. It is the current version that most closely matches the functionality of the official mobile client and contains all of the newest moderation tools available officially for the platform. It is the form of the reddit website that most moderators depend on, as well as being openly used by many non-moderator users.

Thank you for your consideration!

**Comment by extesy** [comment]
Fixed by https://github.com/extesy/hoverzoom/commit/8e033f613eb2d8d2259b6db0fc599443fd877fbf, will be available in next release
