### ISSUE TITLE
Scroll Wheel Only Goes Forward in Albums

### ISSUE THREAD

**Issue by chrisgp123** [extesy/hoverzoom#144]
Scroll wheel used to be able to go back and forth through albums on Reddit, now both scroll directions go forward.

**Comment by extesy** [comment]
Still works both ways for me. Please provide url of the page where it happens.

**Comment by chrisgp123** [comment]
So I believe this is more of an OS Sierra issue, not necessarily a Hoverzoom issue. Erratic scrolling with external mice since 10.12. But still getting only fwd scrolling in reddit for imgur albums.
