### ISSUE TITLE
Can't get the extension to work

### ISSUE THREAD

**Issue by rr20eid10** [extesy/hoverzoom#146]
Hi

I've installed the extension but it doesn't do anything.  

1.  I click the icon = nothing happens. 
2.  I double-click the icon = nothing happens.  
3.  When I right-click, I get a context menu but nothing on that menu actually makes the tool work. 

The instructions say that **this extension is compatible with my device** (PC) and that **the icon will only show if it can act on the page**.  However, I've been to several pages, even Yahoo, and I can't get the tool to work at all.  

How do I get this tool to work? I'm Win 8.1, Chrome Version 53.0.2785.143 m.  Thanks.

![hoverzoom-doesntwork](https://cloud.githubusercontent.com/assets/6556523/19223339/537b0e30-8e3b-11e6-8ec9-2b2dad61f9ec.png)

**Comment by extesy** [comment]
You should go the page that holds images, for example http://reddit.com then hover your mouse over the image.
