### ISSUE TITLE
[regression] Action key > Lock Image on click > right click not as reliable

### ISSUE THREAD

**Issue by cannibalox** [extesy/hoverzoom#1487]
**Describe the bug**
in recent builds, when the settings `advanced > Action key > Lock Image on click` is set to `right click` :
sometimes the right click menu will appear preventing the lock image behavior.
at other times it will work, but then once the image is locked, the right click doesn't trigger the contextual menu anymore.

**To Reproduce**
set ``advanced > Action key > Lock Image on click > right click`, then hover images, right click. sometimes it will fail. if it works, try to enable the right click menu : it doesn't appear
 
**Expected behavior**
in previous builds (I believe before commit #1472), it was working flawlessly : 
. RMB would lock the image without the contextual menu appearing
. once image is locked, a new RMB would trigger the context menu so we can interact with the locked image

`right click` to lock image is the default in Imagus, and it's useful for keyboardless browsing. Access to the right click menu is important to use addons like web clippers, image annotation, etc...

**Desktop (please complete the following information):**
 - win11 23h2
 - chromium 131
 - H+ Version 1.0.223

**Comment by extesy** [comment]
@LiliaDoe this looks like one of your recent changes

**Comment by LiliaDoe** [comment]
I have a new pr coming which will fix this. Just haven't fully tested it

**Comment by cannibalox** [comment]
in 1.0.225, when `Lock image on screen` is set to `right click` : once the image is locked, it's not possible to display the right click context menu using right click. 
Using other hotkeys to lock an image, we can still display the right click context menu to save the image.

**Comment by extesy** [comment]
How do you expect the same hotkey to perform two different actions?

**Comment by cannibalox** [comment]
that's how it used to work :

. right click when hovering will lock the image
. once hovered, right click is not intercepted and triggers the browser context menu

it was the behavior before the commit that broke the feature (it works the same way in imagus).
that way you can lock the image to inspect and then still have access to the context menu for addons (like save to a web service, etc)

**Comment by extesy** [comment]
@LiliaDoe it looks like there's still some follow-up fix needed

**Comment by LiliaDoe** [comment]
Oh I see! I'll get on that. A temporary solution is holding right click after locking the image should pull up the context menu, if it's not set to something too
