### ISSUE TITLE
No zooming on Instagram

### ISSUE THREAD

**Issue by kovacsattila-hun** [extesy/hoverzoom#149]
Enabled to Instagram on Plugins, but no zooming photos!

(on Google Chrome, latest Hover Zoom GOLD! 1.0.89)

Please fix!
Thank you very much!

**Comment by kovacsattila-hun** [comment]
No always zooming original size. Only 640x640 resolution.

**Comment by extesy** [comment]
@kovacsattila-hun please submit your bug for the extension you are using - https://github.com/superlime/HoverZoomGold

**Comment by kovacsattila-hun** [comment]
I'm using Hover Zoom+ already.

Hover Zoom+ 1.0.92

(I first tried the Hover Zoom Gold!)

**Comment by extesy** [comment]
Fixed in b68c6728db9be8a5261c8ddf2010452421b2f0d6

**Comment by kovacsattila-hun** [comment]
Unfortunately it still can not give the original sized image of the zoomed image.
Max zoomed size by Hover Zoom+ 1.0.93 with the newest Instagram plugin:    640x640
And original size of photo example: 1080x1080 or 750x937

(sorry, little speak english)

**Comment by extesy** [comment]
Is ^^^ something you can look at, @smaltby?
