### ISSUE TITLE
Reddit - Zoom only shows the thumbnail for images, no videos, full images, extra images, etc.

### ISSUE THREAD

**Issue by Thatguyyoumightknow** [extesy/hoverzoom#1499]
## Description of the problem
If you are on compact view and hover over the thumbnail of a post with an image, it only shows a slightly larger version of the thumbnail, in terrible resolution and most of the image missing. This also happens if hovering over the thumbnail for a post with multiple images (only shows the thumbnail image and not any of the other images). Posts with videos on them don't show anything at all.
Example:
![Capture](https://github.com/user-attachments/assets/5ce239fd-4976-4089-8a47-debb6d6d7216)

When trying to highlight over an image or slideshow post, the following shows up in the console:
![Capture2](https://github.com/user-attachments/assets/648ec117-4ecb-48c4-94eb-7ccc0f49aa00)
(Nothing happens when highlighting over videos)

## Url of the page where the problem occurs (not the image url)
www.reddit.com/r/all (any other page on the site should also be affected)

## Steps to reproduce the problem (include image url here)
1. Open www.reddit.com/r/all
2. Set view to compact
3. Hover over any image or slideshow image and observe that only the thumbnail already shown at a slightly larger resolution is displayed
4. Hover over any video and observe that nothing happens
Note: Images on main www.reddit.com sometimes work, and will carry over if viewed on www.reddit.com/r/all or other pages.

## OS version, extension version
Win 10 64-bit, Chrome 131.0.6778.109, Hover Zoom+ 1.0.223
Also tested on Firefox (latest version as of issue posting. Don't have it installed anymore to get specific version)

**Comment by extesy** [comment]
@Thatguyyoumightknow Does this issue only happen in compact view, with all other views unaffected?

**Comment by Thatguyyoumightknow** [comment]
Mostly similar error occurs on Card view as well.

Videos load with no issues or errors.
Posts with multiple images load the image, with ability to scroll through the other images in the post, but still output an error in the log
Posts with one image don't load the image at all and output the error.

Console error from viewing a single image post on card view:
![Capture](https://github.com/user-attachments/assets/1451b8ca-b4e6-43e0-8b94-50a4245e5ca9)

**Comment by LiliaDoe** [comment]
I'll look into it. My previous fix no longer seems to work for sh.reddit
