### ISSUE TITLE
1.0.224 Broke all fuctionality on Firefox

### ISSUE THREAD

**Issue by ANDRUOMEDA13** [extesy/hoverzoom#1502]
As of update 1.0.224, this extension has fully broken for me

Hover over a image link and it dims the background but never shows an image on every site

**Desktop**
 - OS: WIN 11
 - Firefox Browser 133.0.3

**Comment by Kissaki** [comment]
Still works for me

* 1.0.224
* 133.0.3

for example, hovering over your avatar

![](https://github.com/user-attachments/assets/7be60a13-7574-432b-98b7-d61db4c6edd9)

**Comment by extesy** [comment]
@ANDRUOMEDA13 Bug report form exists for a reason. Please use it.
