### ISSUE TITLE
Since 1.0.224 HoverZoom is not working on firefox

### ISSUE THREAD

**Issue by NeXiik** [extesy/hoverzoom#1504]
Same issue as https://github.com/extesy/hoverzoom/issues/1502 which was closed without any help.
Since last update (1.0.224) hoverZoom stopped working on firefox.

1. point mouse cursor on picture.
2. loading icon blinks, but no picture is shown.
3. when hovering on video, only audio is playing.

Expected behavior:
for it to work?

I dont have screenshots of it not working.

Desktop
 - OS: Win 11 pro 21H2
 - Browser:  firefox 133.0.3 64bit
 - Version: 1.0.224

Restart of pc didn't help.
On chrome which is still on 1.0.223 it works.

**Comment by LiliaDoe** [comment]
I cannot reproduce this with Firefox 133.0.3 (64-bit) on windows 10. Have you tried resetting your settings? What sites have you tested on?

**Comment by NeXiik** [comment]
Ok. After resetting the Hoverzoom settings, it seems to work.
Then I began to enable the settings I had and the Ambient light is what it broke again.
I had mine set to 3% edge and 0% transparency. 
Thank you.

**Comment by LiliaDoe** [comment]
Thank you for bringing the issue with ambiant light up. That issue is reproduceable.
