### ISSUE TITLE
Hover Works but Will Not Save

### ISSUE THREAD

**Issue by JSGestalt** [extesy/hoverzoom#154]
I updated Google and then re-downloaded Hover Zoom+ Now the icon is different and at first didn't appear. I assume this is because of the update. Now none of the shortcut keys are working. Images will not zoom, open in a new window, save or progress through galleries. Only the hover part is working.

**Comment by extesy** [comment]
@JSGestalt Please click on the icon, open extension options and there you can configure the parameters you need, including shortcuts.

**Comment by JSGestalt** [comment]
Well yeah. I did that and it didn't work but please, feel free to go ahead
and close the ticket before finding out that I did that.
