### ISSUE TITLE
Please add the resized image the resize percent to corner!

### ISSUE THREAD

**Issue by kovacsattila-hun** [extesy/hoverzoom#156]
Please add the resized image the resize percent to corner!

Example:
[http://i.imgur.com/rey09rY.png](http://i.imgur.com/rey09rY.png)

It could be useful!

**Comment by irvinm** [comment]
I would like to add to this request.  A feature I had asked for with "Thumbnail Zoom Plus" (Firefox) was to display both the dimensions of the image and the percent resized.

Here is what the result looks like.  It is very useful when you don't have the dimensions displayed already like here on Google Images.

![zoom](https://user-images.githubusercontent.com/979729/29006298-072a445c-7abb-11e7-9726-80867b0adee8.png)

**Comment by GrosPoulet** [comment]
Hi @kovacsattila-hun, this feature was added by #774
