### ISSUE TITLE
Black border around album image counter numbers

### ISSUE THREAD

**Issue by awoh** [extesy/hoverzoom#163]
When you view an album, is shows which image of the album you are on (i.e. 3/20), but the numbers are just plain white. If the image is plain white or some other combination of very light colors in the top right corner, it becomes impossible or extremely hard to see the numbers. This happens quite often, especially if a user is on reddit, where there are a lot of screenshots of reddit or texting conversations, where the background is mainly white. A black border around the white numbers will allow it to be seen on any background (as seen here http://d22zlbw5ff7yk5.cloudfront.net/images/stash-1-507c8da7ae6f2.png).

Thanks :)

**Comment by Ubimo** [comment]
Simply make the counter numbers YELLOW. Like in Imagus, it's easyer to see the numbers then.
