### ISSUE TITLE
Hoverzoom+ not loading thumbnail images & profile pictures on posts on FB timeline

### ISSUE THREAD

**Issue by kuspie** [extesy/hoverzoom#165]
Added the extension today.  This is what occurs when hovering over the thumbs and profile pics.

![image](https://cloud.githubusercontent.com/assets/23294976/20039862/ede03204-a400-11e6-982f-816e0e7de1a0.jpg)

**Comment by extesy** [comment]
Duplicate of #126

**Comment by kuspie** [comment]
Sorry, did I miss something?  I realize it's a dupe but has it been fixed?  I'm new to gitub, thx.

**Comment by extesy** [comment]
No, it hasn't been fixed yet. There's no need to open two identical issues for the same problem.
