### ISSUE TITLE
HoverZoom seems to be causing insecure content warning on HTTPS pages

### ISSUE THREAD

**Issue by Sushubh** [extesy/hoverzoom#166]
Imgur still would not serve their content over HTTP. And on pages where Imgur albums are embedded, somehow HoverZoom+ is resulting in insecure content warning. I have it configured to preloaded the images which might be causing this. But I have not noticed this behavior before. Not sure if this is a new thing. One example link is this:

https://broadbandforum.co/posts/1111936

**Comment by extesy** [comment]
Duplicate of #84. It's very tricky, see my comment there.
