### ISSUE TITLE
Loading rules of video vs gif is different between plugins

### ISSUE THREAD

**Issue by Markussss** [extesy/hoverzoom#178]
I just wanted to point out that the rules in plugins are not consistent. Especially between gfycat and imgur.

With «Zoom Videos» in options disabled.

- When hovering over an imgur-link:
  - pointing to a gifv/mp4/webm, we get no video.
  - pointing to a gif, we get a gif
- When hovering over a gfycat-link
  - pointing to a mp4/webm/no file extension, we get a gif
  - pinting to a gif, we get a gif

I believe one of these plugins should be updated with the "correct" thing to do, but I'm unsure what is correct as both of these can serve *both* videos and gifs of the same content, depending on what the user (or the addon) asks for.

**Comment by TheMikeyR** [comment]
I have the same issue with imgur
[example](https://i.imgur.com/ExYD0jY.gifv)

**Comment by Michael18751** [comment]
webm links are flat out not working for me

**Comment by extesy** [comment]
> webm links are flat out not working for me

Not helpful without any information on how to reproduce.

**Comment by LiliaDoe** [comment]
Both those links work fine for me on the latest version of HZ+(1.0.221) and Firefox (132.0)
