### ISSUE TITLE
W Open Image in New Window Action Key Broken

### ISSUE THREAD

**Issue by mikey55** [extesy/hoverzoom#199]
I have lost the W action key on my 2015 Pixel on Chrome OS 54 and the latest 55 build Stable Channel, I can still use the T action key to open the image in a new tab...

**Comment by extesy** [comment]
Still works for me. Please check your key bindings in the options.

**Comment by mikey55** [comment]
This is still an issue on my Pixel 2015, I uninstalled Hoverzoom rebooted my Pixel and reinstalled Hoverzoom and it worked for a day, unitl this morning, the W action key is now not working anymore.  I tried changing the action key but none works for opening into a new window, the T action key still functions normally however... not sure, possibly there is an interference with other extensions I have loaded in Chrome...

**Comment by mikey55** [comment]
just turned off Enable Albums Support and the W action key starting to work normally again...

**Comment by mikey55** [comment]
It's intermitent, and now it's no longer working again for me again......
