### ISSUE TITLE
HoverZoom+ window disappears and reappears after slightest cursor movement when viewing streamable links

### ISSUE THREAD

**Issue by TETYYS** [extesy/hoverzoom#205]
Thus starting the video from the beginning..

Also seems to disappear and reappear randomly, without even moving the mouse.

**Comment by extesy** [comment]
@TETYYS Please provide steps to reproduce the problem.

**Comment by TETYYS** [comment]
1. Hover on streamable link, HoverZoom+ plays the video
2. Move your cursor 1px in any direction while maintining focus on link

**Comment by Grantapher** [comment]
+1. Has been happening whenever the zoomed image/vid/gif is underneath the cursor and the cursor moves. It is hard to keep the cursor absolutely still with a mouse.
