### ISSUE TITLE
Shortcut "T" doesn't work as expected

### ISSUE THREAD

**Issue by CaBz** [extesy/hoverzoom#21]
Hey,

Just switched from Hover Zoom to Hover Zoom+ and I've tried it a bit using my usual shortcuts. Unfortunately, the "T" shortcut doesn't work as expected:

**Expected:** Opens a new tab with a correct image url (**http**://i.imgur.com/dskljfsd.png).

**Happened:** Opens a new tab with an incorrect image url (**file**://i.imgur.com/OICCwRD.jpg).

Thanks a lot!

**Comment by AltarBeastiful** [comment]
Same here, when pressing "T" it tried to open:
```
chrome-extension://pccckmaobkjjboncdfnnofkonhgpceea//i.imgur.com/BiSBWcb.jpg
```

**Comment by extesy** [comment]
Fixed locally, will go out with the next release.

**Comment by CaBz** [comment]
Thanks a lot. I just re-added the extension a few minutes ago and I already see you fixing bugs. I guess you took the ownership of this project? Or you started to be active again?

Anyways, good job and keep going!

God bless.

**Comment by extesy** [comment]
I usually don't have much time to fix bugs quickly, but I felt that the amount of issues was too high recently and so I have decided to fix the most annoying bugs.
