### ISSUE TITLE
Blacklist Non-Functional

### ISSUE THREAD

**Issue by Pr0cKz3d** [extesy/hoverzoom#218]
Pretty much exactly what the title says. Despite having a blacklist set up for quite a long time now, about 4 or 5 days ago it just has stopped working entirely. Hoverzoom is active on every website i browse. I have tried clearing and recreating my black list several times to no avail. Disabling hoverzoom entirely and re-enabling it. Restarting chrome completely.

**Comment by extesy** [comment]
@Pr0cKz3d Please provide screenshot of your whitelist settings page and page urls where it doesn't work.

**Comment by Pr0cKz3d** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25299434/22218583/8e10e67c-e175-11e6-88ea-ce5f5be54001.png)

it fails to work on the entire list. it's as if the feature isn't even active.

**Comment by extesy** [comment]
@Pr0cKz3d Can you try removing trailing slashes from urls?

**Comment by Pr0cKz3d** [comment]
that did the trick! working as intended now~
