### ISSUE TITLE
Hover Zoom+ stopped working completely on reddit

### ISSUE THREAD

**Issue by NSueiro** [extesy/hoverzoom#219]
I have the whitelist feature enabled (for quite some time) and reddit is the only website in it. Yesterday the extension stopped working.

Chrome Version 55.0.2883.95 (64-bit)
macOS Sierra version 10.12.2

**Comment by johnsexton** [comment]
I am having the same issue - same versions of macOS and Chrome. Also experiencing it on Windows 10 and Chrome 55.0.2883.87 m (64-bit).

**Comment by extesy** [comment]
@NSueiro @johnsexton Could you please provide your hoverzoom settings on whitelist page? Screenshot would be fine.

**Comment by johnsexton** [comment]
Here you go!
![screenshot](https://cloud.githubusercontent.com/assets/1376945/22218031/3f7042bc-e173-11e6-8586-249e6987dc78.png)

**Comment by NightWanderer** [comment]
I have the exact same problem. Was using HoverZoom+ only for reddit in whitelist mode. A few days ago it stopped working. In fact the whole whitelist/blacklist setting seems to be broken. I tried blacklisting different sites and they still showed zoomed images, and tried whitelisting different sites and they did not show images.

**Comment by ragnarkarlsson** [comment]
Its a mixed content issue I suspect. I'm seeing this in the console on Chrome.

`Mixed Content: The page at 'https://www.reddit.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://imgur.com/5HvRm9g'. This request has been blocked; the content must be served over HTTPS.`

**Comment by neilaja** [comment]
Exact same problem.  Whitelisted reddit, hoverzoom not working.

Win 7 Enterprise, Chrome Version 55.0.2883.87 m (64-bit)

**Comment by jritz611** [comment]
same here

**Comment by extesy** [comment]
Ok, I see what's going on here. Over time a lot of people requested to modify whitelist/blacklist to also apply to actual image urls, not just sites that contain image links. For example they never want to expand links to `imgur.com` no matter what website has this link. That's exactly the change I made a few days.

Now your `reddit.com` in whitelist mode means that only links **to** `reddit.com` are allowed. This is obviously undesired, so let me see how to fix that but satisfy the original requirement as well.

**Comment by extesy** [comment]
Ok, please try if version 1.0.104 works better for you.

**Comment by johnsexton** [comment]
It works! Thanks for the quick response!

**Comment by NSueiro** [comment]
Works like a charm! Thanks for the quick fix!

**Comment by jritz611** [comment]
how to force update?

**Comment by NSueiro** [comment]
Write "chrome://extensions" on the URL field. Then on the upper right corner you'll see a checkbox with the text "Developer mode". Check it and a button that reads "Update extensions" will appear

**Comment by jritz611** [comment]
streamable links do not seem to be working on reddit

**Comment by extesy** [comment]
With streamable it's the same old http over https problem, see #84.

**Comment by jritz611** [comment]
weird, it worked before this latest problem

**Comment by NightWanderer** [comment]
Thank you very much for fixing it so quickly!
