### ISSUE TITLE
Some Youtube links won't play

### ISSUE THREAD

**Issue by TETYYS** [extesy/hoverzoom#224]
For example:
https://www.youtube.com/watch?v=XXX&feature=youtu.be
https://youtu.be/XXX (although I see it there (??) https://github.com/extesy/hoverzoom/blob/master/plugins/youtube_a.js#L78)
https://www.youtube.com/watch?v=XXX&test=test
https://www.youtube.com/attribution_link?a=XXX&u=%2Fwatch%3Fv%3DXXX%26feature%3Dshare

Upon hovering I see a flash of loading circle and then nothing

**Comment by extesy** [comment]
@TETYYS Please also provide specific video examples (not just patterns) and the page urls from where they are linked. Some videos disable inline previews.

**Comment by TETYYS** [comment]
Hmm, seems like it's not an issue with different link forms, for example those two videos in this reddit comment chain won't play: https://www.reddit.com/r/osugame/comments/5quh0n/yaong_keji_feat_nanahira_ange_du_blanc_pur/dd29hk4/

**Comment by extesy** [comment]
@TETYYS Here's the error message: "This+video+contains+content+from+WMG.+It+is+restricted+from+playback+on+certain+sites." So it can't be embedded in the way hoverzoom+ works.

I suspect it's the same problem with all your other videos, so I'm closing the bug for now.

**Comment by TETYYS** [comment]
Can this message be shown in a floating box?

**Comment by extesy** [comment]
Theoretically yes, but it's complicated to implement. Different sites return errors in different ways for different reasons.
