### ISSUE TITLE
Improper scaling of photos on Instagram

### ISSUE THREAD

**Issue by tropicoo** [extesy/hoverzoom#225]
This bug is quiet old. Just go to [http://instagram.com](http://instagram.com), search for any tag e.g. #shibainu and hover over photos and videos. Many of them are improperly scaled. Also they're continuously hiding/appearing.
Video: [https://gfycat.com/ColorlessFreshAtlanticridleyturtle](https://gfycat.com/ColorlessFreshAtlanticridleyturtle)
Reproducible on Chrome 56 Release, Windows 10 / macOS Sierra 10.12.3 with latest build of Hover Zoom+

**Comment by extesy** [comment]
I've just tried that, using the same search and got the same photos back. But I can't reproduce he problem - all photos are zooming correctly for me. Do you have any chrome plugins that might conflict with hoverzoom?

**Comment by tropicoo** [comment]
I've tried on macOS in Incognito mode with disabled all Chrome addons and issue somehow is still present [http://i.imgur.com/vHAVHNu.png](http://i.imgur.com/vHAVHNu.png)

**Comment by tropicoo** [comment]
I've just noticed that image is scaled and stretched regarding Instagram post description length.

**Comment by eqagunn** [comment]
Came here to report the same bug. It's been like this for a long time.
Some images get stretched horizontally while others preserve the aspect ratio.

**Comment by extesy** [comment]
Something to do with the captions. You can temporarily disable captions in the extension options until this bug is fixed.
