### ISSUE TITLE
Facebook images not working but linked images do

### ISSUE THREAD

**Issue by ivanoleo** [extesy/hoverzoom#229]
Images that are uploaded to FB do not zoom. There is a flash of a rotating cursor, then nothing. But images that are within links (such as news articles with a photo) work just fine.

**Comment by extesy** [comment]
Duplicate of #141.

**Comment by ivanoleo** [comment]
So this is now closed, but is there a fix for it?

**Comment by extesy** [comment]
No, you should follow existing ticket #141 instead.
