### ISSUE TITLE
Getting null errors for dribbble.com

### ISSUE THREAD

**Issue by doppl3r** [extesy/hoverzoom#23]
```sh
Uncaught TypeError: Cannot set property 'hoverZoomSrc' of null
```

The hover-zoom works until you click the 'Load More...' button. Perhaps dynamically loading more photos is causing the null?

[dribbble.com](https://dribbble.com/shots)

**Comment by extesy** [comment]
Fixed locally, will go out with the next release.

**Comment by doppl3r** [comment]
Awesome work @extesy! I look forward to seeing the update c:
