### ISSUE TITLE
"ambient light behind images" It leads to braking of GIF

### ISSUE THREAD

**Issue by Artlant** [extesy/hoverzoom#232]
add <Disable> option to "ambient light behind images"  when open (hover) image if a gif

'Ambient light behind images' resulting in uneven playback gif animation. But static image all ok

**Comment by extesy** [comment]
@Artlant That just means your hardware can't handle changing the background glow in realtime. You'll have to either disable this feature or use more powerful hardware.

**Comment by Artlant** [comment]
@extesy extesy 
 Yes I made a mistake, sorry! The reason was not the script (has it works only after full image download and glow does not change when it starts). But this Issue is not helpful would be useless. There was a conflict with this extension on google images tab (imghp). You may want to implement check (notification) for injection the work of the script or its inability to perform on the site. This deletion some complaints chome store on ' allegedly ' not work' script on some sites.  For example, I had some work to change this extension https://chrome.google.com/webstore/detail/remove-google-redirection/dnhjklgpiifbofihffldllbcopkinlod
