### ISSUE TITLE
Feature Request: Scroll to cycle images in gallery

### ISSUE THREAD

**Issue by realtimecaulk** [extesy/hoverzoom#24]
The original hoverzoom extension supports going through images in an album with the scroll wheel, similar to how HoverZoom+ supports using the arrow keys to cycle through them. Scroll Wheel up/down would be a good addition to the list of hotkeys that can be set to an action.

UPDATE: Enable "use mousewheel to navigate albums" option if it's disabled.

**Comment by cts359** [comment]
This was indeed a great feature of the original, would be appreciated as either a default or an alternate bind in settings.

**Comment by AndrewRoks1998** [comment]
I second (third? lol) this notion, I always used the scroll wheel for albums in the old Hover Zoom. In my opinion this is a must-have.

**Comment by extesy** [comment]
I've just tried on reddit.com with imgur galleries and using mouse scroll wheel works fine for me. Can you provide any specific examples where it doesn't work?

**Comment by AndrewRoks1998** [comment]
I've also tried on reddit.com with imgur galleries, and on imgur.com itself, and on tumblr.com, and it simply isn't working. When I use the scroll wheel, it just scrolls the page instead of going through the images in the album.

**Comment by ntravis** [comment]
@extesy example of a page here:
https://www.reddit.com/r/skyrim/comments/3u4m34/aela_the_huntress_by_april_gloria/

that fails to scroll with mouse up/down, but works with the keyboard defaults (right-left)

**Comment by extesy** [comment]
@ntravis Surprisingly it works for me on that page. Do you have "use mousewheel to navigate albums" enabled in options? What kind of OS and type of mouse do you have? Do you use non-default mouse drivers (provided by manufacturer, not OS)?

**Comment by joshuaferrara** [comment]
I too am having the same issue, but I'm not seeing the "use mousewheel to navigate albums"  option within the settings. Might be an old version on the Chrome Store, or I'm blind haha.

![image](https://cloud.githubusercontent.com/assets/248680/11389163/3f788c22-92f2-11e5-80fd-a8dacf44e84e.png)
![image](https://cloud.githubusercontent.com/assets/248680/11389168/4c9995f4-92f2-11e5-999a-d9e2968ded2f.png)
![image](https://cloud.githubusercontent.com/assets/248680/11389176/73b88c12-92f2-11e5-85d6-409ba2360bb1.png)

**Comment by extesy** [comment]
@joshuaferrara There was a small issue in version 1.0.19 which is now fixed. Please try 1.0.20 and let me know if it works for you.

**Comment by joshuaferrara** [comment]
Works like a charm! :+1:

**Comment by extesy** [comment]
Great! Thanks for confirming. I'm closing this bug then.

**Comment by ntravis** [comment]
Thanks @extesy , working great for me!
