### ISSUE TITLE
Hoverzooming image sets 'title' attribute of all links to null

### ISSUE THREAD

**Issue by Eegras** [extesy/hoverzoom#249]
Reddit doesn't give us much in the way of being able to stick images in our sidebar, so we get that functionality by making a link like `[](https://foo.bar "fizzbuzz")` and styling links with the title of fizzbuzz.  HoverZoom, when hover-zooming, sets apparently all link titles to null which causes the page to jump around.

You can see it in the sidebar here: https://www.reddit.com/r/pcmasterrace/new/

**Comment by Eegras** [comment]
Fixed in #250

**Comment by extesy** [comment]
PR merged. Thanks for the fix!

**Comment by Chiller252** [comment]
Lol this caused issue #252

**Comment by Eegras** [comment]
Uhh, strange. I'll take a look at it when I get home.
