### ISSUE TITLE
Request: Support for Bing Images

### ISSUE THREAD

**Issue by AndrewRoks1998** [extesy/hoverzoom#25]
Hello, would it be possible to add support for [Bing Images](http://www.bing.com/images)? That'd be great to have in Hover Zoom+. Thanks for making/fixing this neat extension!

**Comment by extesy** [comment]
Fixed locally, will go out with the next release.

**Comment by AndrewRoks1998** [comment]
Thanks a lot man, the lack of Bing support was the only problem I had with the old Hover Zoom (not counting the spyware, lol)

**Comment by AndrewRoks1998** [comment]
I see that you changed some of the code in bing.js, however, hovering over the thumbnails on Bing Images results pages (i.e., http://www.bing.com/images/search?q=example ) does not activate Hover Zoom+. I am using version 1.0.20.

**Comment by extesy** [comment]
I've tested it on this page - https://www.bing.com/images - and it worked. Looks like I need to test on a search page separately.

**Comment by AndrewRoks1998** [comment]
It seems to be working perfectly now, thank you :+1:
