### ISSUE TITLE
Alt/Title text obscuring image

### ISSUE THREAD

**Issue by Chiller252** [extesy/hoverzoom#252]
With a recent update (probably March 21, 2017) images with alt text or title attributes in the image element will cause the popup to be layered in front of the hover-zoomed image. This results in the image being obscured by the popup. 

With some research, it appears that there is no way to disable alt text/ titles in Google Chrome. There also appears to be no way to disable alt text/ titles in the options for the extension.

Example image: http://imgur.com/a/nATt7

Perhaps creating a quick toggle in the settings that enables/ disables displaying the alt would be a quick solution.

**Comment by extesy** [comment]
@Chiller252 Please also post a link where this bug can be reproduced.

**Comment by Chiller252** [comment]
Are you sure you really want that...?

**Comment by Chiller252** [comment]
Perhaps a toggle can be added to the settings that reverts the changes made in #249 / #250.
Also I find this particular issue number quite appropriate.

**Comment by Chiller252** [comment]
Just letting everyone know that I've seen lots of people switching away from HoverZoom+ due to this issue. "Switch to Imagus. Same basic behaviour, captions do show at top of image but not in a particularly problematic way IMO (single-line-high bar of text at top of image, extending to the right indefinitely)"
