### ISSUE TITLE
Hide mouse on zoom

### ISSUE THREAD

**Issue by chrisbeamond** [extesy/hoverzoom#254]
I love the extension! One slight annoyance is the mouse showing when an image is zoomed. Please add an option where the mouse is hidden when over a zoomed image?

**Comment by jonluca** [comment]
This should be pretty easy with just a css change of cursor-style: none when hovered. I can try to take a look at it later

**Comment by krnets** [comment]
Any progress on this enhancement? 
Would really like this to automatically hide when image is viewed - similar to how it works for Firefox extension Imagus.

**Comment by GrosPoulet** [comment]
Hello @krnets 
#785 introduces a new option:
![Capture](https://user-images.githubusercontent.com/23529041/131245723-a2334d0d-f903-4f89-a593-53f3c07b8a79.JPG)
It'll be available in next HZ+ release (1.0.181).
Important: by default, this option is **disabled**, so you'll have to enable it in: **Options -> General -> Delays**

**Comment by LiliaDoe** [comment]
This issue can probably be closed
