### ISSUE TITLE
plugin not working on pinterest

### ISSUE THREAD

**Issue by SeldenK** [extesy/hoverzoom#258]
Rollover doesn't induce zoom on pinterest.com!

**Comment by extesy** [comment]
@SeldenK It works fine for me. Please make sure you are using hoverzoom+ and not hoverzoom.

**Comment by SeldenK** [comment]
Definitely using HoverZoom+. I tried to capture the error [here](https://youtu.be/rc6vl3tnzwU) w/a comparison of the plugin working fine on another site; sorry that it's a pretty shoddy recording attempt!

**Comment by reverberating101** [comment]
Doesn't work for me either and yes I'm using HoverZoom +

**Comment by extesy** [comment]
@SeldenK @reverberating101 Which version are you using? What is the link on pinterest that you are using?

**Comment by reverberating101** [comment]
> Hover Zoom+ 1.0.115 
Just Pinterests main page - it usually works on images after I’ve clicked on them (which of course defeats the purpose of the extension)

**Comment by extesy** [comment]
Are you using Chromebook by any chance?

**Comment by reverberating101** [comment]
No -  Version 57.0.2987.133 (64-bit) of Chrome browser on a MacBook Pro

**Comment by SeldenK** [comment]
Using Version 1.0.115; I just uninstalled and reinstalled before starting this thread. I am also just using Pinterest's main feed, not using a Chromebook, and have Version 57.0.2987.133 (64-bit) of Chrome.

**Comment by SeldenK** [comment]
Something I just realized: if I search for something on Pinterest, the extension works fine on the search results page. It does not seem to work on pages for specific boards, however.
