### ISSUE TITLE
Settings aren't saved in Chrome 46.0.2490.86

### ISSUE THREAD

**Issue by tropicoo** [extesy/hoverzoom#26]
Any extension's setting isn't saved in Chrome 46.0.2490.86 m (64-bit) / Windows 10 v1511 10586.14 x64 ENG.
Reloading page shows previous values.
Video: http://i.imgur.com/barQu1A.gifv

**Comment by mrsln** [comment]
I've encountered the same problem. It says [Cannot read property 'checked' of undefined – options.js:117]
(https://github.com/extesy/hoverzoom/blob/master/js/options.js#L117).

**Comment by tropicoo** [comment]
Screenshot from console
http://i.imgur.com/MVvlh75.png

**Comment by mrsln** [comment]
you can go to the line that causes the error in the console (click on options.js:117), comment it out, save it (ctrl+s) and it try to it again ;)

**Comment by mrsln** [comment]
I made PR – https://github.com/extesy/hoverzoom/pull/27 :laughing:

**Comment by tropicoo** [comment]
Nice workaround, thanks.

**Comment by mrsln** [comment]
you are welcome! Glad I helped :smile:

**Comment by extesy** [comment]
Thanks, @mrsln. I've uploaded a new build with your fix.
