### ISSUE TITLE
OS X crashes when HoverZooming on Facebook (just lately)

### ISSUE THREAD

**Issue by raulrene** [extesy/hoverzoom#261]
## Description of the problem
I've encountered this just lately, been using Hover Zoom for a long time without any problems. I only encountered it on Facebook. It happens only sometimes but it's come to happen at least once a day now (even when I'm not scrolled deep on Facebook).

At times if I'm lucky it just freezes for a split seconds and recovers. Other times it freezes forever and I need to reboot. Nothing responds, not even keyboard controls for light/sounds etc.

I've encountered this in the past week or so and if I remember correctly the extension got updated somewhere around last week, so I guess something in the new version? Can I downgrade in a way?
I currently disabled Facebook plugin and I'm not having the problem anymore, but it would be great to find a solution.

## Steps to reproduce the problem (include image url here)
Can't really add more to what it's in the description because the laptop freezes (sometimes it just re-starts, sometimes it stays frozen until I force reboot)

## OS version, extension version
OSX Sierra 10.12.4, Version 1.0.117 

Thanks in advance!

**Comment by extesy** [comment]
I'm sorry to disappoint, but this is not an extension issue. This is a hardware issue with your laptop. Chrome extension is just a few JavaScript files executed on every page. If it causes any hardware issues then you should repair/replace your hardware. Facebook it probably just triggering something related to your video driver or video card.
