### ISSUE TITLE
Suggestion: adjust frame background color

### ISSUE THREAD

**Issue by baz357** [extesy/hoverzoom#262]
Hi,

I have a suggestion, not sure if it's even technically possible.

The problem:
When you use HoverZoom+ on a mostly black website, and it's not loading an image right away, then it 'flashes' the white frame background for a short period of time (<1s) before loading the image. The effect is less in-your-face on lighter sites.

The solution:
This could be fixed by either
- calculating the average color value of the page Chrome is currently displaying and using that to set the frame background color accordingly
or by
- allowing the user to manually set the frame background color

I'm using Windows 10, latest Chrome and HoverZoom+ version.

**Comment by ajlomagno** [comment]
I'm going to give this one a go and see what I can come up with.
