### ISSUE TITLE
Comment zoomer une image sans qu'elle ne sorte du cadre ? How to zoom an image without it leaving the frame?

### ISSUE THREAD

**Issue by HerbDan** [extesy/hoverzoom#263]
Bonjour,
Actuellement, lorsque je survole une image, elle est bien agrandie, mais je ne peux voir qu'environ la moitié car elle sort de mon écran. 
J'aimerais qu'elle se positionne en plein écran, quel que soit la position de mon curseur. 
Merci d'avance, 
Daniel

**Comment by extesy** [comment]
@HerbDan I don't speak French, please write in English.

**Comment by HerbDan** [comment]
Hello,
(Translated by Google Translate)
Currently, when I fly over an image, it is enlarged, but I can only see about half as it comes out of my screen.
I would like it to be positioned full screen, regardless of the position of my cursor.
Thank you in advance,
Daniel

**Comment by extesy** [comment]
@HerbDan You can enable "center images" option so that they won't follow your cursor anymore.

**Comment by HerbDan** [comment]
@extesy I have respected your instructions; I attached screenshots
![image with over zoom](https://cloud.githubusercontent.com/assets/28704189/26070880/81974376-39a6-11e7-8da0-bd3d0a963362.jpg)
![image without over zoom](https://cloud.githubusercontent.com/assets/28704189/26070886/893d357c-39a6-11e7-868f-f0e6ea39e337.jpg)
![options over zoom](https://cloud.githubusercontent.com/assets/28704189/26070890/8cc2ad62-39a6-11e7-908e-eff95c2161d6.jpg)

**Comment by extesy** [comment]
Does this happen only on facebook or other sites as well?

**Comment by HerbDan** [comment]
@extesy No, it's on all sites
