### ISSUE TITLE
Scrolling through albums with mouse wheel doesn't work

### ISSUE THREAD

**Issue by BubiBalboa** [extesy/hoverzoom#264]
Scrolling through albums with mouse wheel doesn't work on Reddit. Scrolling scrolls the page not the album. Mouse wheel left and right navigate the album. Checking or uncheckig the mouse wheel option has no effect.

## Url of the page where the problem occurs (not the image url)
reddit.com
https://www.reddit.com/r/DIY/comments/6baxr1/i_built_a_super_beefy_industrial_steel_frame/

## Steps to reproduce the problem (include image url here: https://imgur.com/gallery/trl4x)
1. hover over album on Reddit
2. scroll
3. page scrolls, album doesn't

## OS version, extension version
Win 10 (latest updates) , FF 53.0.2 (64bit), HoverZoom+ 1.0.88

**Comment by extesy** [comment]
@BubiBalboa update to the latest hoverzoom+ version - 1.0.117

**Comment by BubiBalboa** [comment]
This is the latest version on AMO. And there is no beta channel. How do I update?

**Comment by extesy** [comment]
@BubiBalboa You were not using HoverZoom+. You were using HoverZoom. You can install HoverZoom+ from https://chrome.google.com/webstore/detail/hover-zoom%20/pccckmaobkjjboncdfnnofkonhgpceea

**Comment by BubiBalboa** [comment]
No, you missunderstand :) I'm on Firefox. And I'm using HoverZoom+. It even links to this repo on the settings page. 
![unbenannt](https://cloud.githubusercontent.com/assets/8809532/26122169/deff2eea-3a76-11e7-8918-83fc971ad370.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/8809532/26122171/e15d08c4-3a76-11e7-90c4-3bee3934fbbd.PNG)

**Comment by extesy** [comment]
Sorry I missed that it is for Firefox. Yes, it's not my addon, somebody took it and ported to Firefox. Please contact the submitter of that extension, it has nothing to do with me or this repo.

**Comment by BubiBalboa** [comment]
Okay. If you were interested in officially porting your addon to Firefox, I'm sure a lot of people would be happy. It should be pretty easy too since Firefox uses Chrome addon API now. Maybe something to consider. :) Thanks for your work, either way.
