### ISSUE TITLE
После нажатия на S для загрузки , вместо диалога download

### ISSUE THREAD

**Issue by Litvinr** [extesy/hoverzoom#265]
## Description of the problem
После нажатия на S для загрузки картинки , вместо диалога download картинка открывается в вкладке
Версия для chrome не имеет такого бага

## Url of the page where the problem occurs (not the image url)
Любое изображение на всем сайте https://www.youtube.com

## Steps to reproduce the problem (include image url here)
1. Наведи курсор мыши на изображение  
2. Дождись открытия окна hover с картинкой и нажми на S 
3. Вместо загрузки в папку download или диалога download изображение открывается в тойже вкладке вместо сайта. 

## OS version, extension version
Windows7 64bit
Cyberfox x64 (aka Firefox) Mozilla 52

**Comment by extesy** [comment]
This repo has nothing to do with Firefox extension, please contact that extension author.
