### ISSUE TITLE
Not working with Pinterest (again)

### ISSUE THREAD

**Issue by reverberating101** [extesy/hoverzoom#271]
## Firefox?
Is your question about Firefox addon? Please don't create an issue here and contact https://twitter.com/wallacesilva09 instead. This repository has nothing to do with Firefox addon.

## Steps to reproduce the problem (include image url here)
1.
2.
3.

**Comment by reverberating101** [comment]
It is not currently working.Hasn't for the last several days. 

    On Tuesday, July 11, 2017 8:06 PM, Oleg Anashkin <notifications@github.com> wrote:
 

 Closed #271.—

**Comment by extesy** [comment]
@reverberating101 The bug template exists for a reason. What you see on your screen is not what I see on my screen. I can't read minds so I will not consider any improperly filled bug reports.
