### ISSUE TITLE
Pnterest

### ISSUE THREAD

**Issue by Gelu66** [extesy/hoverzoom#272]
Hello,

Description of the problem
The plugin don't working for https://www.pinterest.fr since some days.
I need to click on a picture then the home page for the plugin to work, before this step was not necessary.

Url of the page where the problem occurs (not the image url)
https://www.pinterest.fr

Steps to reproduce the problem (include image url here)
Just go on pinterest french version website

OS version, extension version
Windows 10 (1703)
Hover Zoom+ 1.0.123

Do you have a solution ?

**Comment by reverberating101** [comment]
Hasn't worked on Pinterest for days  - Chrome 59.0.3071.115 (Official Build) (64-bit) - macOS Sierra 10.12.5

**Comment by Gelu66** [comment]
Has not worked for months :(
