### ISSUE TITLE
Update jquery

### ISSUE THREAD

**Issue by Mte90** [extesy/hoverzoom#276]
## Description of the problem
The extension use an old version of jQuery and in the console there are different report for using old api.

**Comment by Mte90** [comment]
I tried updating to jquery 3.2.1 but I got $ is not defined but I am not sure about the order of loading the files

**Comment by Mte90** [comment]
Ref #277

**Comment by extesy** [comment]
Fixed by #277

**Comment by extesy** [comment]
Thanks for the contribution!
