### ISSUE TITLE
Images hosted on i.reddit.com not added to history if they are embedded through non-direct link

### ISSUE THREAD

**Issue by ragnarkarlsson** [extesy/hoverzoom#283]
## Description of the problem
When viewing images on https://www.reddit.com/ those which are hosted on the subdomain i.reddit.com but the submitted link is not direct (ie is the featured image of a thread) they are not added to browser history. Yesterday's patch is installed and I'm seeing all imgur links update browser history.

All combos of settings, whitelisting and restarting the browser do not resolve the issue.

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/r/all

## Steps to reproduce the problem (include image url here)
1. Visit Reddit https://www.reddit.com/r/all
2. Hover over a link to a picture hosted on subdomain i.reddit.com eg https://www.reddit.com/r/aww/comments/6r173k/this_little_guy_waiting_for_his_new_family_to/
3. ???
4. Image displayed, browser history not updated

## OS version, extension version
Win10 (fully patched)
Chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by extesy** [comment]
@ragnarkarlsson Are you sure you are using version `1.0.121` and your option (in "advanced" options tab) is enabled? Because I've just tried to reproduce this and the link does get added to history.

**Comment by ahoibakk** [comment]
I'm having the same issue as @ragnarkarlsson, but it's i.redd.it, not i.reddit.com. It's working for other sites like i.imgur.com though.
Video here: https://img.m42.no/be54b355-45ce-4c8c-917a-e9a5960ee280.mp4
Perhaps it's related to some link trickery reddit is using? HoverZoom is able to magnify the image, but the link is actually to the post, not the image..?

**Comment by ragnarkarlsson** [comment]
Can confirm that I am using 1.0.121 and that the tickbox for _Add viewed pictures to the browser's history_ is enabled.

![image](https://user-images.githubusercontent.com/3290527/28894225-0ede9abe-77cc-11e7-9736-992c41f3017e.png)

Also @ahoibakk has correctly pointed out that it is indeed i.redd.it domain and not i.reddit.com

I'm fairly confident that this was working previously, but couldn't give you anything definitive in terms of timeframe I'm afraid.

**Comment by extesy** [comment]
Hm... I used https://www.reddit.com/domain/i.redd.it/ list and all links were adding into history for me just fine. Maybe some other options and/or plugins interfere with it?

**Comment by ragnarkarlsson** [comment]
I've just tried that URL, result is still the same:

![image](https://user-images.githubusercontent.com/3290527/28896604-0844b93c-77d5-11e7-9a44-9ad1c6878034.png)

Tried going into hoverzoom+ settings and disabling every plugin (please, please, put in a select/deselect all option) except for Reddit. No impact.

Disabling whitelist mode didn't help, hover zoom+ is the only extension running in Chrome atm as well to try and eliminate anything else.

What else can I test?

**Comment by extesy** [comment]
Do you have any relevant errors in the console ("more tools" -> "developer tools")?

**Comment by ragnarkarlsson** [comment]
With only HZ+ enabled I don't get any on hover, but there are some on page load
![image](https://user-images.githubusercontent.com/3290527/28897550-2c74d0a4-77d9-11e7-8437-338d5a4eff49.png)
Each of those references hoverzoom.js as far as I can see when expanded.

**Comment by extesy** [comment]
These are benign warnings, not errors. I'll try to somehow reproduce the problem on another machine.

**Comment by denaje** [comment]
I'm having the same issue.

HoverZoom+ version 1.0.121
Chrome Version 60.0.3112.78 (Official Build) (64-bit)

No console errors. If there's anything I can do to help reproduce, let me know.

**Comment by pbo10** [comment]
Same issue here, the latest update fixed all the other links but the i.redd.it images are still not added to my browser history.

**Comment by tropicoo** [comment]
Same issue. 

Windows 10 x64
Chrome 60.0.3112.90 Official 64-bit
HoverZoom+ 1.0.121

No errors in console.

**Comment by ahoibakk** [comment]
I thought perhaps it had something to do with our user (and/or Reddit Gold), but I tried using it logged out with no difference.

**Comment by extesy** [comment]
Ah, I see. Do any of you have "reddit enhancement suite" installed? Because for me the url on this link is a link to the image, not the post.

**Comment by denaje** [comment]
I do have RES installed. Every link on https://www.reddit.com/domain/i.redd.it/ is a link to the post (e.g. if I click on the link, it takes me to the comments section). The image zooms properly while hovering, it just doesn't color the link purple afterwards.

**Comment by ahoibakk** [comment]
No, I do not have RES installed.

On 5 Aug 2017, at 15:09, Jesse Denardo <notifications@github.com<mailto:notifications@github.com>> wrote:


I do have RES installed. Every link on https://www.reddit.com/domain/i.redd.it/ is a link to the post (e.g. if I click on the link, it takes me to the comments section). The image zooms properly while hovering, it just doesn't color the link purple afterwards.

**Comment by ragnarkarlsson** [comment]
I have RES installed, but I just tried disabling it and logging out to be sure it wasn't even account related. Issue persisted.

**Comment by denaje** [comment]
@extesy It looks like your commit fixed the problem for me! Thanks a bunch!
