### ISSUE TITLE
"Open image in a new window..." no longer works on small images

### ISSUE THREAD

**Issue by EviLFazZ** [extesy/hoverzoom#284]
> "Open image in a new window" (default key is 'W')
> "Press this key to open the image you are currently viewing in a new window. Press this key again to close the window" no longer works on small images, but does on images larger than my browser window"

1. Hoverzoom over an image that opens smaller than your current browsers windows size
2. Press 'W' (the default key) to open in a new window
3. Nothing (but 'S' for example works for saving images etc)

_**Windows 10 x64** using **Chrome 60.0.3112.78**_

**Comment by extesy** [comment]
@EviLFazZ Works for me. Please use the original bug template if you want your issue to be fixed.

**Comment by EviLFazZ** [comment]
Thanks for letting me know @extesy, _at least I knew it was just me,_ so forced a quick manual update of my **Chrome** installation and works again (now using 60.0.3112.90 ...which did not want to update too) ...anywho, thanks again and keep up the awesome work 😄
