### ISSUE TITLE
"Add viewed pictures to the browser's history" not working

### ISSUE THREAD

**Issue by nagelsax** [extesy/hoverzoom#287]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Can't check the box in settings

## OS version, extension version
Windows 10, Firefox Nightly 57, Version 1.0.88

**Comment by extesy** [comment]
@nagelsax you have to say "allow" to the dialog that Chrome shows you after you attempt to check the checkbox.

**Comment by nagelsax** [comment]
I don't get a dialog popup when I try to check the box. And in on Firefox.

**Comment by extesy** [comment]
@nagelsax Please contact the author of the Firefox extension for the support.
