### ISSUE TITLE
Doesn't work when cookies are disabled globally.

### ISSUE THREAD

**Issue by mathew832** [extesy/hoverzoom#288]
The same thing happens with Stylus addon but I was told it's a Firefox bug. I reported it on bugzilla and was told to isolate the problematic code which, as a non-programmer, might not be feasible at the moment though I'll investigate.

URL of affecting pages: * (everywhere)

Steps to reproduce the problem:
1. Disable cookies in FF options

Steps to fix the problem:
About:debugging, open manifest.json url and allow cookies specifically for the extension

OS version, extension version:

Windows 10, ext version 1.0.88

**Comment by extesy** [comment]
@mathew832 What extension are you talking about? There is no officially published Firefox version of it yet. If you are asking about https://addons.mozilla.org/en-US/firefox/addon/hover-zoom/ then please contact its author.

**Comment by mathew832** [comment]
Oops, thought I was using yours. But I did try yours for a while. I'd suspect you may have the same issues as a few other addons have this problem of relying on global cookies to function.
