### ISSUE TITLE
Firefox: Cannot be installed because addon is corrupted

### ISSUE THREAD

**Issue by vurtomatic** [extesy/hoverzoom#290]
## Description of the problem
Firefox can't install the addon because it's corrupted.

## Url of the page where the problem occurs (not the image url)
https://addons.mozilla.org/en-US/firefox/addon/hover-zoom-plus/

## Steps to reproduce the problem (include image url here)
1. Click on "Add to Firefox"
2. Firefox will download the addon
3. Cannot install, corruption error

## OS version, extension version
Firefox Nightly 57.0a1 (2017-08-16) (64-bit), MacOS, extension Version 1.0.121

**Comment by extesy** [comment]
> This add-on has not been reviewed by Mozilla.

@vurtomatic Don't install it yet, it's been just submitted and is not guaranteed to work.
