### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by JorgeWFelix22** [extesy/hoverzoom#292]
#As imagens de perfil no facebook que ficam no canto da tela não se expandem, ficam somente carregando e carregando, mas nunca abre.
https://www.facebook.com/

**Comment by extesy** [comment]
@JorgeWFelix22 I don't speak your language.

**Comment by ozzyjr** [comment]
It meant that the extension is not currently working with Facebook images.

**Comment by extesy** [comment]
Well, that's not helpful because it does work for me. The original bug submission template has several questions for a reason. I don't have a crystal ball to read minds.
