### ISSUE TITLE
Feature request: Add maximum zoom mode with scroll to zoom

### ISSUE THREAD

**Issue by ghost** [extesy/hoverzoom#295]
## Description of the problem

Long images fit their whole length to the page and have to be opened separately in order to view.

## Url of the page where the problem occurs (not the image url)

Many examples over at [/r/polandball](https://www.reddit.com/r/polandball/)

## Steps to reproduce the problem (include image url here)

1. Go to https://www.reddit.com/r/polandball/
2. Hover over an image
3. Full image is always displayed

## OS version, extension version

Kubuntu 16.04, 

# Proposition

Do it like [imagus](https://addons.mozilla.org/fr/firefox/addon/imagus/?src=userprofile):

 - right click or "Z" key activates maximum zoom (fit to screen by width)
 - scroll in "maximum zoom" mode scrolls in or out

[Example](https://streamable.com/5hfga)

[Example mirror](https://gfycat.com/gifs/detail/FabulousFlawlessElectriceel)

**Comment by abjugard** [comment]
This is one of the features I miss most from Imagus.

**Comment by LiliaDoe** [comment]
I think #1442 addresses this. If not, there could be an option to make locking the image a held action instead of a toggle.

**Comment by LiliaDoe** [comment]
@extesy I think this issue can be closed now. The feature requested is already added with image locking
