### ISSUE TITLE
Does not maintain changes made to settings

### ISSUE THREAD

**Issue by RWeOurselves99** [extesy/hoverzoom#296]
Does not maintain changes made to settings 

moz-extension://a06c869e-1a5c-4275-983c-f6abf08e1610/html/options.html

1. Go to HoverZoom+ Options
2. Make changes to the default settings
3. Next time you open Firefox Browser the settings have reverted to default

Windows 10

**Comment by extesy** [comment]
@RWeOurselves99 Firefox version does not exist
