### ISSUE TITLE
Bing Images not enlarging on mouseover using Chrome and Windows 7

### ISSUE THREAD

**Issue by jeromymanuel** [extesy/hoverzoom#297]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
- Bing Images will not resize when hovering in chrome (latest build)

## Url of the page where the problem occurs (not the image url)
- http://www.bing.com/images/search?q=Hurricane+Jose

## Steps to reproduce the problem (include image url here)
1. hovered mouse over the following first 3 images of the search, also refreshed page
- http://www.bing.com/images/search?view=detailV2&ccid=CTGNCrSt&id=0C2608F8643A243E0A9D008AD9E22941EA61E573&thid=OIF.D162EI32AlaBESjhB5T0bQ&q=Hurricane+Jose&simid=142923560267&selectedIndex=0
- http://www.bing.com/images/search?view=detailV2&ccid=jGmsMLPb&id=650CBC9549181A30DD122320D0FB73DDB81F4418&thid=OIF.HH2gX2Zq9MhDGJF%2ffZDapA&q=Hurricane+Jose&simid=74163648587&selectedIndex=1
- http://www.bing.com/images/search?view=detailV2&ccid=iM7eypHA&id=E56BB72479CB540911EBB2C5C8C8FA123D26AF4F&thid=OIF.2pqBtWPM8CshSoPK%2bx3k8A&q=Hurricane+Jose&simid=74184148434&selectedIndex=2

## OS version, extension version
- Windows 7 enterprise 64-bit
- Chrome Version 61.0.3163.79 (Official Build) (64-bit)
- Hover Zoom Version 1.0.123

**Comment by GrosPoulet** [comment]
Works fine now
