### ISSUE TITLE
Orphaned plugins not included in manifest

### ISSUE THREAD

**Issue by stil** [extesy/hoverzoom#303]
Following plugins are not included in manifest.json
* `gifbin.js`
* `live.js`
* `mercadolibre_com_ar.js`
* `skyrock_a.js`
* `voxmedia.js`

Should we delete them or add them to manifest.json?

**Comment by extesy** [comment]
I'd say include them. Why delete something that works? I think `skyrock_a.js` should go into the top "<all_urls>" block and the rest into each other separate blocks.

**Comment by extesy** [comment]
By the way, do you want direct push access, @stil? Looks like you are doing a good job so you might as well push to the repo without waiting for me.

**Comment by stil** [comment]
> do you want direct push access

I use this add-on daily, so I can help with fixing some of issues I encounter.

**Comment by extesy** [comment]
Ok, done: https://github.com/extesy/hoverzoom/invitations
