### ISSUE TITLE
Imgflip domain not working

### ISSUE THREAD

**Issue by elynnaie** [extesy/hoverzoom#310]
## Description of the problem

Images hosted on imgflip.com do not load on hover. Note that i.imgflip.com hosted images _do_ work.

## Url of the page where the problem occurs (not the image url)

https://www.reddit.com/domain/imgflip.com/

## Steps to reproduce the problem (include image url here)
1. Go to https://www.reddit.com/domain/imgflip.com/
2. Find an image where the domain is imgflip.com, not i.imgflip.com
3. Hover over said image. Image does not load.
4. Example image url: https://imgflip.com/i/1xltqi

## OS version, extension version

Arch Linux, Google Chrome version 61.0.3163.100, extension version 1.0.123

**Comment by GrosPoulet** [comment]
Hi @elynnaie, this issue was solved by #689
