### ISSUE TITLE
Low visibility on some images with transparent background.

### ISSUE THREAD

**Issue by Explorare** [extesy/hoverzoom#313]
## Description of the problem
Low visibility on some images with transparent background.

## Url of the page where the problem occurs (not the image url)
https://en.wikipedia.org/wiki/Lucida#/media/File:Lucida_Console_sample.svg

## Steps to reproduce the problem (include image url here)
1. The image loooks like this in my browser by default.
![](https://i.imgur.com/W3qy91y.png)
2. It looks like this when the cursor hovered on the image
![](https://i.imgur.com/ZiRBdSN.png)

## OS version, extension version
Windows 10 Enterprise 1607
CentBrowser  2.9.4.39 (Chromium 61.0.3163.100)
HoverZoom+ 1.0.123

**Comment by extesy** [comment]
@Explorare That happens because of image transparency (see that checkered background?). When you hover, entire screen is darkened and then black letters are displayed on top. The image you are trying to zoom does not have a white background. It has no background.

**Comment by Explorare** [comment]
I know it happens because of image transparency. But is it possible to add a white background to the image automatically?

**Comment by extesy** [comment]
@Explorare Then you would have exactly the same problem with images that use white letters on a transparent background.

**Comment by Explorare** [comment]
You are right, lol.
