### ISSUE TITLE
Save option not working

### ISSUE THREAD

**Issue by sudanking** [extesy/hoverzoom#314]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Save Option with shortcut (S) not open save dialog bo

## Steps to reproduce the problem (include image url here)
1. Hover over pic
2.shortcut (S)
3.open picture in same tap

## OS version, extension version
Windows 10, FireFox57.0(64) , Ext Ver1.0.125

**Comment by extesy** [comment]
Please report Firefox extension issues to its author. This repository is for Chrome extension only.
