### ISSUE TITLE
"Add viewed pictures to the browser's history" not working in Firefox Quantum

### ISSUE THREAD

**Issue by rappo** [extesy/hoverzoom#317]
## Description of the problem

When trying to enable the Advanced option "Add viewed pictures to the browser's history" in Firefox Quantum (57.0), the option cannot be enabled. The checkbox quickly flickers the first attempt to enable, with no reaction after that. That behavior can be repeated by reloading/revisiting the page. 

## Url of the page where the problem occurs (not the image url)

Advanced tab of Hover Zooom+ Options (/html/options.html)

## Steps to reproduce the problem (include image url here)
1. Click Options from about:addons
2. Click Advanced tab
3. Attempt to check the box next to "Add viewed pictures to the browser's history"

## OS version, extension version

Windows 10 Pro
Firefox Quantum (57.0)
HoverZoom+ Version 1.0.88

**Comment by extesy** [comment]
This repo is not for Firefox extension

**Comment by rappo** [comment]
The Firefox extension links directly to this repo, btw. Is there Firefox extension an unofficial or unsupported port?

**Comment by extesy** [comment]
Somebody took this source code and republished for Firebox without changing backlinks. I'm not responsible for it.
