### ISSUE TITLE
Doesn't work on Facebook after most recent update

### ISSUE THREAD

**Issue by euronate** [extesy/hoverzoom#32]
This extension works fine on other websites (reddit, Twitter, imgur, etc), but it hardly works at all on Facebook after the most recent update.  It doesn't even look like it's trying to work either (no little white box beside your cursor when you hover over a picture).

**Comment by DaveTheDrummer** [comment]
Same issue. Not working at all on Facebook. Seems OK on other sites. Although it's never worked with links and previews to Imgur.

**Comment by extesy** [comment]
Facebook changed their site design. There are no extensions in the Chrome webstore now which support it. I've tried updating the plugin, but Facebook uses a very heavy AJAX and I couldn't figure out how to extract the full picture url.

**Comment by DaveTheDrummer** [comment]
Hi Oleg,

 

No worries. Thanks for responding.

Facebook are a real pain in the arse doing things like this. They seem to be on a mission to kill anything that makes the user experience of their site more flexible.

Do you have a donate button I can press?

 

Thanks,

 

Dave

**Comment by extesy** [comment]
I've pushed a quick fix which should help in some cases. Please confirm if it works for you.

@DaveTheDrummer Thank you for the offer, Dave, but I don't seek donations and prefer pull requests instead. Or at least a good word and some help with recommending this extension to other people.

**Comment by DaveTheDrummer** [comment]
No worries, you're very welcome. Thank you for your efforts, it's much appreciated. I'll spread the word.

**Comment by Misiek304** [comment]
Thank you for your work. 
Hope you will be able to figure out it soon.

**Comment by euronate** [comment]
Thanks for the response and I figured it was a Facebook change that broke it.  That's exactly why I don't post 1 star reviews saying your extension is broken when it works just fine everywhere else.  Hopefully you'll be able to find a fix soon.  I'll keep checking back here for updates, but I haven't noticed any improvements during the last 24 hours.  Thanks for the support!

**Comment by extesy** [comment]
Latest update (1.0.37) works pretty well on my facebook feed. Please check it out. There might be some edge cases left, but most of photos expand correctly now.

**Comment by DaveTheDrummer** [comment]
Working perfectly for me :-)
Thank you for making my life a little easier.

**Comment by frogbong1** [comment]
can you disable it on the FB notifications drop down menu?

**Comment by extesy** [comment]
@frogbong1 should be fixed in 1.0.45

**Comment by frogbong1** [comment]
Thanks! I love this app
