### ISSUE TITLE
Mouse scroll on Firefox not working

### ISSUE THREAD

**Issue by marcusboon** [extesy/hoverzoom#320]
## Description of the problem
It seems like imgur albums on reddit especially have broken mouse scroll. The left and right buttons work fine for going through the albums.

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/r/Amd/comments/7g6fne/finaly_built_myself_a_custom_loop_for_my_vega_56/

## Steps to reproduce the problem (include image url here)
1. Go to the AMD subreddit
2. Pick a link that contains an imgur album e.g. the one above which links to https://imgur.com/a/4P9GD
3. Hover over the title

Expected:
The image zooms to the original size and you can use the scroll wheel of the mouse to move between images in the album

Actual:
The image zooms to the original size but the scroll wheel of the mouse just scrolls the page

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 Pro, Unofficial 1.0.125, Firefox (now I know this is technically not supported yet but once it is published in the Mozilla extensions then I think this bug will still be there)

**Comment by extesy** [comment]
Firefox is not supported.

**Comment by extesy** [comment]
When I publish it to Firefox officially, I will test all features to make sure everything works. Until then, firefox bugs are not accepted.
