### ISSUE TITLE
Unable to 'Add viewed pictures to the browser's history' in Firefox

### ISSUE THREAD

**Issue by ckippen** [extesy/hoverzoom#321]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Unable to check box under Advanced > Add viewed pictures to the browser's history

## Url of the page where the problem occurs (not the image url)
Hover Zoom+ Options

## Steps to reproduce the problem (include image url here)
1.
2.
3.

## OS version, extension version (Chrome only, Firefox is not supported)
Firefox 57.0.1

**Comment by extesy** [comment]
Firefox is not supported
