### ISSUE TITLE
new shortcut suggestion: open image in new *background* tab

### ISSUE THREAD

**Issue by baz357** [extesy/hoverzoom#324]
This would - like the current "open image in new tab" shortcut - open the image in a new tab, but in the background, not going to that tab.

Benefit: on pages like the Google image search, you could open all the images you want in new (background) tabs without having to move back to the image search tab again and again.

Thanks for this great extension!

**Comment by ajlomagno** [comment]
In the options of hoverzoom in the tab called actions keys there's an option called "Open image in a new tab" which is bound to a key. Pressing `Shift+key ` opens a tab in the background whereas just pressing the bound key will open the tab and take you to it. Is this what you were looking for?

**Comment by baz357** [comment]
Oh! I totally missed that... yes, that's perfect, thank you! :)
