### ISSUE TITLE
unable to access options on hoverzoom+

### ISSUE THREAD

**Issue by frogbong1** [extesy/hoverzoom#33]
it wont let me click on any options

**Comment by extesy** [comment]
I can't reproduce that so I need more details from you. What is your OS and browser version? Can you try opening Chrome dev tools and see if there are any errors on the console tab?

**Comment by AltarBeastiful** [comment]
I get an error from gumby when opening the options :
```javascript
Uncaught ReferenceError: yepnope is not defined
gumby.min.js:1
```
Tested on Windows 10, chrome version 47.0.2526.106 m, HoverZoom+ 1.0.43

**Comment by extesy** [comment]
This is weird because options worked for me and majority of other users. I've merged the pull request anyways, hopefully that would help. Please try version 1.0.44.

**Comment by frogbong1** [comment]
Im using windows 10 and version 1.0.44 and chrome is up to date. when I open the options page it shows "general, sites, action keys and advanced" I can't click on any of it

**Comment by frogbong1** [comment]
I just restarted my LT and now its working.
