### ISSUE TITLE
Cannot save images on Chrome

### ISSUE THREAD

**Issue by TiliSleepStealer** [extesy/hoverzoom#337]
## Description of the problem
When pressing the save image button (S) it does not download the image, but opens it instead. 

## Url of the page where the problem occurs (not the image url)
Any image.

## Steps to reproduce the problem (include image url here)
1. Hover on any image
2. Press S
3. Observer that image is not downloaded.

## OS version, extension version (Chrome only, Firefox is not supported)
Version 65.0.3325.51 (Official Build) beta (64-bit)

**Comment by extesy** [comment]
Can't reproduce on Chrome 64. Beta/Canary/Dev builds are not supported.
