### ISSUE TITLE
Support for Steam store (store.steampowered.com) image carousel

### ISSUE THREAD

**Issue by 07416** [extesy/hoverzoom#338]
[example page](http://store.steampowered.com/app/356500/STAR_WARS_Galactic_Battlegrounds_Saga/)

Steam's native image viewer (click on a thumbnail followed by larger image) doesn't show the image at full size. Please add support to browse through the entire gallery. Videos shouldn't be included.

**Comment by GrosPoulet** [comment]
Fixed by #539
