### ISSUE TITLE
pixabay.com problem

### ISSUE THREAD

**Issue by xrTor** [extesy/hoverzoom#339]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
all images are zoomed only first 6 lines all other lines on uploader page or browse pag resultes are not zoomed

## Url of the page where the problem occurs (not the image url)
pixabay.com

## Steps to reproduce the problem (include image url here)
1.pixabay.com
2.search something and check the bottom lines of the resultes
3.

## OS version, extension version (Chrome only, Firefox is not supported)
chrome and windows and the aextension/addon updated to the last, wundows 10 64 home

**Comment by GrosPoulet** [comment]
Pixabay plug-in was added a few years ago. It works fine even when you scroll down results pages for a loooooong time.
