### ISSUE TITLE
isue with the site streamable.com

### ISSUE THREAD

**Issue by super10man** [extesy/hoverzoom#34]
if you hover for ½ to 1 second over a link to streamable.com the audio will keep playing even after leaving zoom and the audio loops.

**Comment by extesy** [comment]
I've tried on https://www.reddit.com/r/soccer with several links and different hover durations but I couldn't reproduce this bug. Any suggestions what else I can try?

**Comment by super10man** [comment]
i did it on /r/mma i move the cursor away right before the loading icon appears and it seems to be quite easy to reproduce.

**Comment by extesy** [comment]
I was able to reproduce the problem on /r/mma. Thanks for the report, I'll try to fix the bug.
