### ISSUE TITLE
Timestamp and Using Mousewheel/Trackpad to scroll through videos not working - Firefox Quantum 58.0.2

### ISSUE THREAD

**Issue by picklejoe69** [extesy/hoverzoom#342]
## **Description of Problem**
Even with the "Show timestamp on videos" option selected, the timestamp does not show up at all (works fine on Chrome). Mousewheel/Trackpad also does not change video position/navigates within video when hovered over video (works fine on Chrome) and no I do not have the "Don't use mousewheel to navigate within video (action keys will still work)" option selected 

## **Page URL**
reddit.com front page, any video link (youtube, v.reddit.com, streamable, etc.)

## Steps to reproduce the problem (include image url here)
1. Using Firefox go onto any page with a hoverable video link and hover over it using the correct settings as detailed above
2. Notice the missing timestamp
3. Try to scroll through video

**Comment by extesy** [comment]
Firefox is not supported
