### ISSUE TITLE
Settings reset when browser is closed (Firefox)

### ISSUE THREAD

**Issue by 07416** [extesy/hoverzoom#345]
## Description of the problem
Configuration settings reset back to the default when browser closed or restarted.
link to the extension: https://addons.mozilla.org/en-US/firefox/addon/hoverzoom-plus/

## Steps to reproduce the problem 
1. Restart Firefox.

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10, Hover Zoom+ 1.0.127, Firefox 58.0.2 (as stated in the template above, "Firefox is not supported", but I'm opening this issue as [there are at least four open issues for the Firefox version](https://github.com/extesy/hoverzoom/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+firefox))

**Comment by 07416** [comment]
There [is an issue](https://github.com/extesy/hoverzoom/issues/116) about this same problem, I assumed that the report is about _non-functional save feature_ as stated in the title.

**Comment by extesy** [comment]
Firefox is not supported
