### ISSUE TITLE
Firefox Mouse Scroll

### ISSUE THREAD

**Issue by YostyLad** [extesy/hoverzoom#346]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Unable to scroll through images in an album

## Url of the page where the problem occurs (not the image url)
www.reddit.com

## Steps to reproduce the problem (include image url here)
1. Go on Reddit
2. Find Album
3. Use mouse wheel

## OS version, extension version (Chrome only, Firefox is not supported)
Firefox 58.0.2 (64-bit)

**Comment by extesy** [comment]
Firefox is not supported
