### ISSUE TITLE
mouse cursor doesn't disappear when hovering

### ISSUE THREAD

**Issue by alivefromsomewhere** [extesy/hoverzoom#347]
the mouse cursor doesn't disappear when hovering and it stays on top of the content .

everywhere, www.facebook.com, boards.4chan.org ....

1.open site
2.use the extension on a photo that covers the display
3.you'll get a mouse cursor on the way, ofc while checking Extend zoomed images below the mouse cursor ( except it's not below)  

win10 64bit, 1.0.125
thank you sir

also I'd like to request a feature, I use the push button to activate but I want it to be automatic on some sites where I don't have to push. whitelist.

**Comment by GrosPoulet** [comment]
An option was added to hide mouse cursor after a delay:

![image](https://user-images.githubusercontent.com/23529041/146353254-ecf67be5-5b75-49d1-bb6c-579240ad86f6.png)
