### ISSUE TITLE
Zoomed Gifs/Twitch clips are playing at a lower fps.

### ISSUE THREAD

**Issue by flopwop** [extesy/hoverzoom#352]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
When zooming gifs/twitch clips, the zoomed image seems to be playing at a lower fps than intended.

## Url of the page where the problem occurs (not the image url)
reddit.com

## Steps to reproduce the problem (include image url here)
1. reddit.com/r/all
2. hover any picture (ex. https://gfycat.com/CommonSoreIndianhare)
3. choppier gif is displayed, evident when clicking the link and going directly to the website.

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 Home, Chrome Version 65.0.3325.146 (Official Build) (64-bit)

P.S. Using a 144hz monitor, could be part of the issue.

**Comment by ivan2340** [comment]
Should hopefully be fixed now @extesy

**Comment by extesy** [comment]
Fixed by fe3601c023219da61c1ff18733169169e19bdf32
