### ISSUE TITLE
Not zooming profile images in LinkedIn

### ISSUE THREAD

**Issue by richardhauer** [extesy/hoverzoom#354]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Hovering profile images in LinkedIn doesn't do anything in current Chrome or Firefox on Windows 1709. When you open a user profile there is a right-side list of profiles called "People Also Viewed" - hovering these images has no effect.  Also in many other places, actually.

## Url of the page where the problem occurs (not the image url)
https://www.linkedin.com/in/richardhauer/

## Steps to reproduce the problem (include image url here)
1. Log into LI
2. View a user profile (any)
3. Note the right-bar "People Also Viewed" containing a number of user profile photos
4. Hovering these does not show the zoom window

Image URL: `https://media.licdn.com/dms/image/C4D03AQHg3Iy2zlxwoQ/profile-displayphoto-shrink_100_100/0?e=1526716800&v=alpha&t=RdAgpSHSKCky5Mk9_olx_ipM7UDx9jf-DAwUOvlBmuI`

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 x64 v1709
Chrome 65.0.3325.162
Extension 1.0.125

**Comment by Cris70** [comment]
Same here
