### ISSUE TITLE
Chrome Web Store description updates - Added permission

### ISSUE THREAD

**Issue by JoshuaaMichael** [extesy/hoverzoom#363]
## Description of the problem
This new Managing Downloads permission is needed, the description of the extension will need to be updated on the Chrome Web Store.
"The only permission it needs is to access data on all websites (to extract full images), and optional permissions to access browser history or get tab urls for per-site configuration."

## Url of the page where the problem occurs (not the image url)
https://chrome.google.com/webstore/detail/hover-zoom%20/pccckmaobkjjboncdfnnofkonhgpceea?hl=en

## Steps to reproduce the problem (include image url here)
1. Go to page above
2. Read the information and confirm it's incorrect

## OS version, extension version (Chrome only, Firefox is not supported)
Chrome

Related to closed ticket #361

**Comment by extesy** [comment]
@JoshuaaMichael It's already updated:

> The only permission it needs is to access data on all websites (to extract full images), downloads (to save image) and *optional* permissions to access browser history or get tab urls for per-site configuration.
