### ISSUE TITLE
Wary of the new Permissions Requirements

### ISSUE THREAD

**Issue by Laraso** [extesy/hoverzoom#364]
Started up my browser today to see that nothing was happening. Checked my extensions page and noticed it told me that it was disabled because it requires new permissions.

**Why does this extension now need to be able to read and change all the data on the websites I visit and also manage my downloads?**

Screenshot: https://i.imgur.com/TNtNPOc.png

Not reactivating it until I get an answer...

**Comment by khamseen** [comment]
If you read the multitude of other posts about this same thing before posting, you'd have your answer already :P 
It's because of the changes to fix saving images (using S key) it now uses the Chrome API for downloading and thus needs permission to use that.
