### ISSUE TITLE
I'd like a version without the download feature.

### ISSUE THREAD

**Issue by Zenivo** [extesy/hoverzoom#365]
## Description of the problem
The latest update wants to manage your downloads. I'm not okay with that, even though it may only be for the download image feature. I just want the hover to view image feature, that's it.

## Url of the page where the problem occurs (not the image url)
Not required.

## Steps to reproduce the problem (include image url here)
1. Open Chrome.
2. Notice permission change.
3. Uninstall Extension.

## OS version, extension version (Chrome only, Firefox is not supported)
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by brucou** [comment]
The exact same issue brought me here. I don't want to give permissions to manage my downloads. So I'd like to keep the same old version if that would be possible.

**Comment by cpenny42** [comment]
same

**Comment by tmhisey** [comment]
I plan to uninstall unless the permission to manage downloads is removed.

**Comment by extesy** [comment]
Making permission dynamic is a bit complicated. I'll get to it when I have some time. But in any case you can see exactly what this permission is used for: deac0fe.

**Comment by brucou** [comment]
That is a good point, and I thank you for a prompt answer. I understand that this is something you do on your free time, and I don't want to sound like I take your time for granted or anything like that.

It is coincidental that in recent news we have seen the impact that intended and unintended data sharing may have. I have always cautious about not accepting something that I do not fully understand and agree with. I understand there is no ill will, but anything can change for any reasons and while that permission is unlimited in time, my attention span is not. If you could find the time to add the dynamicity you mention (or publish a separate extension Zoom++ with all bells and whistles, and rollback Zoom+ to the previous behaviour), that would be greatly appreciated.

**Comment by ivan2340** [comment]
I have now issued a hotfix and am waiting for it to be merged... I'm kind of pissed that people rush out and put 1 star reviews on the chrome store and just straight up uninstall the extension without seeking any conversation.. It's my first time contributing to such a project and i just wanted to fix the main issue that i was having with this extension because it's the first thing i install on chrome, and i am a very heavy user of the download feature...

**Comment by brucou** [comment]
Yeah that is unfortunate. People can react without much nuances in the online world. Maybe the extension system itself is also favouring the lack of communication (as a user you just see that someone wants to manage your downloads, and not the reason behind so for some people it is some kind of unprompted aggression), and forces update on you whether you like it or not.

In any case, don't let that bring you down. The extension is awesome, and I am going right now to put a 5-* review to it. I only have 4 extensions at all time in my browser and that is one of them.

**Comment by extesy** [comment]
Fixed in 30602dcadcdac0bc5f59e406034994f74b67580a, available in version `1.0.127`
