### ISSUE TITLE
Hovering image with ancor at end of url doesn't work.

### ISSUE THREAD

**Issue by blamarche** [extesy/hoverzoom#369]
## Description of the problem
Trying to hover an image that normally works, but where the URL ends in #_whatever_ will fail to show the image. 

## Url of the page where the problem occurs (not the image url)
See steps

## Steps to reproduce the problem (include image url here)
1. Hover [test image no anchor](https://i.imgur.com/OM1jAhs.gif) - works
2. Hover [test image w anchor](https://i.imgur.com/OM1jAhs.gif#icon) - doesn't work

## OS version, extension version (Chrome only, Firefox is not supported)
ArchLinux. Extension 1.0.126

**Comment by ivan2340** [comment]
Nice, i can reproduce this, i'll see if i can get out a fix today

**Comment by extesy** [comment]
Thanks for the report, @blamarche. This should be easy to fix.
