### ISSUE TITLE
Not zooming anything on Reddit

### ISSUE THREAD

**Issue by Smity31** [extesy/hoverzoom#373]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

The reddit UI has changed in the last couple of days, and since then none of the images/links are 'zoomed' by hover zoom. I'm not sure if anyone else is having this problem, since I seem to be the first to have posted about it here.

reddit.com

1. Go to reddit.com
2. Try to hover over any image/video/link
3. See if it zooms

HoverZoom+ vers. 1.0.129
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by extesy** [comment]
@Smity31 You can switch back to the old reddit UI

**Comment by MattRK** [comment]
@extesy I mean, that is a valid workaround. However, it doesn't solve the issue. The Reddit redesign is here to stay. It makes sense to update the extension to work with the new layout.

**Comment by phadnett** [comment]
any update on this?

**Comment by onedr0p** [comment]
I've moved to the Imagus extension on Chrome, now it works :)

**Comment by LiliaDoe** [comment]
This is fixed in everything but searches by #1443
