### ISSUE TITLE
Album scroll no longer working

### ISSUE THREAD

**Issue by Dethley** [extesy/hoverzoom#382]
## Description of the problem
Unable to scroll through albums.  This is not website specific.

## Url of the page where the problem occurs (not the image url)
reddit.com...imgur.com...etc.

## Steps to reproduce the problem (include image url here)
1. Hover an album and scroll.  Page scrolls instead of pictures.  The setting " Use mousewheel to navigate albums" is enabled.  I have attempted to disable it and re-enable.  Have also re-installed extension.

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 7 64 bit
Chrome - Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by theandrewk27** [comment]
I have this same problem with MacOS High Sierra and Firefox version 61.0 61-bit.

**Comment by guillermofbriceno** [comment]
I'm having the same issue, was it working for you before at some point?

**Comment by guillermofbriceno** [comment]
I'm having the same issue, was it working for you before at some point?

**Comment by AhmedKamal20** [comment]
It's working fine with me on :
- HoverZoom+ Version 1.0.132
- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Linux Ubuntu 16.04

**Comment by guillermofbriceno** [comment]
Still having issues, on 1.0.132
- Firefox 62.0 (64-bit)
- Fedora 28

**Comment by TheHappyDude** [comment]
Same issue on 1.0.132. Scroll wheel does not work even when selected in settings, arrow keys do.

- Vivaldi 2.0.1309.37 (32-bit)
- Chromium 69.0.3497.102
- Windows 10

**Comment by inimical** [comment]
Scrolling moves page instead of album item/skip ahead in YouTube videos

- Version 1.0.132
- Google Chrome Version 71.0.3559.6 (Official Build) dev (64-bit)
- OSX 10.10.5

**Comment by iNSPODS** [comment]
I'm having the same issue.
Version 1.0.134
Google Chrome Version 73.0.3683.39 (Official Build) beta (64-bit)
Windows 10

**Comment by VirtusB** [comment]
Also having this issue, just started

**Comment by SPBarbu** [comment]
Same issue. Something changed. It wasn't doing that a week ago.
Version 1.0.134
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Windows 10

**Comment by extesy** [comment]
Fixed in 1.0.135

**Comment by paOol** [comment]
still having the issue on 

1.0.136

chrome  75.0.3770.100
