### ISSUE TITLE
When clicking "S" do download the image that is currently zoomed in the downloaded image appears to be corrupted

### ISSUE THREAD

**Issue by Sasadminoni** [extesy/hoverzoom#387]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
When clicking "S" do download the image that is currently zoomed in the downloaded image appears to be corrupted

## Url of the page where the problem occurs (not the image url)
No url

## Steps to reproduce the problem (include image url here)
1.Download image by clicking "S"
2.Try to open the image
3.The image is corrupted on both WINDOWS and MACOS (Chrome and Vivaldi)

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10, MACOS, Chrome and Vivaldi

**Comment by ivan2340** [comment]
Could you elaborate on what you mean by "corruption" right now theres a bug where the extension will download the same webm no matter the link, this is fixed and i'm waiting for @extesy to merge

**Comment by Sasadminoni** [comment]
I mean the pic that is downloaded by clicking "S" cannot be opened by any program. I tried this in MAC and Windows and it the same. It appears that it does not download completely because the size is quite different if I download it manually (ex: 345kb vs 1.1mb). If I download the image manually its okay.

**Comment by ivan2340** [comment]
Can you retry changing the filetype to .webm and try then opening it? If this works this will be fixed with the next patch

**Comment by AhmedKamal20** [comment]
@ivan2340 that's it , it's the same .webm bug, but with different ext. it seems corrupted to the photo viewer.

**Comment by ivan2340** [comment]
Ok then just wait for the merge :) i'm really sorry i though i had removed that line...

**Comment by Sasadminoni** [comment]
Yes, when I change it to webm it opens now, but its always the same thing. Some waves and a cliff. Looks like a star wars ship in the water.

I assume its the same issue as the webm download, as @AhmedKamal20 said

**Comment by extesy** [comment]
Fixed in `1.0.132`.

**Comment by Sasadminoni** [comment]
Thank you!!! :)
