### ISSUE TITLE
Will there be support for new Reddit site?

### ISSUE THREAD

**Issue by jr611** [extesy/hoverzoom#388]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
support for new reddit

## Url of the page where the problem occurs (not the image url)
www.reddit.com

## Steps to reproduce the problem (include image url here)
1.
2.
3.

## OS version, extension version (Chrome only, Firefox is not supported)
chrome

**Comment by extesy** [comment]
Duplicate of #373
