### ISSUE TITLE
Tweetdeck images not working

### ISSUE THREAD

**Issue by CrappyUser** [extesy/hoverzoom#394]
## Description of the problem
Hoverzoom is not working on Tweetdeck, it seems to be getting some extra arguments for the URL and they break the direct image links. _(It adds things like [?format=jpg&name=240x240"] at the end of the image URL)_. Strangely enough the extension works fine if I try it on the same image but on Twitter.com

## Url of the page where the problem occurs
https://tweetdeck.twitter.com/

## Steps to reproduce the problem
1. Hover over any tweet image _(Videos and profile pictures seem to work fine)_
2. Image fails to load and I get a blank square where it should've loaded ([x](https://i.imgur.com/Dpiyc2c.png))
3. if you press the hotkey to open the image on another tab you get [this](https://i.imgur.com/ICy2bWa.png)

## OS version, extension version
Windows 7 Ultimate x64 // Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by ivan2340** [comment]
this works for me

**Comment by unclnis** [comment]
Images on Tweetdeck (https://tweetdeck.twitter.com) are still not displayed. Any chance to get this fixed?
Thanks

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284

**Comment by extesy** [comment]
Should be working now in 1.0.163

**Comment by unclnis** [comment]
> Should be working now in 1.0.163

It does! Much appreciated :-) Is there a way to support the work via a donation?

**Comment by extesy** [comment]
@unclnis I really appreciate the offer but I'm not doing this for donations. A good word or review is enough for me :)
