### ISSUE TITLE
hoverzoom no longer works on pixiv.com

### ISSUE THREAD

**Issue by maple3142** [extesy/hoverzoom#408]
## Description of the problem

Hoverzoom popup no longer appears even if `Pixiv` plugin is enabled.

## Url of the page where the problem occurs (not the image url)

https://www.pixiv.net/

## Steps to reproduce the problem (include image url here)
1. Go to https://www.pixiv.net/member_illust.php?id=4147414
2. Hover the mouse on any image below

## OS version, extension version (Chrome only, Firefox is not supported)

Windows 10 x64
Hoverzoom 1.0.132

**Comment by extesy** [comment]
This should be working, was fixed a long time ago.
