### ISSUE TITLE
Bing images not working

### ISSUE THREAD

**Issue by iamauser231** [extesy/hoverzoom#415]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Bing images do not seem to zoom

## Url of the page where the problem occurs (not the image url)
https://www.bing.com/images/search?q=beyonce
https://www.bing.com/images/search?q=(any query)

## Steps to reproduce the problem (include image url here)
1. https://www.bing.com/images/search?q=beyonce
2. Hover over an image
3. Image does not zoom

## OS version, extension version (Chrome only, Firefox is not supported)
Browser | Chrome
Browser Version | 67.0.3396.87
User Agent String | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
OS Type | Macintosh
OS Name | OS X 10.9.5
Same on a Windows 7 machine

## Notes:
In the view source each image seems to be a  <li tag, inside a <a tag, inside is some json "m="{(json)}, inside is "murl" which has a direct image address. Not sure if this helps

Thanks! Hope this is fixed soon.

**Comment by kamalesh0406** [comment]
Check pull request #417

**Comment by kamalesh0406** [comment]
Hope this solves this issue

**Comment by iamauser231** [comment]
> Hope this solves this issue

@kamalesh0406 

Hi thanks for looking at this.

I am not sure how all site this works but will the extension only start working after the chrome plugin is updated by the admin? i am not sure sorry. 

I have tried reinstalling the plugin on chrome store but bing still not working.

Since you know how to code could you look at this instagram issue also, it might be easy to fix github.com/extesy/hoverzoom/issues/414 i have added notes

How to get the admin to update on chrome store?

Thanks again

**Comment by extesy** [comment]
Fixed in #417
