### ISSUE TITLE
gfycat API has changed

### ISSUE THREAD

**Issue by jason-e** [extesy/hoverzoom#416]
## Description of the problem
https://github.com/extesy/hoverzoom/blob/640f428b31b043acea0bb8f065e9191c3b65b311/plugins/gfycat.js#L8
It seems gfycat has stopped supporting the api url `https://gfycat.com/cajax/get/{id}`. The equivalent new url is `https://api.gfycat.com/v1/gfycats/{id}` (the same data is returned). [Their API documentation](https://developers.gfycat.com/api/#getting-info-for-a-single-gfycat) suggests this request must be authenticated, however the endpoint seems to work without authentication like the old url.

## Url of the page where the problem occurs (not the image url)
Any gfycat.com image, [example on reddit](https://www.reddit.com/r/aww/comments/a1bufu/golden_retrievers_are_way_too_wholesome/) or [direct link](https://gfycat.com/yawningunfitelephant)

## Steps to reproduce the problem (include image url here)
1. Mouse over the image link (`https://gfycat.com/yawningunfitelephant`)
2. HoverZoom requests `https://gfycat.com/cajax/get/yawningunfitelephant` which results in a 404

The low resolution gif `https://thumbs.gfycat.com/YawningUnfitElephant-size_restricted.gif` is shown (not sure how it even manages this). The image that should be shown is `https://giant.gfycat.com/YawningUnfitElephant.webm`

[Working API link](https://api.gfycat.com/v1/gfycats/yawningunfitelephant)

## OS version, extension version (Chrome only, Firefox is not supported)
N/A (Windows 10, extension version 1.0.132)

**Comment by RumplesWrinkles** [comment]
I'm also experiencing this issue, however, the working API link in the example above does not work for me.

**Comment by jason-e** [comment]
@RumplesWrinkles Just to be clear, that link can be navigated to in order to get JSON data about a gfycat file, it isn't a Hover Zoom-able link. Are you actually unable to navigate to it? If so, what happens when you try to do so?

**Comment by DrakeOlson** [comment]
I am getting the same issue. It it just as simple to change that line to the correct one? I have tried HoverZoom and HoverZoom+

**Comment by Eiion** [comment]
Same

**Comment by extesy** [comment]
Fixed in #418
