### ISSUE TITLE
Disable extension on current site not working

### ISSUE THREAD

**Issue by lukasasorensen** [extesy/hoverzoom#423]
When I want to disable hoverzoom for a specific site, I have to go to the settings and enter in the site name and press save. I would like the option to add the current site I am on to that list through the pop up menu when you press the hoverzoom extension icon.

**Comment by lukasasorensen** [comment]
I would be willing to take on this issue myself if it is wanted

**Comment by lukasasorensen** [comment]
I realized after creating this issue that it seems that the checkbox in the popup labelled "Allow per-site extension configuration" is supposed to disable the current site. The wording on that seems confusing to me. Unless I am wrong about the purpose of this checkbox, but it seems like, from reading the code, that a more reasonable name would be: "Disable hoverzoom for current site"

**Comment by lukasasorensen** [comment]
The checkbox also does not work. It adds "null" to the list of sites hoverzoom should be disabled on

**Comment by lukasasorensen** [comment]
I was able to figure out the issue. First, chrome.tabs.query() returns an array. The code was not accounting for this. Second, it was querying for only active: true which returns the active tab from each window you have open, so if you have multiple windows open it will return more than one tab, so I added currentWindow: true to fix this

**Comment by extesy** [comment]
Fixed by #424
