### ISSUE TITLE
Not working on twitter

### ISSUE THREAD

**Issue by shinobumw** [extesy/hoverzoom#428]
## Description of the problem

Twitter rolled out the redesigned interface recently, and hoverzoom is not working.

## Url of the page where the problem occurs (not the image url)

https://twitter.com/

## Steps to reproduce the problem (include image url here)

1. Opt-in the new twitter
2. Hover the mouse to any desired image on twitter site

## OS version, extension version (Chrome only, Firefox is not supported)

- Windows 10 1809
- Chrome 71.0.3578.98
- Hover Zoom+1.0.133

**Comment by grummkruger** [comment]
The thing is, it works for me in incognito but not on a regular window.

**Comment by Explorare** [comment]
The new design is out of beta and used by default now. It's would be great if the extension works on Twitter again.

**Comment by bobbydigital24** [comment]
Also having trouble on (new) Twitter. Love the extension. Hoping for a fix!

**Comment by kasiajuda** [comment]
i really wish this would work on twitter. i use twitter for work and am constantly opening pictures and now im spending extra time to open it. would love if it would work again.

**Comment by markperezone** [comment]
up up
