### ISSUE TITLE
New tab media has no sound

### ISSUE THREAD

**Issue by warhead0** [extesy/hoverzoom#439]
When opening a video with the new tab button (T) videos will be muted and are unable to be un-muted.

This is something I really only noticed an issue with Reddit.

1. I find a video or something that I would like to share; https://old.reddit.com/r/funny/comments/bcjifd/this_expression_on_this_dog/

2. Using action key 'T' I can open the media in a new tab and it looks like this; https://v.redd.it/ce72s6elpwr21/DASH_1080

3. Now I have the video open on my new tab and it is working, however there is no audio at all, and I'm not sure how to restore the audio.

I'm using version;
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
running on
Win 10 Pro  v1809 build 17763.404

Hope this has an easy fix.
Thanks,

Corey

**Comment by GrosPoulet** [comment]
Hi @warhead0, this issue was fixed by #751 : an audio player is displayed with usual controls (volume, download...)
