### ISSUE TITLE
Feature request: Dark overlay without ambient light

### ISSUE THREAD

**Issue by paulschmeida** [extesy/hoverzoom#44]
Should be pretty easy to implement, just add an option to enable dark overlay background, but no ambient glow from the picture. Sometimes the ambient glow lags a bit and I'm sure it won't be a problem with only dark overlay.

**Comment by Lucane** [comment]
This would be nice. On older hardware the ambient glow slows down videos/gifs considerably since it's not optimised properly.

**Comment by GrosPoulet** [comment]
This request was addressed by improvements on Ambilight feature (August, 2020)
