### ISSUE TITLE
You Tube videos won't zoom up/play

### ISSUE THREAD

**Issue by Psl85** [extesy/hoverzoom#448]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
You Tube videos won't play while I is howering over them in google/other sites. This is very frustating and I want to have them zoomed without having to go to youtube.com to watch them.

## Url of the page where the problem occurs (not the image url)
https://www.google.com/search?q=watch+dogs+legion+map&safe=active&rlz=1C1AKJH_enSE768SE768&source=lnms&sa=X&ved=0ahUKEwjm1JWXk_XiAhWHxIsKHVLhB_MQ_AUICygA&biw=1680&bih=907&dpr=1

## Steps to reproduce the problem (include image url here)
1. 
2.
3.

## OS version, extension version (Chrome only, Firefox is not supported)
windows 10 (unknown version), latest google chrome version, extension version is 1.0.136

**Comment by kamalesh0406** [comment]
This issue is similar to #402 . Please don't add redundant issues. Comment on the older issue that you are facing a similar problem with your version and Browser.
