### ISSUE TITLE
youtube video name tooltips

### ISSUE THREAD

**Issue by marvel96** [extesy/hoverzoom#449]
when using youtube tool-tips don't show up anymore when hovering on video name with the cursor

##Url of the page
youtube.com

Steps to reproduce the problem (include image url here)
1- open youtube
2- hover with the cursor on any video title

OS version, extension version 
windows 10, hoverzoom+ version 1.0.136

**Comment by kamalesh0406** [comment]
This is the same issue as #402 . Try to not put up the same issue again. I will check on this.
