### ISSUE TITLE
DataSpii: How extensions hide their data grabs—and how they’re discovered

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [extesy/hoverzoom#451]
## Description of the problem
hover spy affaire
i have read about extension hover zoom in the news for spying its users and getting removed of chrome and mozilla extension store. what about this fork?

## Url of the page where the problem occurs (not the image url)
https://arstechnica.com/information-technology/2019/07/dataspii-technical-deep-dive/?comments=1

## Steps to reproduce the problem (include image url here)
1.https://arstechnica.com/information-technology/2019/07/dataspii-technical-deep-dive/?comments=1

## OS version, extension version (Chrome only, Firefox is not supported)
Chrome

**Comment by extesy** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software You can look at the source code. Try to find any spyware in it.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Sure , everyone can see it himself, if there would be any. Same for the mentioned extension this is based on. But in Practice, who checked it and see it on forked before using this fork.?.. Not to blame this repo for it.

**Comment by extesy** [comment]
I don't know how to respond to that. If you are interested in this issue, then you can check it personally. Or do you have some specific "authority" in mind to "approve" this fork?
