### ISSUE TITLE
On google image search, sometimes starts to spin icon, but then nothing is displayed

### ISSUE THREAD

**Issue by WilfulTravesty** [extesy/hoverzoom#452]
## Description of the problem
Sometimes the extension acts like it is going to zoom an image, but then does nothing. For example, on the right-most image of the top line of the google image search below.

## Url of the page where the problem occurs (not the image url)
https://www.google.com/search?q=area+51+signs&rlz=1C1CHBF_enUS841US841&tbm=isch&source=iu&ictx=1&fir=0LJ2g8ZjR_8mrM%253A%252C1tM721Lk9eZLCM%252C_&vet=1&usg=AI4_-kS2XIDHd5AYdIM2W6UBJZMzGwOAOg&sa=X&ved=2ahUKEwjKr8LAk8fjAhURUa0KHWNLB2gQ9QEwAHoECA4QBA#imgrc=0LJ2g8ZjR_8mrM:

## Steps to reproduce the problem (include image url here)
1. go to https://www.google.com/search?q=area+51+signs&rlz=1C1CHBF_enUS841US841&tbm=isch&source=iu&ictx=1&fir=0LJ2g8ZjR_8mrM%253A%252C1tM721Lk9eZLCM%252C_&vet=1&usg=AI4_-kS2XIDHd5AYdIM2W6UBJZMzGwOAOg&sa=X&ved=2ahUKEwjKr8LAk8fjAhURUa0KHWNLB2gQ9QEwAHoECA4QBA#imgrc=0LJ2g8ZjR_8mrM:
2. hover over the right-most image of the first row ("Area 51 Front Gate" from lazygranch.com)
3. the extension shows the spinning icon for 1-2 seconds
4. then nothing happens

## OS version, extension version (Chrome only, Firefox is not supported)
Extension Version 1.0.136
Chrome 75.0.3770.142 (Official Build) (64-bit)
Windows 10 Pro version 1903 OS Build 18362.239

![2019-07-21 18_44_00-Zoom Issue](https://user-images.githubusercontent.com/6433968/61598751-a1b06d80-abe7-11e9-9c61-1bdc7d553ffc.png)

**Comment by GrosPoulet** [comment]
Hi @WilfulTravesty 
There is a new option in latest releases of HZ+ : "**Try to open unloadable urls in separate window/tab**"
If you enable it & save settings then images that can not be zoomed on Goggle Images search results page will be displayed in separate window or tab.
For instance, with "Area 51 Front Gate" from lazygranch.com:
![image](https://user-images.githubusercontent.com/23529041/107874315-02ce1f00-6eb9-11eb-97b7-449aaa75ecb6.png)
