### ISSUE TITLE
Youtube previews don't work on reddit

### ISSUE THREAD

**Issue by Happy0-0** [extesy/hoverzoom#454]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
When i go to a website like www.reddit.com/r/videos and hover over one of the links the video doesn't show up in a another video.

## Url of the page where the problem occurs (not the image url)
www.reddit.com/r/videos

## Steps to reproduce the problem (include image url here)
1. go to website
2. hover over a link to a *youtube* video
3. see if video pops up

## OS version, extension version (Chrome only, Firefox is not supported)
Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by Michael18751** [comment]
I have the same issue. Global webm links simply don't load
