### ISSUE TITLE
imgur gifs (videos) on reddit don't play anymore

### ISSUE THREAD

**Issue by Eiion** [extesy/hoverzoom#458]
## Description of the problem
Gifs on imgur can't be previewed on reddit anymore. I first noticed this about 1-2 weeks ago.

## Url of the page where the problem occurs (not the image url)
imgur.com

## Steps to reproduce the problem (include image url here)
1. Surf reddit
2. hover over imgur link
3. see preview picture but not the playing gif/video

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 Pro 64bit, Chrome Version 76.0.3809.132 (Official Build) (64-Bit)

EDIT:
## Additional info:
Attention: The following links might be considered NSFW
Oddly enough it works for some but not for other links on reddit.
While this link works: https://imgur.com/a/dB2kDnx
this one doesn't:        https://imgur.com/a/6GWnjBk
Both are the same format, both apparently are stored as *.mp4.

**Comment by LiliaDoe** [comment]
neither of those links seem to be valid anymore. Can you provide new examples?

**Comment by extesy** [comment]
This is a very old bug report. Most likely it's been already fixed a long time ago. I'm closing it.
