### ISSUE TITLE
Blink and load twice

### ISSUE THREAD

**Issue by technobulka** [extesy/hoverzoom#46]
Blink and load image twice on deviantart.com. Sometimes jump to next image.
Example page - http://artgerm.deviantart.com/gallery/
Example video - https://goo.gl/Yu6G62 (<1Mb)

**Comment by extesy** [comment]
Thanks for the repro video. I can't reproduce this issue myself, but it might be related to your internet speed. I've noticed that the image was loading very slowly. I'll investigate.
