### ISSUE TITLE
Hover Zoom+ stopped working for Google image search

### ISSUE THREAD

**Issue by baz357** [extesy/hoverzoom#463]
## Description of the problem
Hover Zoom+ stopped working for Google image search

## Url of the page where the problem occurs (not the image url)
https://www.google.com/search?q=sean&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiAnbG_qvbkAhXEzaQKHTa9BTIQ_AUIEigB&biw=1477&bih=807

## Steps to reproduce the problem (include image url here)
1. open https://www.google.com/search?q=sean&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiAnbG_qvbkAhXEzaQKHTa9BTIQ_AUIEigB&biw=1477&bih=807
2. try Hover Zoom+ on any image
3. see that it works on not a single one

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10
Hover Zoom+ 1.0.137
Chrome 77.0.3865.90

**Comment by EviLFazZ** [comment]
I guess this is **still** an issue, as I now have the exact same issue as of today, using **Google's Image Search Engine** (images and GiF's) via Brave Browser (Version 1.2.42 / Chromium 79.0.3945.117 / 64-bit) and it worked perfectly fine for me 48 hours ago when I last used it 😿

**Comment by chaloots** [comment]
Crapped out recently today on Google Images using Firefox 72.0.2, Windows 10 Pro, Hover Zoom + v1.0.136.1

**Comment by MrToM528** [comment]
Seems to only work AFTER clicking a image to preview it.....which kind of defeats the whole point of it.

**Comment by MrToM528** [comment]
Installing the following script with tampermonkey made HoverZoom+ work again for me...

[https://greasyfork.org/en/scripts/29420-google-dwimages](url)

Not sure if the script actually does what it was intended for but still, works wonders!

**Comment by chaloots** [comment]
greasyfork requires Chrome. I go with Firefox as default. Thanks though.

**Comment by MrToM528** [comment]
I'm using...
Firefox 73.0.1
Tampermonkey v4.10.6105

...and it works just fine, honest.

**Comment by chaloots** [comment]
Installed. Noticeable results. Suspect it also removed previous side view with thumbnail of selected individual images. If the latter winds up to be something I can't live with, I presume removing the extension will terminate it?

Thanks, btw.

**Comment by MrToM528** [comment]
Yeah, the script does appear to work as intended, ie, it gives you a direct link to the image rather than the side panel, (which I understood wasn't very well received anyway). If you want to disable a script just click the tampermonkey icon and then the script name....it will toggle it on or off...you can also do this from the 'dashboard' which is toward the bottom of the dropdown.

I'll keep working on this and see if I can restore the normal Google layout. I found the side panel more of an annoyance but appreciate others may find it useful....I'm just happy I have HoverZoom+ back!

**Comment by chaloots** [comment]
Thanks again for the additional script info. My first. 

F*ing Google can't seem to make their mind up which way Images is gonna run.

**Comment by MrToM528** [comment]
No worries, and yes, I reckon Google's next move will be to remove the images from the image search....why not, they've removed everything else..... today I discovered that 'image size' has been ripped out of the page, I knew the option to show it had gone but the info was still there, it still shows on the larger side panel image so why remove it from the results? No consistancy. Who knows how those minds work, although they are doing a pretty good job of making Bing look good!

**Comment by MrToM528** [comment]
OK, to restore the 'Side panel' image preview, (and keep HoverZoom+ working), edit the script as follows...

Comment out, (with two forward slashes), lines 137 and 138
$result.on('click focus mousedown', stopPropagation)
$imageLink.on('click focus mousedown', stopPropagation)

To edit the script click the Tampermonkey icon, then 'dashboard'. Once opened click 'Google DWIMages' under column 'Name'.

The script will open in an editor, scroll to those lines and comment them out....SAVE the script using File > Save

You may need to reload any opened tabs for it to take effect.....and just check its enabled if you turned it off.

Good luck.
