### ISSUE TITLE
pixiv issue

### ISSUE THREAD

**Issue by xeansz** [extesy/hoverzoom#465]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
after a week i used hoverzoom, it work perfectly fine, but 3 days ago image zoom became small,
and for some reason album scroll function stop working. i never touch option menu at all, so i'm not sure why it became like this, at first i thought there was a maintenance or some sort, but after waiting till this day it doesn't fix at all, so i came here.

## Url of the page where the problem occurs (not the image url)
https://www.pixiv.net/en/artworks/77014887

## Steps to reproduce the problem (include image url here)
1. try pointing mouse to album https://ibb.co/djYd5hN
2. try pointing mouse to single picture https://ibb.co/XtgBZ54
3. try pointing mouse to other images on pixiv

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10
Hoverzoom v1.0.137
Google Chrome v75.0.3.3770.142

**Comment by fhadiel** [comment]
Pixiv make some changes in the website.
I actually already make an update for pixiv hoverzoom #464 .

If you want to use the latest version of hoverzoom, you can clone this repository and add the extension manually in chrome.

**Comment by extesy** [comment]
Fixed in version 1.0.138

**Comment by xeansz** [comment]
thanks for fixing it :D
