### ISSUE TITLE
What is !imagus folder used for?

### ISSUE THREAD

**Issue by fhadiel** [extesy/hoverzoom#466]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Steps to reproduce the problem (include image url here)
1.
2.
3.

**Comment by extesy** [comment]
Old debug files, got accidentally mixed up with the source code.

**Comment by fhadiel** [comment]
i can delete it in my fork then.
I recently start using firefox. and i test this extension . it works fine. 
You can check it here : https://addons.mozilla.org/en-US/android/addon/hover-zoom2/

Should we add firefox support?
