### ISSUE TITLE
Not working on Imagefap

### ISSUE THREAD

**Issue by Firefoxuser3** [extesy/hoverzoom#479]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
No longer works on imagefap.com thumbnails.

## Url of the page where the problem occurs (not the image url)
https://www.imagefap.com/index.php

## Steps to reproduce the problem (include image url here)
1. Go to imagefap.com
2. Mouse over any image or .gif thumbnail
3. https://www.imagefap.com/photo/2046203003/

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 64-bit, all updates applied to date. Firefox 70.0.1 (64-bit). Hoverzoom version 1.0.139 for Firefox

**Comment by GrosPoulet** [comment]
Closed by #574
