### ISSUE TITLE
Why is hover zoom asking for new permissions?

### ISSUE THREAD

**Issue by jefhtavares** [extesy/hoverzoom#48]
I'm using hover zoom on Google Chrome, and it is asking for permissions to 

- Read and modify my navigation history
- Read and modify all data in websites that I'd visited (cookies, I suppose)

Why hover zoom needs this?

**Comment by mattman00000** [comment]
I'm no expert in chrome extensions but hoverzoom operates by getting a link to the full sized image ("Reading ... data in websites that [you visit]") and then creating a div (I assume) element containing the full size picture ("modify[ing] ... data in websites that [you visit]"). "Read and modify my navigation history" is for the option Advanced > "Add viewed pictures to the browser's history"

**Comment by extesy** [comment]
> Read and modify my navigation history

This is used to add viewed images as "visited" so that browser highlights them differently.

> Read and modify all data in websites that I'd visited

Read is needed to parse html content of the page and find images there. Write is used to inject zoomed image into html page.
