### ISSUE TITLE
logical error rarely

### ISSUE THREAD

**Issue by newpost** [extesy/hoverzoom#480]
if (this.src.toLowerCase().lastIndexOf('.jpg') != this.src.length - 4) {
counter-example:
"jpg.jpg"

**Comment by extesy** [comment]
@newpost I don't see any problem here, this line searches for the last instance of `.jpg` (with dot). Your counter-example works just fine.

**Comment by newpost** [comment]
a.jpg.jpg？

Regards,

________________________________
发件人: Oleg Anashkin <notifications@github.com>
发送时间: Thursday, December 5, 2019 12:17:18 PM
收件人: extesy/hoverzoom <hoverzoom@noreply.github.com>
抄送: niceguy <zss9527@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [extesy/hoverzoom] logical error rarely (#480)


Closed #480<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fextesy%2Fhoverzoom%2Fissues%2F480&data=02%7C01%7C%7Cf1bdc5fed5e44994fa4c08d7793a0564%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637111162406716471&sdata=8JpYn1KcGTmqpwLA6H8aqeQIL%2B6pICsMxWoMjhXIwkk%3D&reserved=0>.

―

**Comment by newpost** [comment]
`“abcde.jpg.jpg”`

**Comment by extesy** [comment]
so? `.lastIndexOf('.jpg')` will return the ending `.jpg` which confirms that this file has `.jpg` extension which is the intent of this line.
