### ISSUE TITLE
Action Key for "Save Image" does not work in Chrome in 4chan and 4channel

### ISSUE THREAD

**Issue by Sasadminoni** [extesy/hoverzoom#484]
The Action Key for "Save Image" does not work in the newest Chrome 69.0.3497.100

Steps to reproduce the problem (https://boards.4chan.org/wg/thread/7523649)
Select a letter for "Save Image" in "Action Key" Tab, for example mine is set as "S"
Go in 4chan hover over an image
While hovering click "S" and the image would not save (it should save but in the newest Chrome version it doest save)
I tried other sites such as google images and reddit and it works there. It weird that only 4chan seems to be affected.

I tested it on MAC OS and Windows 10 and in both it doesn't work.

Thanks :)

**Comment by Sasadminoni** [comment]
I noticed if I press "S" right after the image I hover appears it does work, but if I wait a bit (2-3 seconds), then the download does not work.

**Comment by GrosPoulet** [comment]
Hi @Sasadminoni, this issue was solved by #692
