### ISSUE TITLE
Part of the image in the popup is blurred when the image is done loading

### ISSUE THREAD

**Issue by dubhater** [extesy/hoverzoom#485]
**Describe the bug**
The popup sometimes looks like this when the image is done loading:
![IMG_20200110_155302-crop](https://user-images.githubusercontent.com/1739488/72159451-0d200e80-33c5-11ea-8c05-5881509fbeb2.jpg)

Sometimes more of the image is blurred, sometimes less. It's always at the top. There is no blur while the image is loading. The blur appears the moment when the image is completely loaded. The blur disappears (the image clears up) as soon as I move the mouse a bit. I assume that triggers a redraw, even if I move the mouse in a way that doesn't move the popup because it's already in a corner of the screen.

I'm pretty sure this happens on several sites. This bug is probably more than a year old, I just didn't report it until now. 

**To Reproduce**
1. Hover over any image.
2. It seems to be random.

**Expected behavior**
No part of the image should be blurred.

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox 70.0.1 and older ones too
 - Addon Version: 1.0.139 and older ones too
 - Graphics: Intel(R) HD Graphics 620 (Kaby Lake GT2) (Core i3 7020U)

I enabled compositing in Firefox because I was getting tearing without it. Maybe that's relevant.

**Comment by fhadiel** [comment]
I'm in ubuntu and firefox, didn't get that problem. maybe try to disable the compositing?

**Comment by dubhater** [comment]
I disabled compositing in Firefox and went back to the image search above. The 23rd image I hovered over exhibited the same blur again. I checked the compositing in about:support and it's definitely disabled.

**Comment by dubhater** [comment]
Here are some of the problematic images:

* https://www.cuckooland.com/dnc/cuckooland/artwork/product_images/Kids-Concept-Natural-Wood-Tool-Box.jpg?quality=90&scale=canvas&width=1000&height=1000
* https://images-na.ssl-images-amazon.com/images/I/61jQWON5VgL._SL1000_.jpg
* https://www.archonaut.cz/media/k2/items/cache/51a3864ed3ad604d2340c3f8fe249f94_XL.jpg
* https://sc02.alicdn.com/kf/HTB19WvdasvrK1Rjy0Feq6ATmVXaS/234261949/HTB19WvdasvrK1Rjy0Feq6ATmVXaS.jpg
* https://www.babipur.co.uk/media/catalog/product/cache/1/image/1000x/9df78eab33525d08d6e5fb8d27136e95/p/l/plan_toys_3486_ice_cream_set_4_.jpg
* https://afilii.com/en/wp-content/uploads/sites/3/2018/05/creative-wooden-toys-for-kids-Woonkis-by-Wodibow_2.jpg

I don't know what they have in common other than the JPG format.

**Comment by dubhater** [comment]
It seems this problem disappeared after some update. (Of Firefox? Video driver? Who knows.) I haven't seen it in a long time.

**Comment by extesy** [comment]
@dubhater Thank you for confirming. I'm closing this issue.
