### ISSUE TITLE
HoverZoom locks up windows rendering

### ISSUE THREAD

**Issue by bhollan** [extesy/hoverzoom#492]
**Describe the bug**
While browsing the internet, sometimes my computer will lock up.  I dismissed this as generic until it happened three times in a row while browsing with hoverzoom.  I disabled the extension and the same content did nothing bad.

**Desktop:**
 - OS: Windows 10 Pro Insider Preview (build: 19564.rs_prerelease.200207-1438)
 - Browser Chrome 
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
When I went to check my Chrome Version, it downloaded an update.  I will comment here if I continue to experience this bug.

**Comment by bhollan** [comment]
Still happening after Chrome updated to Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by Cistoran** [comment]
I have the same issue. Notably when browsing reddit on gif heavy subreddits (Rocket League for example) Gfycat seems to be a huge culprit.

**Comment by guanzo** [comment]
Disabling hoverzoom with the domain filter doesn't seem to do anything? I can still see the extensions jQuery listening to the mouseover event, and it's causing performance issues.

**Comment by extesy** [comment]
There was a fix recently that improved performance in certain cases. I think this should address this problem too, please try the latest version.
