### ISSUE TITLE
Executes php pages on hover

### ISSUE THREAD

**Issue by fabian310** [extesy/hoverzoom#493]
**Describe the bug**
- I've got a href linking to a php file. This href url includes a php parameter containing a relative path to a file. Example: `<a href="somesite.com/something?r=/data/image.png">click</a>` .
- Upon hovering over this href the load icon of your extension shows up.
- I can see my server files change, which are supposed to change when this php file is executed .

**To Reproduce**
1. Go to some site with a href, containing a php parameter with a file
2. Hover over the href
3. See the php file doing stuff

**Expected behavior**
Don't do that php stuff

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux Ubuntu
 - Browser: Chrome, Vivaldi

**Comment by extesy** [comment]
@fabian310 How do you propose to differentiate between "php file doing stuff" and a normal image that is being served through a script?

**Comment by fabian310** [comment]
I assume you check the url for endings like .jpg, .gif, etc. . Maybe this can be fixed by checking the url for a `?` ?

**Comment by extesy** [comment]
There are lots of images that have `?` in urls.
