### ISSUE TITLE
Question about option "Extend zoomed images below the mouse cursor"

### ISSUE THREAD

**Issue by fireattack** [extesy/hoverzoom#494]
I plan to make a translation of this awesome extension, but I don't fully understand what this "Extend zoomed images below the mouse cursor" option actually does. I'm mainly confused by  "below the mouse cursor" here.

I did notice the tooltip ("If unchecked, zoomed images will be resized dynamically"), but that doesn't help much.

I tried to uncheck this option, the only difference I noticed is that if I did so, the enlarge zoom factor I set (2) will be ignored.

Could you kindly explain it a little bit (as in, what's the difference between checked and unchecked)?

It would help me to make a more accurate translation.

Thanks!

**Comment by fireattack** [comment]
Ah, thanks. I thought it's "below" in a sense of vertical space.

But why when unchecked, it also disables zoom factor of 2 on this image?
https://en.wikipedia.org/wiki/Secretariat_(horse)#Kentucky_Derby (left one)

It doesn't overlap with the cursor even when shown in 2x (can check with the option re-checked).

**Comment by extesy** [comment]
It might be a bug (as I'm not the original author of this extension), but at least that was supposed to be the idea.

**Comment by fireattack** [comment]
Thanks!
