### ISSUE TITLE
When hovering on v.reddit links, the audio doesn't sync with the video.

### ISSUE THREAD

**Issue by Rigamix** [extesy/hoverzoom#501]
**Describe the bug**
When hovering on v.reddit links, the audio doesn't sync with the video. There is a couple of seconds of silence before the audio plays, but by then the video is 2sc out of sync.

**To Reproduce**
1. Go to https://www.reddit.com/r/TikTokCringe/
2. Hover the cursor over the v.reddit links
3. The audio will not play right away and therefore be out of sync.

**Expected behavior**
The audio and video should play in sync.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - 75.0 (64-bit)

**Additional context**
Some v.reddit links have a proper synced audio when hovering on them, but the vast majority doesn't. Can't figure out what's causing this.

Thank you.

**Comment by extesy** [comment]
@Rigamix Please try version 1.0.147.
