### ISSUE TITLE
Update version for Firefox

### ISSUE THREAD

**Issue by Mte90** [extesy/hoverzoom#506]
I checked that the last release on MOzilla addons store is of 7 months ago instead for Chrome is yesterday.
It is possible to release an update for firefox users?

**Comment by extesy** [comment]
I don't own the Firefox addon, please don't ask for support here.

**Comment by Mte90** [comment]
Sorry but the links of that extension point to this repo and also the readme of this repo was pointing to that so I was thinking that was the original.

**Comment by extesy** [comment]
Links from https://addons.mozilla.org/en-US/firefox/addon/hover-zoom2/ do not point to this repo. Thanks for reminder about readme, I'll remove the link from it.
