### ISSUE TITLE
Gfycat links (on reddit) not working anymore

### ISSUE THREAD

**Issue by Eiion** [extesy/hoverzoom#517]
**Describe the bug**
Gfycat links (on reddit) are not working anymore

**To Reproduce**
1. Go to 'reddit.com'
2. Hover over any gfycat link
3. See error

**Expected behavior**
Hovering over the link opens the gif in a preview.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser: Chrome (Version 83.0.4103.61)
 - Hover Zoom+ Versions 1.0.143 and 1.0.144

**Additional context**
See https://github.com/extesy/hoverzoom/issues/508#issuecomment-631902234 and https://github.com/extesy/hoverzoom/issues/508#issuecomment-632254080 for reference.
"It appears to me that gfycat is messing around with how they host the content and moved on to pushing [...] gifs to "gifdeliverynetwork.com" instead of to redgifs... no idea what's going on with that."

**Comment by extesy** [comment]
@Eiion please post a specific reddit page where this doesn't work

**Comment by Eiion** [comment]
For example, links on https://www.reddit.com/r/wavesbeingbros/ (for gfycat URLs).

Here's a related post on the gfycat subreddit - maybe that can help:
https://www.reddit.com/r/gfycat/comments/gmire6/what_is_gifdeliverynetworkcom/

**Comment by Eiion** [comment]
Since you've (@extesy) updated the code I went ahead to give it a try:
GIFs that are still hosted directly on gfycat (not moved to redgifs, yet) are now working again, GIFs that are now delivered via https://www.gifdeliverynetwork.com/ still do not work. Same for GIFs hosted on redgifs - they still aren't working.

**Comment by extesy** [comment]
@Eiion I've tested it on your NSFW subreddit above and the fix worked. If you provide any other link where it is not working then I can take a look.

**Comment by Eiion** [comment]
Alright @extesy, I did some un- and re-installs of the extension, some restarts of the PC - for whatever reasen, just now when testing for posts hosted on gfycat/redgifs/gifdeliverynetwork via the "reddit.com/domain/URLgoeshere/"-pages everything seemed to work again. Perfect!

Many thanks for your continued work on the extension!

Any idea when the current version 1.0.144 will be up replacing version 1.0.143? (In case you push the update whenever changes/fixes are implemented - I have no idea how long it takes for google to typically replace versions.) Just wondering because of the warning message that I'm getting with every browser start because of using an extension installed in dev mode.

**Comment by extesy** [comment]
I don't know. The previous version is still "pending review". This was not necessary before and it's the first time the review is required. So I don't know how long it will take.

**Comment by Eiion** [comment]
I see. Well, I guess we'll find out. Thanks, once again!
