### ISSUE TITLE
HoverZoom+ causing flash crash on videos when AdBlock is enabled

### ISSUE THREAD

**Issue by germaloney11** [extesy/hoverzoom#52]
Playing a video on independent.ie causes the webpage to crash with "Shockwave Flash isn't responding" when AdBlock is enabled. Once you click 'stop plugin' it goes back to normal but usually crashes all the other tabs video players.

Example: http://www.independent.ie/entertainment/banter/trending/son-celebrates-mothers-day-by-constantly-scaring-his-poor-irish-mammy-then-posts-the-video-online-34525541.html

**Comment by extesy** [comment]
@germaloney11 I'm using uBlock and this page loads fine for me without any issues. I suspect this is AdBlock bug, not hoverzoom.

**Comment by germaloney11** [comment]
HoverZoom+ is still causing this problem. It works perfectly when HZ+ is disabled. AdBlock isn't causing the problem.
