### ISSUE TITLE
Extension doesn't work in Google Sheets?

### ISSUE THREAD

**Issue by fg58d3zo584** [extesy/hoverzoom#523]
## Description of the problem
I'm a new user, never tried this extension before, but recently I have read a few guides about inserting images into Google Sheets and expanding them with this extension. I've tried a few different methods, but the result is always the same: nothing happens.
It works like a dream in many other websites, I will keep it installed, but it doesn't work in Sheets.

## Url of the page where the problem occurs (not the image url)
https://docs.google.com/spreadsheets/

## Steps to reproduce the problem (include image url here)
1. Open or create any Google Sheets spreadsheet.
2. Insert a locally stored image into a cell, hover the mouse over - nothing happens.
3. Make the image a hyperlink - still nothing.
4. Insert the hyperlink of an image into a cell, mouse over - still nothing.

## OS version, extension version (Chrome only, Firefox is not supported)
OS: Windows 10 Home, Ver. 1909 Build 18363.900
Browser: Google Chrome Ver. 83.0.4103.116 (Official Build) (32-bit)
Extension: Ver. 1.0.145

**Comment by extesy** [comment]
For most simple websites there's generic support, and there are also plugins for more complex websites. There's currently no plugin available specifically for google sheets, it needs to be added.

**Comment by jdavidberger** [comment]
If you select a link, and hover over the full URL popup the image will pop up successfully. HOWEVER if there are multiple links, they all show the first image you loaded in. I made a small sheet where you can test/see this:

https://docs.google.com/spreadsheets/d/1o2PkxZyQqgolLySlcpL3xatzNJLUgFkxSnhMt-qV1cU/edit?usp=sharing

**Comment by GrosPoulet** [comment]
I can reproduce the issue: 

![image](https://user-images.githubusercontent.com/23529041/105084555-c9abb600-5a96-11eb-9484-6c0c7fc1716f.png)

I'll try to fix it this week.
