### ISSUE TITLE
Half of the videos in v.redd.it doesnt work with HoverZoom

### ISSUE THREAD

**Issue by GitAcc53** [extesy/hoverzoom#525]
**Describe the bug**
Check reddit.com/domain/v.redd.it/ , almost half of the videos in there doesnt work since 2 days ago. It was all fine since 2 days ago. 
    
**Desktop (please complete the following information):**
 - OS: W10
 - Browser chrome
 - Version 1.0.145

**Additional context**
I use "Dark Reader" and I cant see the videos on reddit without zooming them with Hover Zoom so I really need you to fix this please.

Edit: I just tried imagus on opera browser, the same videos that works also works there and the same videos that doesnt work also doesnt work on imagus. Maybe reddit had an update? I think HoverZoom needs an update aswell.

**Comment by jr611** [comment]
having same issue

**Comment by esotericsean** [comment]
Same issue here too

**Comment by Gaviell** [comment]
Also having this issue. Some vreddit videos work, many don't.
