### ISSUE TITLE
Does not load images after first 100 images in Google Image site.

### ISSUE THREAD

**Issue by yothawrani** [extesy/hoverzoom#526]
**Describe the bug**
In the google image search, the hover zoom works fine for the first 100 images, means it extracts the first 100 images and zoom it but after that it does not produce the zooming effect.

**To Reproduce**
1. Go to 'https://www.google.co.in/search?q=hello&tbm=isch&ved=2ahUKEwjkhfuLk7DqAhVICLcAHdS9AJYQ2-cCegQIABAA&oq=hello&gs_lcp=CgNpbWcQAzIHCAAQsQMQQzIHCAAQsQMQQzIFCAAQgwEyBQgAEIMBMgUIABCxAzIFCAAQsQMyAggAMgUIABCxAzIFCAAQsQMyAggAOgQIABBDUOzYPFia3zxg2eE8aABwAHgAgAFLiAHjApIBATWYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img&ei=Haf-XqSDMsiQ3LUP1PuCsAk&bih=625&biw=1366&hl=en'
2. Hover on 'any image after first 100 images'
3. See error

**Expected behavior**
Till first 100 images, the hover zoom will work but after that it will not work.

**Desktop:**
 - OS: Windows 10
 - Browser: chrome

**Comment by GrosPoulet** [comment]
Hi @yothawrani 

This issue is solved by #519, but this fix was no yet released to Chrome Web Store.
So you can either:
- wait for the release 
- download the extension from GitHub and manually load it into Chrome.

Have a nice day!
@GrosPoulet

**Comment by extesy** [comment]
@yothawrani Since #512 every update now requires a manual review and unfortunately that takes unpredictable amount of time.
