### ISSUE TITLE
Amazon - Hover doesn't work on user submitted gallery

### ISSUE THREAD

**Issue by The-KarateKid** [extesy/hoverzoom#532]
# Description of the problem
When viewing the image gallery of user-submitted images on product reviews, the hover does not work once you open the pop-up gallery by clicking "See all customer images"

## Url of the page where the problem occurs (not the image url)
https://www.amazon.com/Victiv-72-inch-Aluminum-Lightweight-Shooting/dp/B07JZCYWLZ/?pldnSite=1#customerReviews

## Steps to reproduce the problem (include image url here)
1. Go to an Amazon product page
2. Go to the Customer Reviews section
3. At the top of this section on the right and before the first review, it will say "Customer images" with up to 4 images under it. Below these images, click "See all customer images" (NOTE: The hover feature DOES work on these 4 preview images)
4. The hover feature does not work for all preview images in the pop-up gallery
5. If you click a specific image to view it along with the review, the hover feature still does not work.

## OS version, extension version (Chrome only, Firefox is not supported)
Chrome Version 84.0.4147.89 (Official Build) (64-bit)
macOS 10.14.6

**Comment by GrosPoulet** [comment]
User-submitted images in pop-up galleries are now correctly handled.
