### ISSUE TITLE
Add separate delay for videos

### ISSUE THREAD

**Issue by jjfahner** [extesy/hoverzoom#54]
Having a separate delay for videos would be really nice. I like my images to pop up immediately, but because my timeout is set to the lowest value, with videos I now have to click when the video is already hovering, and end up with the hovering video still playing in the reddit tab while the new youtube tab also plays the same video (the hover window doesn't close when I click the link to open the video in a new tab, which is my default for links).

Thanks!

**Comment by extesy** [comment]
Good idea, I'll add it in the next release.
