### ISSUE TITLE
Hover Zoom+ activates even when my action key isn't pressed

### ISSUE THREAD

**Issue by Bortseb** [extesy/hoverzoom#55]
I have chosen Ctrl as my action key, but Hover Zoom+ just activates all the time anyways, regardless of the action key being pressed.

**Comment by extesy** [comment]
@Bortseb I've just tried on OS X Yosemite and it works as expected for me. What OS version are you using? Are you sure you've pressed Save button and reloaded the page with images afterwards?

**Comment by Bortseb** [comment]
Chrome Version 49.0.2623.87 m
yes, I am sure I hit save. I have been having this problem off and on for about a week now... I'm not sure if something is resetting itself or what.... everything seems fine now, but it has seemed this way for periods in the past too... Leave this issue open for another few days and ping me if I don't respond back... But if I continue having problems I will log them here.

**Comment by Bortseb** [comment]
The other strange thing that I will note. Even when experiencing the problem... I go to settings to see if the action key has been turned off or changed, but it is still shown as I had it, preserved from the last time I saved.

**Comment by extesy** [comment]
@Bortseb Do you still experience this issue? I wasn't able to reproduce it locally so far.

**Comment by Bortseb** [comment]
Not sure if I can reply to this through email now that it is closed,  but
I'll give it a try.

I have just realized that certain extension settings of mine seem to reset
to default after chrome crashes. I am not a extension dev myself, so would
this explain it? Might it have something to do with settings being saved
locally, in a more fragile way, and are being lost when chrome crashes?

I think this may be at the root of a few different extension problems of
mine, so I would like to get to the bottom of this :P
