### ISSUE TITLE
Let us have the ability to add support for our own websites

### ISSUE THREAD

**Issue by Michael18751** [extesy/hoverzoom#552]
This would be helpful to people that want to add support to their own websites that want too or tweak it the way they want until you update it.

This all would depend on how you write code for it. Could we write custom CSS files for a website or edit the ones you already made? Possibly even have a website dedicated to 3rd party scripts that we could add?

Ask you to port/add support for a website but that could take time.

**Comment by Michael18751** [comment]
If you were to add your own javascript files would that work?

**Comment by extesy** [comment]
@Michael18751 Feel free to send a pull request for any new website. You can look at [recent commits](https://github.com/extesy/hoverzoom/commits/master) for examples and also [existing plugins](https://github.com/extesy/hoverzoom/tree/master/plugins). External plugins (outside of the chrome extension) are currently not supported and there is no plan to add support, unless you want to implement this functionality. But in general I'm open to any contributions.
