### ISSUE TITLE
Activate full zoom not working

### ISSUE THREAD

**Issue by drhouse** [extesy/hoverzoom#570]
**Describe the bug**
The following hotkey in the options menu does not zoom any picture regardless of which key it's mapped.
_"Activate full zoom - When this key is held down, the picture is displayed using all available space. Useful for high resolution pictures only."_

**To Reproduce**
1. Go to https://www.google.com/search?q=lakes
2. Hover over the first lake image
3. Hold hotkey 'Z' down, which is the default mapping for 'Activate full zoom'

**Expected behavior**
Some sort of zoom effect should take place. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome x64
 - Version: 85.0.4183.83

**Comment by GrosPoulet** [comment]
Hi Doctor
That's because in some cases HZ+ does not find any bigger version of picture being hovered.
So it may just display the same picture, this is not an issue with key mapping.
In your Google Images example, zoom works on most lake pictures but not all of them.

**Comment by drhouse** [comment]
Thanks for the reply, but in my case the hotkey 'Z' does nothing to any image... 
the standard hover-zoom feature works and shows the 'full-sized image' over the thumbnail, but I thought the 'Z' key was supposed to further expand the 'full-sized image' to use up as much as the browser screen space as available (while being constrained by ratio).

**Comment by extesy** [comment]
@drhouse Do you have "Extend zoomed images below the mouse cursor" option enabled by any chance? The zoom key is basically a temporary on-demand version of that option.

**Comment by EpochalEngineer** [comment]
I also recall the original HoverZoom to work that way: zoom to all available space, even if there is not a larger source version available.

I would much appreciate a feature to do this, as I often browse on a 4K resolution with much of the source material being small in comparison.

**Comment by drhouse** [comment]
> I also recall the original HoverZoom to work that way: zoom to all available space, even if there is not a larger source version available.
> 
> I would much appreciate a feature to do this, as I often browse on a 4K resolution with much of the source material being small in comparison.

for what it's worth, soon after my last post I discovered Imagus, it does everything the way I want it to work and seem to remember Hoverzoom working, highly recommended:
[chrome store - Imagus](https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab)

**Comment by EpochalEngineer** [comment]
I actually switched from Imagus to HoverZoom+ because Imagus has issues with v.reddit.com.

But yes, I definitely prefer the Imagus behavior other than that.

**Comment by EhsanKia** [comment]
+1 for imagus behavior. fill screen without Z. That being said I'm working on right click locking which imagus has which should partially solve this.

**Comment by Mrfiregem** [comment]
Regarding Imagus' right click functionality, this is how I expected Z to work as well. I'm glad to hear there's work being done to add this feature.

**Comment by EhsanKia** [comment]
I have an initial prototype of the right click behavior if anyone wants to try and give feedback on. Just download zip of latest version [from my repo](https://github.com/EhsanKia/hoverzoom), extract somewhere, then load unpacked into Chrome. Make sure to disable the original extension since you'll have it twice in Chrome. Check options, by default it sets it on L, but you can change it to right click to match imagus behavior. Play around a bit, I tried to get it as close as I could from memory.

@extesy I have an initial PR if you want to take a look and see what your first impression is.
https://github.com/extesy/hoverzoom/pull/746

**Comment by pookymaster** [comment]
Would it be possible to use numpad enter key for the imagus behavior? That's how I always activated it and most convenient for me, reaching it with my mouse hand.

**Comment by pookymaster** [comment]
> 
> 
> I have an initial prototype of the right click behavior if anyone wants to try and give feedback on. Just download zip of latest version [from my repo](https://github.com/EhsanKia/hoverzoom), extract somewhere, then load unpacked into Chrome. Make sure to disable the original extension since you'll have it twice in Chrome. Check options, by default it sets it on L, but you can change it to right click to match imagus behavior. Play around a bit, I tried to get it as close as I could from memory.
> 
> @extesy I have an initial PR if you want to take a look and see what your first impression is. #746

Hi, I've been using this version on Chrome for a few months, and it works great! I migrated to Firefox and I'm really missing this feature. I tried using the zip file to add it through the Firefox "install add-on from file" option, but it says it's corrupt. I'm guessing that's because this was built for Chrome. Is there anyway we can get a Firefox version with this lock feature?

**Comment by extesy** [comment]
While I'm still working on resolving #782, you can manually install the extension using https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/ guide.

**Comment by mustaqimM** [comment]
Has this been resolved? I was looking for Imagus-like zoom functionality, where right clicking locks the image into place and the cursor is able to move around and zoom in and out with scroll. On Firefox, all shortcuts, e.g. `Z` don't work for me

**Comment by rudolphos** [comment]
I changed Lock to Right Click, it works in a similar way to Imagus, but not as good. Zoom is slow and panning doesn't work as smooth as on Imagus. Also pan is only possible if image size exceeds screen size.

**Comment by rudolphos** [comment]
I changed _Lock_ to _Right Click_ and now it works similarly to Imagus, but not as good. Zoom is slow (small zoom percentage per scroll) and panning doesn't work as smooth as on Imagus. Also pan is only possible if image size exceeds screen size.
Imagus for comparison

https://user-images.githubusercontent.com/4366810/210276704-967010f1-e23f-4c97-9c88-3f2b1216ad17.mp4

**Comment by extesy** [comment]
Fixed by https://github.com/extesy/hoverzoom/commit/f0a064a48e2141cd517004a60982f708cdde13cd, will be available in the next release
