### ISSUE TITLE
W, T, S opens and saves de image 8 times

### ISSUE THREAD

**Issue by sbmaza** [extesy/hoverzoom#577]
When using W shortcut it opens the image in 8 windows. When using T shortcut it opens the image in 8 tabs. When using S shortcut it saves the image 8 times.

**Comment by sbmaza** [comment]
It is not doing it anymore.. I guess it was the number of times I changed settings in the extension and hit save?

**Comment by extesy** [comment]
I'm not sure what you did but I can't reproduce this behavior. If you figure out a consistent repro scenario, then please reopen this issue.
