### ISSUE TITLE
Album support is broken

### ISSUE THREAD

**Issue by janpetras** [extesy/hoverzoom#6]
Chrome Version 39.0.2171.99 m
Windows 10 Technical Preview Build 9879

Issue: Going with the Action Keys Left or Right in a imgur.com hosted album, on Reddit, scrolls two photos instead of one.

Example: Album containing 10 photos. Pressing right key on image number 1 takes the user to image number 3. Pressing right key again takes the user to image number 5 and so on.

To reproduce: Install Hover Zoom+, go to Action Keys, select Left/Right as Previous/Next image (even if they are already selected). Press Save. Go on reddit.com. Find an album. Press right. You should now be on image 2, but instead Hover Zoom+ goes straight to image number 3.

**Comment by extesy** [comment]
Just tried with this one: http://www.reddit.com/r/DIY/comments/2tcgp4/triforce_chest_i_made_for_my_girlfriend_to_hold/ - works fine for me, scrolls one image at a time. I'm using Chrome 41, Windows 7.
