### ISSUE TITLE
Feature request: Show timestamp/video length for videos

### ISSUE THREAD

**Issue by fxjkhr** [extesy/hoverzoom#60]

**Comment by MrFrancy** [comment]
This would be perfect ![example](https://cloud.githubusercontent.com/assets/1372764/16174149/757df098-35b6-11e6-82df-e9cab05723bc.png)

**Comment by itpun** [comment]
![image](https://cloud.githubusercontent.com/assets/6364887/16178538/25c2da38-3619-11e6-9dbf-2687365c2b10.png)

would something like this work?

**Comment by MrFrancy** [comment]
A text overlay already exists for albums, so it shouldn't be difficult to make this enhancement.
The code is like [this](http://stackoverflow.com/questions/14491392/countdown-to-the-end-of-the-html5-video)

**Comment by extesy** [comment]
Fixed in 69822e7ebed5b57bedd855cabd1ce9d1ba735159
