### ISSUE TITLE
No more working on Furaffinity

### ISSUE THREAD

**Issue by ShamanWolffire** [extesy/hoverzoom#618]
### Description of the problem
Add-on no more working on Chrome/Firefox on the website Furaffinity

### Url of the page where the problem occurs (not the image url)
https://furaffinity.net

### Steps to reproduce the problem (include image url here)
Every single image-hovering with the mouse over it does nothing.
A few days/weeks ago it went without problems.

**Comment by ShamanWolffire** [comment]
Sorry, this is my first time here.
"update existing plugin"
Does this mean that I don't have the latest version and should run an update?
If I do that I won't get a new version and the bug is still there.
I have version 1.0.156 of the plugin in Chrome 85.

**Comment by extesy** [comment]
@ShamanWolffire This is an internal classification for the ticket so that the developers can differentiate it from all other types of problems and requests.

**Comment by onometre** [comment]
This seems to be working now. I guess Furaffinity fixed whatever got changed on their end during the server move a few weeks ago.
