### ISSUE TITLE
Blacklisting certain websites

### ISSUE THREAD

**Issue by Fastjur** [extesy/hoverzoom#63]
I would like the ability to disable certain websites from showing up.  
Note the difference between the current blacklist (which disables hoverzoom completely on certain websites), I'd like to blacklist certain websites from showing (aka, blacklisting youtube.com would disable ALL video's hosted on youtube.com being shown, on EVERY website).

As mentioned in a issue #49, [(specific comment)](https://github.com/extesy/hoverzoom/issues/49#issuecomment-205561388) one possibility for this would be to disable certain plugins.

I hope I'm making some sense here

**Comment by dmahr1** [comment]
This would be fantastic! I just tracked down this repo to request this exact feature. Maybe call this "host blacklist" to contrast it with the existing "site blacklist"? 

@extesy I would be happy to contribute to Paypal or a charity of choice if it would make this happen sooner.
