### ISSUE TITLE
Pixiv.net - Saving with shortcut does not work

### ISSUE THREAD

**Issue by Autistic-Unicorn** [extesy/hoverzoom#633]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Saving image when in hover mode is not working, outputs 
`Access to fetch at 'https://i.pximg.net/(link to image there).jpg' from origin 'https://www.pixiv.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

## Url of the page where the problem occurs (not the image url)
pixiv.net

## Steps to reproduce the problem (include image url here)
1.Hover over image
2.Load the image in Hover zoom mode
3.Try to save image with "S" shortcut

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10, 1.0.158

**Comment by Autistic-Unicorn** [comment]
It is possible to make saving with shortcut to work with this addon: https://mybrowseraddon.com/access-control-allow-origin.html
Sadly i don't know anything in-deep of that issue so i just hope i can help with giving a good path to fixing the issue.

**Comment by extesy** [comment]
Fixed in bdbc9f4d6c570c2106d739c99f37b6bb72fcd307, will be available in the next release.

**Comment by extesy** [comment]
Still not fixed because of pixiv's referrer check.

**Comment by extesy** [comment]
Fixed in https://github.com/extesy/hoverzoom/commit/130ae06d83ab2ff28cbe579979862cc0666b26c5, will be available in the next release.
