### ISSUE TITLE
Cannot save images from i.redd.it

### ISSUE THREAD

**Issue by harislapo** [extesy/hoverzoom#634]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
I'm unable to download zoomed images from reddit which are hosted on i.redd.it. I use download hotkey which is letter S. Worked fine until last month. I'm able however to download images on reddit that are hosted somewhere else, for example on imgur.com.

## Url of the page where the problem occurs (not the image url)
www.reddit.com

## Steps to reproduce the problem (include image url here)
1. Go to any reddit image.
2. Hover over it.
3. Press download hotkey.

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10, 1.0.158

**Comment by robo042** [comment]
exact same issue with version 1.0.158 of this extension on Linux:

$ lsb_release -a ; google-chrome --version ;
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
Google Chrome 87.0.4280.66

**Comment by k1ngisamu** [comment]
chrome version: 87.0.4280.88
hover zoom + version: 1.0.158
same issue, impossibility to save pics or videos from reddit domain.
thanks for your hard work @extesy

**Comment by lingyuk** [comment]
Same
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by extesy** [comment]
I am aware of the problem. This is related to a security policy of reddit (see more detailed explanation in #633). Not sure how to deal with it yet.

**Comment by lingyuk** [comment]
Ok cool, thanks for giving us that update.

**Comment by extesy** [comment]
Fixed in bdbc9f4d6c570c2106d739c99f37b6bb72fcd307, will be available in the next release.

**Comment by extesy** [comment]
Reopening since this change got reverted by 3ae20267291b1c34c5f46ed8acdc1eb697a4e268.

**Comment by extesy** [comment]
Can someone please test drive the fix in 28362bf48b10877814d45cb4ef1aa34d0d28ff76 before I submit it to chrome web store?

**Comment by fhadiel** [comment]
> Can someone please test drive the fix in [28362bf](https://github.com/extesy/hoverzoom/commit/28362bf48b10877814d45cb4ef1aa34d0d28ff76) before I submit it to chrome web store?

It works for Reddit. but I got forbidden when trying with Pixiv

**Comment by extesy** [comment]
Ok, so the difference with pixiv is that it is requiring a `referrer` header to match the pixiv.ent domain and it is impossible to set this header from an extension (disallowed by XMLHttpRequest rules).
