### ISSUE TITLE
Audio for Hoverzoome'd video will play in background even after video closes - Version 1.0.159

### ISSUE THREAD

**Issue by HeroRyan** [extesy/hoverzoom#638]
**Describe the bug**
For some reason, intermittently, audio from a video will start playing in the background even when hoverzoom is not focused on the video. This audio will continue on a loop, and the only way to get it to stop is to refresh the tab. This started happening in Version 1.0.159. Currently happens very frequently when browsing Reddit on Google Chrome with the Hover Zoom+ extension enabled.

**Comment by extesy** [comment]
@GrosPoulet Could some of your recent commits cause this?

**Comment by GrosPoulet** [comment]
i don't know, did you reproduce this issue?

Le mar. 22 déc. 2020 à 18:30, Oleg Anashkin <notifications@github.com> a
écrit :

**Comment by extesy** [comment]
Nope, not yet. @HeroRyan Please follow a bug template and specify exactly which pages cause it and how to reproduce.

**Comment by HeroRyan** [comment]
@extesy Unfortunately, I have been unable to reliably replicate this bug. It seems to happen intermittently when browsing Reddit on Google Chrome using the HoverZoom+ Extension, assuming there is a video somewhere on the page. What's weird is it will start playing the audio from a thread on the page which was not even previously interacted with. It will continue to play on a loop in the background even when you focus on another image or video. If you focus on another video then it will overlay both of the video's audio's over one another. 

Wish I had the ability to reproduce it, but it seems to happen somewhat randomly.

**Comment by extesy** [comment]
So far I haven't seen this myself and there's no confirmation from other users. I browse reddit regularly so I'll keep an eye on this potential problem.

**Comment by FranchiseRoR** [comment]
I've noticed this happen a few times, it usually occurs when a video is taking a bit to load and you decide to stop waiting for it and move on but it still loads in the background. Or you scroll over a video link quickly and the video loads quickly, but since you've already moved to the next image or video it'll load in the background.
