### ISSUE TITLE
The loading animation is in green color now, it was white-grey before the last update

### ISSUE THREAD

**Issue by danid12** [extesy/hoverzoom#639]
I find it very irritating and noticable every time I hover over an image. Please let option to use it in the colors it was before.

**Comment by extesy** [comment]
@GrosPoulet This was changed in 66b3ebc4cfb2ba430df280449e6a15c9ff4d42e4 - can you please restore the colors? I also think that these colors are too bright. Maybe lower the saturation by 70-80%?

**Comment by GrosPoulet** [comment]
ok, i'll choose another colors scheme and submit for review next week


Le sam. 26 déc. 2020 à 18:32, Oleg Anashkin <notifications@github.com> a
écrit :

**Comment by extesy** [comment]
Fixed by 006207c239331fc0a6ca38c34b86ee0559384dba
