### ISSUE TITLE
Twitter Images Saves as Text after latest update

### ISSUE THREAD

**Issue by maddyvoldy** [extesy/hoverzoom#644]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Twitter images are saving as text file, when you press the hotkey to save. This is specific to twitter, as the functionality is working fine in other websites.

## Url of the page where the problem occurs (not the image url)
https://twitter.com/CinemaClown/status/1343222208294920192

## Steps to reproduce the problem (include image url here)
1. Hover on any twitter image.
2. Press the hotkey to save.
3. It saves as txt file.

## OS version, extension version (Chrome only, Firefox is not supported)
OS: Win 10 Pro 1909, Extension: 1.0.160

**Comment by extesy** [comment]
Should be fixed by 3ae20267291b1c34c5f46ed8acdc1eb697a4e268 in the next version - 1.0.161.
