### ISSUE TITLE
Reddit images download breaking the pic

### ISSUE THREAD

**Issue by k1ngisamu** [extesy/hoverzoom#645]
## Description of the problem

when i hover over a picture in reddit from reddit domain when i press S to download that pic, the file can not be opened.

## Url of the page where the problem occurs (not the image url)

reddit.com

## Steps to reproduce the problem (include image url here)
1. open reddit
2. hover over a image hosted on reddit domain
3. press S to download pic, pic cannot be opened

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 1904 
extension ver: 1.0.160
chrome ver:  87.0.4280.88

**Comment by onometre** [comment]
Same issue on Furaffinity

**Comment by extesy** [comment]
@fhadiel Seems like it was broken by your #641 change. Did you test it?

**Comment by extesy** [comment]
I've reverted that change so now we're back to situation described in #634.

**Comment by fhadiel** [comment]
I can't download pic on version 159, but I can with version 160.
Are we testing on the new reddit or old reddit?
Tested on Chromium 87

**Comment by extesy** [comment]
I'm personally using old reddit. But no-cors policy was breaking many sites, that's why I reverted it. I'm going to test an official chrome api instead of a blob hack.
