### ISSUE TITLE
Not remembering the last download location

### ISSUE THREAD

**Issue by maddyvoldy** [extesy/hoverzoom#646]
**Describe the bug**
When you save, it is not remembering the last downloaded folder location on chrome.

**To Reproduce**
1. Hover on any image.
2. Press hotkey to save and select any non default folder to save.
3. Hover on another image.
4. Press hotkey to save again
5. It reverts back to default download folder.

**Expected behavior**
It should show the last downloaded folder location like it used to.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 87.0.4280.88
 - Extension: Version 1.0.162

**Comment by extesy** [comment]
@maddyvoldy Open your Chrome settings, click on "advanced", scroll to "downloads" and change your settings there.

**Comment by maddyvoldy** [comment]
> @maddyvoldy Open your Chrome settings, click on "advanced", scroll to "downloads" and change your settings there.

I don't think this is related to browser settings, as the setting is working fine in normal saving of the picture, like, right clicking and 'save image as', manually, is remembering last download location.

It is only via HoverZoom extension that pressing hotkey to save image takes to default download folder instead. Even in hoverzoom, it was working fine till couple of days ago, until suddenly this behavior changed.

**Comment by extesy** [comment]
I don't know what the problem might be but the extension cannot choose or control the folder for downloaded files, it's for the browser to decide.
