### ISSUE TITLE
Feature request: Allow arrow keys rewind/fast forward function when HoverZooming YouTube videos

### ISSUE THREAD

**Issue by germaloney11** [extesy/hoverzoom#65]

**Comment by Superluigi6** [comment]
I'd love this!

**Comment by germaloney11** [comment]
Hi, thanks for adding this feature. Would it be possible to change the skip to 5 seconds either way please?

**Comment by extesy** [comment]
@germaloney11 You can change it to 5 seconds in options.

**Comment by germaloney11** [comment]
Just saw it there. Thanks for your help! :)
