### ISSUE TITLE
Subreddit flairs hiding/showing when hovering over posts

### ISSUE THREAD

**Issue by dzienskaj** [extesy/hoverzoom#659]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
When hovering over links with flairs on reddit, flairs show and hide causing website to "jump". Gif with issue https://i.fiery.me/nidPm.gif. When addon is disabled problem doesn't occur

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/r/formula1/

## Steps to reproduce the problem (include image url here)
1. go to subreddit with flairs, eg. formula1
2. hover over link with flair
3. flairs hide when hovering on links and show again when hovering off

## OS version, extension version (Chrome only, Firefox is not supported)
1.0.163

**Comment by GrosPoulet** [comment]
Hi @dzienskaj 
I did not manage to reproduce this issue: the helmet image is displayed fullsize and does not hide until i hover out of the link.
Do you experience this issue on others links ?

**Comment by dzienskaj** [comment]
> Hi @dzienskaj
> I did not manage to reproduce this issue: the helmet image is displayed fullsize and does not hide until i hover out of the link.
> Do you experience this issue on others links ?

Hey, image loading is not a problem here, addon itself works great, but it's causing small "art" flair near title that im hovering to hide/show all the time, causing page to jump around and because of that it's harder to hover over links

**Comment by dzienskaj** [comment]
From what i've noticed, when I hover on the link flairs hide (all flairs on given page), and when i hover off they show again, also when you fast move over a link so that hoverzoom modal doesn't appear, they hide until you hover on link again.

**Comment by extesy** [comment]
Yes, I've seen this happening. I personally only use "old" reddit so maybe it's related to the old reddit design?

**Comment by dzienskaj** [comment]
@extesy i only use old reddit aswell, never checked it on new design

**Comment by extesy** [comment]
@GrosPoulet FYI, this can be reproduced on reddit (https://www.reddit.com/r/formula1/ is an easy example) under two conditions: 1) old reddit design, 2) "use subreddit style" is on. This is caused by `removeTitles`/`restoreTitles` functions in `hoverzoom.js`, but I haven't yet checked if that is truly necessary to do and if there are any workarounds.

**Comment by extesy** [comment]
I've commented out the call to `removeTitles()` and current test-driving the results. I haven't yet seen any rogue tooltips popping up.

**Comment by extesy** [comment]
Ok, I found that not hiding captions causes problems with https://imdb.com so I guess I'll have to make this an option then.

**Comment by dzienskaj** [comment]
@extesy Thank you guys for fixing this issue!
