### ISSUE TITLE
Some redgifs links work and some only display an image instead of the gif

### ISSUE THREAD

**Issue by manuman888** [extesy/hoverzoom#674]
For some reason on https://old.reddit.com/r/porninfifteenseconds/ only some of the redgifs.com links seem to work properly while others will only show an image or thumbnail of the gif. Refreshing does not seem to fix it, but what is very odd is that other links seem to work normally as they should.

The same goes for https://reddit.com/r/porninfifteensecconds

This also seems to happen a lot on other subreddits with gfycat links as well. Again, some work, some don't

**Comment by extesy** [comment]
I've updated redgifs plugin but regarding videos not automatically playing, it seems related to the latest Chrome release which now occasionally prevents videos from being played unless you interact with something on the page. Try clicking anywhere and then hovering over the image.

**Comment by brahmamudi-serial-today-episode** [comment]
I've updated redgifs plugin but regarding[ videos](https://github.com/sandeepdg/birthday-wishes-in-marathi) not automatically playing, it seems related to the latest Chrome release which now occasionally prevents videos from being played unless you interact with something on the page. Try clicking anywhere and then hovering over the image.
