### ISSUE TITLE
Option to export/import settings

### ISSUE THREAD

**Issue by ibLeDy** [extesy/hoverzoom#687]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I reinstall my OS or reinstall my browser, and I have to configure the settings manually each time.

**Describe the solution you'd like**
Buttons to be able to export and import all the settings.

**Comment by merlin555** [comment]
Hi,

Please build a function to save the settings.
Thank you !

Make so on.
Very good addon!

Greetings..

Merlin

**Comment by subsubsubsubsubsub** [comment]
The feature from 2021 has not been added

**Comment by extesy** [comment]
https://github.com/extesy/hoverzoom/commit/6988beeb48ffde1d1f81a3efb1ef52eca5007cfd adds import/export functionality, will be available in the next release.
