### ISSUE TITLE
HoverzZoom+ and Chrome - Autocloses zoomed videos when opened in new window

### ISSUE THREAD

**Issue by FranchiseRoR** [extesy/hoverzoom#693]
**Describe the bug**
Zoomed videos in Chrome will open in new window but close almost immediately. 

**To Reproduce**
Go to reddit.com
Find any video
Hover over video
Allow video to load
Press 'w' to open video in new tab
Video will open in a new tab, but closes almost immediately. 

**Expected behavior**
Window should remain open like it does with images

**Screenshots**
![hoverzoom_video](https://user-images.githubusercontent.com/36144491/108636537-e8b1b500-7453-11eb-9717-49827ef82e4e.png) 
Video opens in new window, like above, then immediately closes

**Desktop (please complete the following information):**
Windows 10
HoverZoom+ v1.0.169
Chrome v88.0.4324.182

**Additional context**
Video will open and play if opened in a new tab (pressing HoverZoom+ hotkey "t").

**Comment by extesy** [comment]
That is probably Chrome's automated popup ad blocker triggering as a false positive.

**Comment by FranchiseRoR** [comment]
I tried disabling all other extensions and Chrome's pop-up blocker. Still videos/gifs will auto close. Images display in new window just fine.

**Comment by FranchiseRoR** [comment]
Playing around with [Hover Zoom Gold](https://github.com/superlime/hoverzoomgold/) v1.0.158, which seems to be following updates for Hover Zoom +. That version there pops out videos just fine and doesn't instant close.

**Comment by extesy** [comment]
I've just tried and it does not auto-close for me. The new window gets opened and the video stays there. Can anyone reproduce? If not then I'll close this issue.

**Comment by szary1** [comment]
Fack off me


czw., 12 sie 2021, 06:47 użytkownik Oleg Anashkin ***@***.***>
napisał:
