### ISSUE TITLE
[Feature] Allow domain "force"

### ISSUE THREAD

**Issue by stuntguy3000** [extesy/hoverzoom#70]
Example domain: https://i.reddituploads.com/ad85b1eb338a4d418c63c513a9223922?fit=max&h=1536&w=1536&s=42ff47e38eb147f0e14dfed92ae6a927.png

HoverZoom doesn't pick it up as an image, but you know, it is. A way to add domains which will be treated as images would be nice :)

**Comment by extesy** [comment]
@stuntguy3000 HoverZoom already works this way. Your specific image is not loading because of permissions issue - server returns "unauthorized request". Otherwise, you'd see a preview from HoverZoom.

**Comment by stuntguy3000** [comment]
Weird, thanks.

**Comment by extesy** [comment]
reddituploads support was added in 608f3fd
