### ISSUE TITLE
Distribute for Safari 14

### ISSUE THREAD

**Issue by eramdam** [extesy/hoverzoom#704]
Safari 14 on macOS now supports the WebExtensions API and I think HoverZoom+ could benefit from being distributed for it.

As an experiment, I tried running [Apple's conversion tool](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) on the repo and it seems to work just like it does on Firefox/Chrome 😄 

![Screen Shot 2021-03-19 at 10 34 31 PM](https://user-images.githubusercontent.com/1409924/111860226-707bc980-8903-11eb-810b-95cc465aaf90.png)

**Comment by GrosPoulet** [comment]
Excellent suggestion @eramdam, i was not aware of this handy conversion tool.
@extesy: what do you think?

**Comment by extesy** [comment]
I would love to, but according to [Safari Web Extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions) page "you must be a member of the Apple Developer Program to distribute them through the App Store" and that costs $99/year which I don't want to pay. Without App Store distribution I really doubt enough potential users would go through a trouble of manual installs to be worth the effort.

**Comment by eramdam** [comment]
@extesy you could still distribute a signed .app bundle. It's not ideal but at least you wouldn't need to go through the App Store process 🤷

**Comment by extesy** [comment]
To sign a bundle such that it would work for other people (not just myself) would still require a developer certificate. And distributing an unsigned extension though github would limit a potential audience to a few people at most. In the several years that I have maintained this extension, you're the very first person to ask about this. In Apple's world, you either distribute your product through AppStore or you essentially don't exist. So with all due respect, but unless there's a big enough demand or there's a way to distribute it from AppStore for free, I would prefer to not spend my personal time on this.

**Comment by eramdam** [comment]
> To sign a bundle such that it would work for other people (not just myself) would still require a developer certificate. And distributing an unsigned extension though github would limit a potential audience to a few people at most. In the several years that I have maintained this extension, you're the very first person to ask about this. In Apple's world, you either distribute your product through AppStore or you essentially don't exist. So with all due respect, but unless there's a big enough demand or there's a way to distribute it via AppStore for free, I would prefer to not spend my personal time on this.

Fair enough 😁 I forgot that the certificate required the subscription since I had to do it to distribute [BetterTweetDeck](https://github.com/eramdam/bettertweetdeck) for Safari 😅. If you ever revisit this, I'd be happy to help!
