### ISSUE TITLE
HoverZoom freezes webpage on aws.amazon.com/elasticmapreduce

### ISSUE THREAD

**Issue by martimlobao** [extesy/hoverzoom#715]
**Describe the bug**
This is highly specific but easy to reproduce. The entire tab freezes when attempting to clone a cluster on AWS ElasticMapReduce.

**To Reproduce**
1. Go to console.aws.amazon.com/elasticmapreduce/home and sign in.
2. Select an existing cluster to clone (assumes a cluster already exists).
3. Click "Clone" at the top of the page.
4. Entire tab will freeze and lock up.

**Expected behavior**
Tab should continue working normally.

**Screenshots**
Page below is completely frozen, hitting the back button or even pressing CMD+W does nothing.
<img width="1275" alt="Screen Shot 2021-04-14 at 16 03 18" src="https://user-images.githubusercontent.com/6430786/114734161-e2e19d00-9d3b-11eb-8cbd-57076b5a69d5.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome 89.0.4389.114
 - Version: 1.0.173

**Additional context**
Adding `aws.amazon.com` to the blacklist of websites fully resolves the issue. Given the specificity of this bug, I'd be happy to provide any additional context or help in finding the root cause of the issue.

**Comment by GrosPoulet** [comment]
Hi @martimlobao 
I'm not familiar with AWS so i did not manage to create & clone a cluster, sorry.

**Comment by martimlobao** [comment]
@GrosPoulet Are there any logs I could send that would help in debugging? Also available for a quick call/screenshare to try to work through the issue if that helps.

**Comment by joeythomaschaske** [comment]
Basically anywhere in the AWS console freezes when hoverzoom is enabled.

**Comment by GrosPoulet** [comment]
@martimlobao I added a new discussion topic on debugging: #721 
Maybe you can enable debug mode and tell us what you see in the console, it might help.

**Comment by martimlobao** [comment]
@GrosPoulet Here's the log, there aren't any obvious errors but hopefully it will be helpful. I think the issue seems to be with some sort of timeout: the page ends up loading after a while, but it's unresponsive for at least 30 seconds. Let me know if you need more specific details.

[us-west-2.console.aws.amazon.com-1619370731492.log](https://github.com/extesy/hoverzoom/files/6372520/us-west-2.console.aws.amazon.com-1619370731492.log)

**Comment by GrosPoulet** [comment]
hoverzoom.js:25 prepareImgLinks: **54171.10009765625** ms
Holy Cow! This function should take approx. 54ms, not 1000x longer.
That's probably an issue with the **aws_a.js** plug-in, if you are confortable with JS you can debug or add traces in this plug-in. 
I'll try to check it next week.

**Comment by lakario** [comment]
Just wanted to added that HoverZoom also causes the "new" VPC home page on AWS to freeze. Disabling/whitelisting immediately restores normal performance. 

Maybe this is a bit easier for repro purposes.

https://us-west-2.console.aws.amazon.com/vpc/home

**Comment by GrosPoulet** [comment]
Thank you @lakario for your suggestion, it allowed me to reproduce & solve the issue (see #727 for details).
Fix should be available in next release of HZ+ (1.0.174).

**Comment by martimlobao** [comment]
Fixed with #727 and released in [release 1.0.174](https://github.com/extesy/hoverzoom/releases/tag/1.0.174).
