### ISSUE TITLE
Feature Request: Color picker for frame

### ISSUE THREAD

**Issue by STaRDoGG** [extesy/hoverzoom#72]
Small req to add an option to select the color of the frame around the popup that shows the image/video. Currently it's white; I'd love to be able to tweak it to match my browser theme(s).

**Comment by stuntguy3000** [comment]
Agreed, would be good for things like "night modes"

**Comment by itpun** [comment]
I currently have a pull request that will allow you to have a Dark Mode setting. It is totally possible to do custom border colors, but I would like your opinion on having set color themes or to pick from a RBG color wheel.

**Comment by extesy** [comment]
@itpun I prefer generic (not one-off) solutions, and ability to choose custom color (with default value #fff) satisfies both this request and a request for a dark theme. But don't forget that the text color should be chosen automatically to appear good on any random backgound color.

**Comment by extesy** [comment]
Implemented in 1.0.124
