### ISSUE TITLE
Hotkey No reaction

### ISSUE THREAD

**Issue by sb2941** [extesy/hoverzoom#724]
Hotkey works on Google ands YouTube.

It also works well with Gmail.

However, Hover Zoom Hotkey cannot be used on most other sites.

The rest of Pixiv, Instagram, Facebook, Tumblr, Art Station, Deviant Art, Amazon, etc.~ Hotkey does not respond.

X, W, T, S, Z~... No matter how much I press it, there is no response.

Most of the zoom features of Hover Zoom work just fine. But, since then, all Hotkey except Google and YouTube have not responded.

Windows 10 Pro 64bit 20H2 19042.928
Microsoft Edge Version 90.0.818.46 (Official Build) (64-bit)
Chrome Extension Hover Zoom + 1.0.173
ID pccckmaobkjjboncdfnnofkonhgpceea
Microsoft Edge Add-on Hover Zoom + 1.0.173
ID bnibclmindjpdfiipicpdhljfblkpkml

Both versions have the same problem.

**Comment by extesy** [comment]
I admit that I didn't do sufficient testing on Edge and assumed that since it uses the same extension format and the same browser engine (Chromium) then everything will just work. And most of functionality does work, except for this bug. I'll try to figure out what's going on with Edge.

**Comment by sb2941** [comment]
It was like this from 3 days ago.

I don't know about coding or programming. It is a very light user who finds and uses extensions. I was wondering if I could ask a question here.

I just found out where to find the question form. Next time, I'll fit the form. Peace! 🤘 ^^

**Comment by sb2941** [comment]
I don't know why, but it seems to be due to an extension crash.

https://chrome.google.com/webstore/detail/drag-freemouse-drag-mouse/cnfngpgfjllafbghaimjcmailafcdhod

드래그프리(마우스 드래그 & 마우스 우클릭 해제)

Disabling this makes the shortcuts react properly. Oh yeah!!!!
