### ISSUE TITLE
[Feature] Debug mode trigger

### ISSUE THREAD

**Issue by Higurashi-kagome** [extesy/hoverzoom#726]
**Is your feature request related to a problem? Please describe.**

It might be a good idea to add a debug trigger on the options page. [How to debug HZ+ (Chrome tutorial) · Discussion #721](https://github.com/extesy/hoverzoom/discussions/721) provided a tutorial but it's not that convenient actually.

**Describe the solution you'd like**

Add the 'Debug mode' on the 'advance' tab of the options page:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/116644973-5b389700-a9a7-11eb-8554-5542b8521513.png)

</details>

**Describe alternatives you've considered**

Open the debug mode by default might be also helpful.

**Comment by GrosPoulet** [comment]
Debug mode option added by #792
