### ISSUE TITLE
Feature request: Disable image titles when viewing image

### ISSUE THREAD

**Issue by leoleosuper** [extesy/hoverzoom#731]
**Is your feature request related to a problem? Please describe.**
When trying to view images, if the image has a title attribute, this will show up blocking some of the image.

**Describe the solution you'd like**
Either disabling the title attribute showing on hover, or make the image appear in front.

**Additional context**
![Help](https://user-images.githubusercontent.com/77450407/118057113-2dfdc880-b359-11eb-8a93-e75468666ff9.png)
The image title (added from inspect element) appears over the image. Is there anyway to disable this either browser wide, or with Hover Zoom?

**Comment by extesy** [comment]
@leoleosuper What is the page url where this happens? I am unable to reproduce it.

**Comment by leoleosuper** [comment]
I have it happen randomly around the web. For the example I put, I got the image from https://www.searchenginejournal.com/image-alt-text-vs-title-vs-file-names/259441/, and used inspect element to add title="annoying" to the img section. Any image that allows HoverZoom and has a title attribute in img has this issue.

**Comment by leoleosuper** [comment]
Through searching I found one site that reproduces it: e926.net. It's an image site, and all images have a title used to show what tags are applied to the images.

**Comment by leoleosuper** [comment]
I believe the cause is an <img> has a title attribute while also linking to an image, thus HoverZoom activates on the link while Google activates on the <img>. Disable title attributes if it also has a link and HoverZoom is on?

**Comment by extesy** [comment]
HoverZoom does in fact remove title attributes before showing the image (https://github.com/extesy/hoverzoom/blob/master/js/hoverzoom.js#L446) but apparently in some rare cases this doesn't work. I'll investigate when I have time.

**Comment by Mattwmaster58** [comment]
Looks like this issue is caused because the code is expecting the title attribute to occur in a parent element of the image element, if at all, but when this isn't the case (ie the img element itself has a title) this fails.
