### ISSUE TITLE
Shortcuts suddenly don't work anymore, out of nowhere

### ISSUE THREAD

**Issue by LinnenMinus** [extesy/hoverzoom#732]
**Describe the bug**
I've tried the shortcuts in Firefox today and they stopped working, images aren't saving with "S"

**To Reproduce**
1. Go to 'Google images'
2. Hover Image
3. Press "S" as shortcut

**Expected behavior**
Saves image

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 88.0.1 (64bit)
 
**Additional context**
It worked today earlier, but now It doesn't?

**Comment by LinnenMinus** [comment]
Works fine in Chrome

**Comment by extesy** [comment]
@LinnenMinus Thanks for the report. In the meantime you can use T shortcut to open the image in a new tab and then save it from there with Ctrl+S.

**Comment by LinnenMinus** [comment]
@extesy Will do 🙏 Notify when It's fixed

**Comment by dedudo** [comment]
I have tha same problem after a Firefox update.

**Comment by extesy** [comment]
Fixed in 67166b3703b3d7d55b94b883103995f8220a9fd2
