### ISSUE TITLE
Scrolling while hovering over a GFY just skips around the video; I would like it to scroll the page

### ISSUE THREAD

**Issue by jonluca** [extesy/hoverzoom#74]
If you're scrolling while hovering over a GFY link (such as in [this link](https://www.reddit.com/r/woahdude/comments/4g8hos/the_power_of_the_sun/))

It'll just skip around the GIFV (even though it's only like 10 seconds long so there's only 2 possible skip locations)

I'd like it to just scroll through the page. In the options there's number for how many seconds to skip forward/backward but no way to actually disable it

Thanks!

**Comment by extesy** [comment]
@jonluca you can disable it by unselecting option "use mousewheel to navigate albums".

**Comment by jonluca** [comment]
Is it possible to make this into two options? I want to still be able to scroll through an album of pictures, while also being able to scroll past GIFV/GFY links

**Comment by SauerKraus** [comment]
Yeah, I'm having the same problem, it never used to do this before. Really frustrating, I'm just using Imagus instead...

**Comment by extesy** [comment]
Unfortunately with 230+ thousands users it's impossible to please everybody. Sometimes people even have contradicting requirements. Just remember that this is a free product which I maintain in my own spare time. Feel free to use anything else if that suits your needs better.

**Comment by jonluca** [comment]
Hey Extesy!

I just made a pull request to add that functionality. I wrote it in today.

However, the one thing I did not do was add localization. I don't speak those languages so I don't know what's correct, so I left it in english for now. Can you do it or have whoever does localization do it?

Thanks!

JonLuca

**Comment by jonluca** [comment]
Update has been merged. Feel free to mark this as closed.

Thanks!
