### ISSUE TITLE
Add support for : MyAnimeList

### ISSUE THREAD

**Issue by prestidigitonium** [extesy/hoverzoom#744]
**What is the URL of the website**
https://myanimelist.net

**Why we should add support for the website?**
MyAnimeList is very popular and it has anime/manga posters very small (example of list: https://myanimelist.net/anime/season)

**Comment by GrosPoulet** [comment]
Hi @prestidigitonium 
Plug-in for : MyAnimeList.net will be available in next HZ+ release (1.0.176)
