### ISSUE TITLE
HoverZoom behaves differently on Firefox & Chrome

### ISSUE THREAD

**Issue by kenethc** [extesy/hoverzoom#747]
HoverZoom behaves differently on Firefox & Chrome
I find it works better in Firefox than in Chrome

Take link: shorturl.at/ltFIO for example.

HoverZoom is enabled on this site on Chrome but not in Firefox.
It behaves correctly on Firefox.

**Comment by extesy** [comment]
Please use a proper issue template. There isn't enough information to diagnose the problem.
