### ISSUE TITLE
Add copy to clipboard hotkey

### ISSUE THREAD

**Issue by kazimirr** [extesy/hoverzoom#750]
There's a hotkey for saving images quickly. It would be nice to have another hotkey to quickly copy an image to the clipboard.

Use case:
I have a group chat with my friends in Telegram. We often share pictures with each other. With such hotkey sharing would be quicker.

**Comment by extesy** [comment]
Fixed by https://github.com/extesy/hoverzoom/commit/9bf7dd42720e16b125549fa80e24ebe207fd2f1b
