### ISSUE TITLE
Zoomed videos from v.redd.it don't play sound

### ISSUE THREAD

**Issue by S-Aggarwal** [extesy/hoverzoom#756]
**Describe the bug**
No sound on zoomed videos from v.redd.it

**To Reproduce**
1. Go to 'reddit.com/r/all'
2. Hover over a video post with sound hosted on v.redd.it.
3. Notice no sound is played.

**Expected behavior**
Video should play with sound.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.164

**Additional context**
Checked settings, I don't have the mute setting on.

**Comment by deludedshai** [comment]
Same problem but on win10.

**Comment by rakeshdas1** [comment]
Same problem here as well, I am running Chrome on Windows 10 as well as Arch Linux. 
I have attempted to toggle all the settings that are related to video playback, but nothing brings the sound back.

The problem seemed to have cropped up after the last update, I suspect the new image/video viewer has something to do with the issue.

**Comment by Veneticus1** [comment]
Same problem here, audio is broken.

**Comment by steffenbk** [comment]
same issue, only on reddit though. No sound from zoomed videos

**Comment by GrosPoulet** [comment]
@rakeshdas1 is right, i introduced this issue with the new image /video viewer :flushed:
I committed a fix (#757), it'll be available in next release of HZ+ (1.0.177).

**Comment by rakeshdas1** [comment]
Thanks for the quick fix @GrosPoulet :)

**Comment by Veneticus1** [comment]
Thank you, it works now!
