### ISSUE TITLE
v.redd.it videos no audio on hover

### ISSUE THREAD

**Issue by k1ngisamu** [extesy/hoverzoom#758]
Reddit videos no audio on hover (v.redd.it)

reddit.com (v.redd.it)

1. go to reddit
2. hover over a v.redd.it link
3. no audio plays on hover

windows 10, hoverzoom 1.0.176 , chrome 92.0.4515.107 (64 bits)

**Comment by gody93** [comment]
They fixed it and it will be added on 1.0.177

https://github.com/extesy/hoverzoom/issues/756

**Comment by Ikbenik5** [comment]
@gody93 Hi, when will the 1.0.177 update be available?

**Comment by extesy** [comment]
Closing as a duplicate of #756

**Comment by extesy** [comment]
The new version will be available as soon as Google approves it and distributes to your browsers.
