### ISSUE TITLE
"Save" Hotkey Action

### ISSUE THREAD

**Issue by WoolyMammouth** [extesy/hoverzoom#770]
When I try to save an image or a video, I always end up w/ like 5 identical files. Maybe put a timer after each action so that you can't save it in duplicates. If anyone can help me, though, I'd love some help.

**Comment by extesy** [comment]
@WoolyMammouth Can you please use the original issue template and provide details to reproduce your problem?

**Comment by SirGer** [comment]
Sometimes happens to me, but with 3x rather than 5x

**Comment by WoolyMammouth** [comment]
I finally was able to make it work, I just didn't refresh the page after changing the settings and saving

**Comment by extesy** [comment]
Thanks for confirming, @WoolyMammouth!

**Comment by SirGer** [comment]
Great - thanks, everyone!
    On Tuesday, September 14, 2021, 10:31:18 PM EDT, Oleg Anashkin ***@***.***> wrote:  
 
 


Closed #770.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
