### ISSUE TITLE
May be a long way down the road, but any plan for Firefox support?

### ISSUE THREAD

**Issue by cormacltighe** [extesy/hoverzoom#80]
I want to be able to run this on firefox as well as chrome. Firefox has no good equivalents.

**Comment by extesy** [comment]
No near future plans. You can try https://addons.mozilla.org/en-US/firefox/addon/imagus/ on firefox.

**Comment by Mo2000** [comment]
Here's another option https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/

**Comment by Mte90** [comment]
Ref #273

**Comment by extesy** [comment]
Firefox is supported now.
