### ISSUE TITLE
support for Allegro.pl

### ISSUE THREAD

**Issue by Gucek** [extesy/hoverzoom#815]
..please?
e.g. on thumbnails here: https://allegro.pl/oferta/sena-r1-smart-kask-rowerowy-z-interkomem-r-59-63cm-10971350808

**Comment by GrosPoulet** [comment]
@Gucek : new plug-in for Allegro missed latest release by a few minutes, so you'll have to wait for the next one or ask @extesy very kindly for a new release...at your own risks (just kidding :stuck_out_tongue_winking_eye:)

**Comment by GrosPoulet** [comment]
@Gucek Plug-in for Allegro.pl added by #816
