### ISSUE TITLE
update for new Pixiv design

### ISSUE THREAD

**Issue by molecast** [extesy/hoverzoom#820]
## Description of the problem
After update Pixiv design, for some images it zooming the thumbnails, instead image itself.
https://i.pximg.net/imgaz/upload/20211008/776687181.png

Zooming normally: https://i.imgur.com/uPr3PiR.jpeg
Zooming thumbnail instead image: https://i.imgur.com/jEAh1sg.png

## Url of the page where the problem occurs (not the image url)
1. https://www.pixiv.net/en/
2. https://www.pixiv.net/bookmark_new_illust.php

## Steps to reproduce the problem (include image url here)
1. Go to Pixiv.
2. Hover over an image.
3. Try another image if the problem is not appear.

## OS version, extension version
Windows 10, 1.0.183

**Comment by GrosPoulet** [comment]
Hello @molecast 
I updated Pixiv plug-in to match new design & improved it a little (zoom user profiles, ...)
Enjoy!

**Comment by GrosPoulet** [comment]
Fixed in [v1.0.185](https://github.com/extesy/hoverzoom/releases/tag/1.0.185)
