### ISSUE TITLE
support loading plugins  dynamically

### ISSUE THREAD

**Issue by haolian9** [extesy/hoverzoom#823]
first, thanks for making this awesome project!

**Is your feature request related to a problem? Please describe.**

the website i want to apply to this extension is not available, then now i have to:
* whether fork this repo
* if i did not fork, then i must send a pr to this repo, wait it be reviewed/merged/released, it may take days!
    * sometimes i do not want to expose this plugin
* then i have to choose forking which means i should maintain a huge code base rather than some scripts
* and if i have multiple computers (laptop, desktop ...), multiple browsers (chromium, vivaldi)

**Describe the solution you'd like**

if hoverzoom implemented loading/importing plugins dynamically, i think there will be some benefits:
* hoverzoom can move all or partial plugins into a standalone repo
* users can have their private plugins without maintaining another hoverzoom

**Comment by extesy** [comment]
Mozilla doesn't allow extensions which execute any remote code (plugins from a remote repo). Google is doing the same thing with Manifest V3. I appreciate the suggestion but what you are asking for is against the security policies of corresponding web stores.

**Comment by haolian9** [comment]
oh, i didnt kown that, thanks for clarifying.
