### ISSUE TITLE
google issues

### ISSUE THREAD

**Issue by andythebeagle** [extesy/hoverzoom#83]
When using google, hover zoom is practically useless.  The zoomed image is somewhere out of the page, usually low and not visible, or doesn't work.  Non functional 90% of the time.  Similar extension for Firefox works flawlessly.   Win10x64

**Comment by extesy** [comment]
@andythebeagle please provide the full url of the page where hoverzoom doesn't work. So far google images work fine for me.

**Comment by andythebeagle** [comment]
Virtually any image on Twitter, any news site, any thing that isn't
google.  It will only show the image on about 30% of the sites I visit and
most of the time when an image does show it is some where off the page/tab
below with only a very small part showing.

**Comment by extesy** [comment]
@andythebeagle Do you have any other similar extension installed, like old "hoverzoom" version 5.17?

**Comment by andythebeagle** [comment]
No.  And another Hover Zoom I have on Firefox works perfectly.  Did you do
it?
