### ISSUE TITLE
Add support for : Tenor

### ISSUE THREAD

**Issue by aelinlovelace** [extesy/hoverzoom#831]
**What is the URL of the website**
https://www.tenor.com/

**Why we should add support for the website?**

I would like to be able to zoom in on the images to read the text on animated gifs, which is nearly impossible from the selection menus on from the web versions of Discord and Google Chat. Giphy and Gyfcat are supported, can you please also support Tenor? Thanks!

**Comment by extesy** [comment]
Implemented by https://github.com/extesy/hoverzoom/commit/c9aedc7b8699b0b3ee5d94aa0cc52e8010ebc6d0
