### ISSUE TITLE
Playback control bar covering the top of videos

### ISSUE THREAD

**Issue by guitarzilla** [extesy/hoverzoom#839]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem

When browsing Reddit using the old layout (not the new redesign) and hovering over a video, the video appears and the top is covered with a playback bar for a few seconds that fades away (pause button, volume etc.) This obscures the top part of the video. Also the bar doesn't seem to have any function since I can't move my mouse to it without the video disappearing. This happens on videos uploaded directly to Reddit showing their origin as v.reddit.com. This just started happening in the past couple of days on all of my computers.

## Url of the page where the problem occurs (not the image url)

old.reddit.com

## Steps to reproduce the problem (include image url here)
1. Open the site old.reddit.com
2. Hover over any video uploaded to v.reddit.com
3. Alternatively, as an example, go to https://old.reddit.com/r/oddlysatisfying/comments/rhx5jc/the_way_these_boots_are_tied/ and hover over the title (I realize this is redundant, but it demonstrates the issue)

## OS version, extension version

Windows 10 Pro version 20H2, OS build 19042.1348

![hoverzoom](https://user-images.githubusercontent.com/96271092/146470348-7507448b-2c8e-4529-a93a-cec8d816cc80.png)

**Comment by GrosPoulet** [comment]
Hi @guitarzilla 
In order to interact with video & audio controls, you must first **lock the viewer** on screen (Action Key=L by default).
Controls are not useful for very short videos, but it's nice to have them for longer ones  (e.g. Twitch) so you can jump to the last seconds/minutes.
Anyway, i agree with your remark: there's no need to display these controls when viewer is not locked, i'll fix it this weekend hopefully.

**Comment by guitarzilla** [comment]
Thanks!! Thats good info too, I didn't know I could lock the viewer. I appreciate you looking into this. It has obscured parts of the video that I wanted to see in the first few seconds, so if you're able to fix it, that's great.
