### ISSUE TITLE
Imgur link directs to http:// regardless of whether original site was https:// or http://

### ISSUE THREAD

**Issue by jonluca** [extesy/hoverzoom#84]
`Mixed Content: The page at 'https://www.reddit.com/ was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/yWm7e28.jpg'. This content should also be served over HTTPS.`

Not a huge problem, more of a warning from the console. I might try to implement a fix for this later.

**Comment by extesy** [comment]
I've seen this before. It's very tricky to fix because not image sites support https. Imagine you are trying to load an image from streamable.com (just for example) and it doesn't support https. Now your image can't load at all. It's impossible to fix this problem in a generic way.

**Comment by jonluca** [comment]
Yeah, it's going to have to be fixed plugin by plugin. I'm doing some research on the plugin-supported sites. There's no way to do anything in the main hoverzoom js file, but we should be able to get the current url in each individual plugin. I'm just going to try and update imgur and youtube for now, and then slowly ramp up updating all the smaller sites. Thanks for the prompt reply!

**Comment by jritz611** [comment]
possible to fix this for streamable?

**Comment by extesy** [comment]
Possible, but I prefer to not create one-off hacks and instead come up with a more generic and scalable solution.

**Comment by jritz611** [comment]
thanks, whats the reason it was working up until a few days ago?

**Comment by extesy** [comment]
It shouldn't have. I suspect that someone was posting `https://` links to streamable and those should have worked. Now you see `http://` links and those don't work.

**Comment by jritz611** [comment]
looks like streamable changed the way they make links recently
