### ISSUE TITLE
Danbooru.donmai.us does not work anymore

### ISSUE THREAD

**Issue by anpuhach** [extesy/hoverzoom#841]
**Describe the bug**
A zoom feature does not work anymore at Danbooru. I remember it was working about a month ago.

**To Reproduce**
1. Go to https://danbooru.donmai.us/posts
2. Hover an image.

**Expected behavior**
An image should zoom.

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.93

**Additional context**
A [similar](https://safebooru.org/index.php?page=post&s=list&tags=all) type of site still works though.

**Comment by anpuhach** [comment]
Hi.
I've checked today's update, but it still does not work at https://danbooru.donmai.us/posts

**Comment by extesy** [comment]
It works for me on that page. Make sure you are using 1.0.186 version.

**Comment by anpuhach** [comment]
Oh, I'm sorry. Everything works fine. It doesn't update automatically for some reason.
