### ISSUE TITLE
Мигает текст страниц

### ISSUE THREAD

**Issue by Benia** [extesy/hoverzoom#847]
Мигает красным текст страниц на d3.ru и грузит процессор на 25%. На других сайтах проблема не проявляется.
Win 7, Chrome 96.0.4664.110 (Официальная сборка), (64 бит), HZ+ 1.0.186
https://cloud.mail.ru/public/27tt/KUbKpvfKK

upd: Откатился на предыдущую версию https://github.com/extesy/hoverzoom/releases/tag/1.0.185, всё заработало нормально.

**Comment by foxm666** [comment]
Я несколько раз выключил и включил расширение и мигание исчезло.

**Comment by GrosPoulet** [comment]
in english please

**Comment by GrosPoulet** [comment]
@extesy On this site (d3.ru), there's an issue with the text blinker i addd in lastest release.
Maybe because there's already some text blinking going on on d3.ru.
If i comment out line 312 in hoverzoom.js: no more issue.

**Comment by extesy** [comment]
@GrosPoulet I wasn't able to reproduce it myself (I don't see any blinking) so thank you for finding a root cause. Do we even need this `.blink` style at all? Seems to be redundant with `.videoErrorMsgCss` in my opinion.

**Comment by StazMD** [comment]
Same for me. d3.ru is blinking with red.

**Comment by Benia** [comment]
> 
Откат решает: https://github.com/extesy/hoverzoom/releases/tag/1.0.185
