### ISSUE TITLE
Loading icons do not go away.

### ISSUE THREAD

**Issue by atticusgrey** [extesy/hoverzoom#85]
On what seems like every page, the loading icon wil lnot go away. [Screenshot here](http://imgur.com/jDfGNMy).

**Comment by extesy** [comment]
@atticusgrey I haven't seen this before. What browser and what version are you using?

**Comment by atticusgrey** [comment]
Chrome 49.0.2623.112 m (64-bit)

**Comment by jonluca** [comment]
Please update to Chrome Version 50.0.2661.102 (64-bit) and attempt to reproduce.

Could you also post your settings?
