### ISSUE TITLE
Reddit - click page then hover again

### ISSUE THREAD

**Issue by zwilldiy** [extesy/hoverzoom#857]
Starting about a week or 2 ago I have been getting large text when hovering over a video or gif on the old version of reddit.com that says "click page then hover again". I am assuming this was a change in a recent update of the extension? Why did you make this change? It was working fine before, did Reddit change something?

**Comment by GrosPoulet** [comment]
Hi @zwilldiy 
On Chrome you have to interact first with the page before a video can be played. 
That's why this warning message was added, it is not specific to Reddit.
I did not test other browsers, which one are you using ?

**Comment by zwilldiy** [comment]
I see. You just need to click anywhere on the page, not actually visit the post. Thanks for clarifying.

**Comment by GrosPoulet** [comment]
@extesy : maybe warning message should be reworded: "click **background page** then hover again" or "click **anywhere on page** then hover again" ?
