### ISSUE TITLE
Action keys not working in firefox latest

### ISSUE THREAD

**Issue by 8OIO8** [extesy/hoverzoom#862]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by extesy** [comment]
@8OIO8 Which action keys? On what website? What version of browser and extension? I can't read your mind. The bug template exists for a reason.

**Comment by 8OIO8** [comment]
latest versions /any website/shortcut to download an image/the same working in edge browser not in firefox

**Comment by frasty** [comment]
I can confirm. HoverZoom doesn't work for any website on Firefox 96/Fedora 35

**Comment by extesy** [comment]
Fixed by b34adbebb035219ed8a7ba7fe93873db4b18f1e6
