### ISSUE TITLE
Scrolling album not work on Instagram

### ISSUE THREAD

**Issue by SpettroFotonico** [extesy/hoverzoom#865]
**Describe the bug**
Scrolling feature doesn't work with any key configuration (mouse wheel or keyboard buttons)

**To Reproduce**
1. Go to 'Instagram (in example)'
2. Click on 'An any album'
3. Scroll down to 'Try to scroll the photos'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [Chrome]
 - Version [e.g. 97.0.4692.99]

**Additional context**

**Comment by edsimpsons83** [comment]
I am able to duplicate this as well. Maybe something changed on Instagram's end.

**Comment by GrosPoulet** [comment]
Hi @SpettroFotonico & @edsimpsons83 
HZ+ zooms IG images & videos since latest release (1.0.202), you can scroll through albums with keys or wheel.

**Comment by extesy** [comment]
Closing as fixed in `1.0.202`.
