### ISSUE TITLE
Hover Zoom+ does not work on instagram.com

### ISSUE THREAD

**Issue by SpettroFotonico** [extesy/hoverzoom#866]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Steps to reproduce the problem (include image url here)
1.
2.
3.

**Comment by GrosPoulet** [comment]
Hi @SpettroFotonico 
HZ+ zooms IG images & videos since release 1.0.202.

**Comment by extesy** [comment]
Closing as fixed in `1.0.202`.
