### ISSUE TITLE
Mouse wheel do not work on imgur album

### ISSUE THREAD

**Issue by Panchito0049** [extesy/hoverzoom#872]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
On imgur the wheel works erratic on album, changes very fast from one picture to other and stops any time

## Url of the page where the problem occurs (not the image url)
https://imgur.com/

## Steps to reproduce the problem (include image url here)
1.select an album
2.move the wheel
3.https://imgur.com/gallery/aYDRpZ4

**Comment by extesy** [comment]
Just checked on Chrome and album scrolling works fine
