### ISSUE TITLE
Add support for preview. redd.it

### ISSUE THREAD

**Issue by 420greg** [extesy/hoverzoom#874]
This plugin works great on most of the reddit image links (i.reddit imgur, etc) but mousing over a link to preview.redd.it just brings up a rotating icon, like it wants to load, but can't.

**Comment by extesy** [comment]
@420greg There is insufficient information to identify and fix the issue. Please open a bug request using a pre-defined template and fill out the details:
![image](https://user-images.githubusercontent.com/65872/154323873-1e715b04-747c-4a18-a6c8-87f8e4f09cb3.png)
