### ISSUE TITLE
Add support for : preview.redd.it

### ISSUE THREAD

**Issue by 420greg** [extesy/hoverzoom#876]
**What is the URL of the website**
https://preview.redd.it/

**Why we should add support for the website?**
most of the other image links on reddit work with Hover Zoom + except this one. 

![reddit_preview_link](https://user-images.githubusercontent.com/11463089/154528862-a80f00d2-8a32-44f8-9db6-95df9d79cc46.png)

**Comment by extesy** [comment]
@420greg Which subreddit has these links?

**Comment by 420greg** [comment]
All of them. They are part of every single post that links to an
image/video.

**Comment by extesy** [comment]
> All of them. They are part of every single post that links to an
@420greg All of them? Couldn't find a single one on https://www.reddit.com/r/politics/. Please provide clear repro steps and please don't generalize. Your "all subreddits" are different from my "all subreddits".

**Comment by 420greg** [comment]
https://www.reddit.com/r/all/

Most of these article titles are followed by a blue link to the image URL.
Hoving over the i,imgur.com and i.reddit.it links shows the linked image in
the pop-up.
If the image link is preview.redd.it, hover just produces a spinning
loading icon.

[image: Screen Shot 2022-02-17 at 3.33.56 PM.png]

**Comment by extesy** [comment]
I was unable to reproduce but please try version `1.0.188` and let me if that fixes your issue.

**Comment by TS6ix2GaH3q679h5** [comment]
Seems like this issue has been fixed. I'm using Version 1.0.189 and all links using this structure are popping-up zoomed for me:
https://www.reddit.com/domain/preview.redd.it/

**Comment by extesy** [comment]
Thank you for confirming, @TS6ix2GaH3q679h5!
