### ISSUE TITLE
Add to browser history not working on old.reddit.com

### ISSUE THREAD

**Issue by mobad** [extesy/hoverzoom#881]
**Describe the bug**
Links aren't turning purple on https://old.reddit.com/r/all/ when hovered over.

**To Reproduce**
1. Enable add to browser history.
2. Browse to https://old.reddit.com/r/all/
3. Hover over various links and see that they aren't turning purple (added to history)

**Expected behavior**
The links should turn purple when hovered over.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 98.0.4758.102

**Additional context**
This only started happening after the update to 1.0.188, most likely due to https://github.com/extesy/hoverzoom/commit/5ff674b1c5e707c721b10375bb91fa3b75c8f574 
I suspect because the image url is actually different from the link URL.
I think most likely you'd need to add both to history?

**Comment by extesy** [comment]
@GrosPoulet Can you take a look? I did mention that the removed lines were originally added to fix reddit.

**Comment by JunoArc** [comment]
Getting same issue 

OS: Win10
Browser Chrome
Version 98.0.4758.102 (Official Build)

**Comment by extesy** [comment]
@mobad @JunoArc Should be fixed in `1.0.189`. Can you please confirm if the feature works properly now?

**Comment by mobad** [comment]
@extesy Works for me now! Thanks @GrosPoulet !
