### ISSUE TITLE
"Add viewed pictures to the browser's history" not working on reddit

### ISSUE THREAD

**Issue by RumplesWrinkles** [extesy/hoverzoom#884]
Hoverzoom is not marking URLs as read when viewed. See attached video example.

https://i.imgur.com/CmqkToQ.mp4

I've quit and reopened Chrome, but the issue persists. I've also unchecked the setting, saved, refreshed, and re-checked and saved the setting.

MacOS Monterey 12.0.1
Chrome Version 98.0.4758.102 (Official Build) (arm64)

**Comment by mobad** [comment]
@RumplesWrinkles This was fixed https://github.com/extesy/hoverzoom/issues/881
Hopefully will be on Chrome store soon.
