### ISSUE TITLE
HoverZoom slows down EmberJS DOM node insertion

### ISSUE THREAD

**Issue by flwyd** [extesy/hoverzoom#890]
**Describe the bug**

**To Reproduce**
Unfortunately, the site where I observed this behavior is not public, but it doesn't look to be doing anything particularly complex.
1. Using the [Ember](https://emberjs.com) framework
2. Have a route which loads ~5,000 records
3. Display it with a template that looks something like
```hbs
{{#each report.people key="id" as |person|}}
  <div>
    <LinkTo @route="person" @model={{person.id}}>{{person.name}}</LinkTo>
  </div>
{{/each}}
```
4. Wait for a _long_ time for anything to show up on the screen.

**Expected behavior**
The data loads in about two seconds if Hover Zoom is disabled, but it takes around one minute to load exactly the same 5,000 divs and links if the extension is enabled.  The divs do not contain any images, the `<a>` tags link to regular pages (not images), and there are no images on the page, though there are other pages on the site where HoverZoom can activate when a person's photo is shown.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS, ChromeOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 99, 99

**Additional context**
I can provide Chrome profiler data if it would be helpful.  The "Bottom up" hot spots are `windowOnDOMNodeInserted` as well as `querySelectorAll` from jQuery's Sizzle via jQuery find, triggered by `DOMNodeInserted events`.  It looks like [DOMNodeInserted is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent) in favor of [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).  Additionally, perhaps 5-10% of the time is spent [https://github.com/extesy/hoverzoom/blob/caa1525e748e23a6a91d43b96fb7141690473c0b/js/hoverzoom.js#L1792](clearing and then setting a timeout) for each inserted link.

**Comment by extesy** [comment]
@flwyd I've replaced the deprecated observer with a new one in [030b2cc](https://github.com/extesy/hoverzoom/commit/030b2ccc9d724d02c8602f871b355de54130618e). If you don't mind, can you please test the new version?

**Comment by extesy** [comment]
I assume it's fixed now. Please reopen if the issue persists.
