### ISSUE TITLE
Add support for : Viewbug.com

### ISSUE THREAD

**Issue by pwmcmaho** [extesy/hoverzoom#896]
**What is the URL of the website**
https://www.viewbug.com/

**Why we should add support for the website?**
A great image site would be nice to be able to see the full-size images without multiple clicks into the site. Thanks!

**Comment by GrosPoulet** [comment]
Thank you for sharing this awesome photos website with us @pwmcmaho :heart_eyes:
I wrote a plug-in for viewbug.com, it'll be available in next release of HZ+ (1.0.190).

**Comment by pwmcmaho** [comment]
Thanks!!! @GrosPoulet

**Comment by extesy** [comment]
Closed by #900.
