### ISSUE TITLE
Please add the option to mute Twitch streams preview

### ISSUE THREAD

**Issue by BeardJesus** [extesy/hoverzoom#898]
**Is your feature request related to a problem? Please describe.**
When hovering a twitch channel on the left pannel, the preview is always at max volume, blasting my poor ears. That happens even though I ticket to mute all videos (and set the volume for videos to 0% just in case)

**Describe the solution you'd like**
I would like a tickbox to mute all live streams preview (or a slider to set the volume in %)

**Describe alternatives you've considered**
Well... I don't know, what I did for now is disabling the preview for twitch

Thank you in advance for your attention !

**Comment by GrosPoulet** [comment]
Sorry for your ears, @BeardJesus 
A fix will be available in next release of HZ+ (1.0.190).

**Comment by extesy** [comment]
Closed by #901.
