### ISSUE TITLE
mac trackpad scroll is too fast for gallery view

### ISSUE THREAD

**Issue by spaham** [extesy/hoverzoom#90]
Hi !

I really enjoy hoverzoom, but there is a problem with how the mac trackpad is handled
when scrolling through a gallery.
A millimeter scrolls many times around a whole gallery. Which makes it impossible
to really browse through.
Maybe a variable multiplier (divisor) in the preferences would help us set it up as we please ?

thanks !

**Comment by extesy** [comment]
Duplicate of #76.
