### ISSUE TITLE
Package is invalid

### ISSUE THREAD

**Issue by Queuecumber** [extesy/hoverzoom#91]
I get this error when installing from the chrome web store

```
Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.
```

Chrome 50.0.2661.102 (64-bit) Ubuntu 16.04

**Comment by extesy** [comment]
I've just tried installing it myself and there were no errors. Try it from another machine or clear your browser cache and cookies. Looks like the error is between your browser and a web store.

**Comment by Queuecumber** [comment]
You're on Chrome  50.0.2661.102 Linux as well? It could be an issue with the platform. Anyway I'll see if I can debug the install process and I'll let you know if that seems to be the case.

**Comment by extesy** [comment]
I'm on a same version of Chrome, but I used Windows and Mac for testing.
