### ISSUE TITLE
redgifs.com links on reddit no longer working

### ISSUE THREAD

**Issue by moocow2024** [extesy/hoverzoom#910]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Hover Zoom + is not currently able to work on redgifs.com links found on reddit in either Chrome or Brave, but works fine on Firefox. However, upon going directly to redgifs.com to view the gif/video, hover zoom + is capable of working properly there. The following examples are definitely NSFW, since redgifs is pretty exclusively NSFW. I tried to find something.... semi-tame. I have reproduced the problem in a private window tab in both Brave and Chrome, where Hover Zoom + was the only extension active. 

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/r/softcorenights/comments/tplp48/softcore_cowgirl_compilation_3/

## Steps to reproduce the problem (include image url here)
1. Visit any reddit.com subreddit with redgifs.com links on a chrome based web browser. 
2. Hover zoom + will not load the video/gif. 

image url:
https://www.redgifs.com/watch/impossibleivoryladybug

## OS version, extension version
Windows 10 Pro version 21H2
Extension: Version 1.0.190 (last update: Fri, Apr 22, 2022)

**Comment by wmertens** [comment]
Seems to be due to CORS:

```
Access to XMLHttpRequest at 'https://api.redgifs.com/v1/gfycats/impossibleivoryladybug' from origin 'https://www.reddit.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.redgifs.com' that is not equal to the supplied origin.
```
