### ISSUE TITLE
The Extension is not working on Slickdeals

### ISSUE THREAD

**Issue by MZAN68** [extesy/hoverzoom#911]
Hi, thank you for this great extension.   I love it.

Can you please look to see why it has stopped working for Slickdeals.net website?  It used to work.

**Comment by extesy** [comment]
@MZAN68 Please use the template (auto-populated when you create the issue) to provide more details. At the time of writing this comment, slickdeals works for me. I need more details (like in the issue template) to be able to diagnose the problem.

**Comment by MZAN68** [comment]
I used the template to create a new issue; closing this one.
