### ISSUE TITLE
Issue with Wallhaven.cc

### ISSUE THREAD

**Issue by GreyErick** [extesy/hoverzoom#918]
**Describe the bug**
Hoverzoom works fine on the main page, The other pages, not at all.

**To Reproduce**
1. Go to wallhaven random
2. hover over picture
3. Picture doesn't expand

**Expected behavior**
I expect the pictures on the other pages of the site to zoom as well.

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1 
 
**Additional context**

**Comment by extesy** [comment]
Seems to work fine for me, just checked both Chrome and Firefox.
