### ISSUE TITLE
Mouse wheel zooming on locked "v.redd.it" video

### ISSUE THREAD

**Issue by Wassss** [extesy/hoverzoom#923]
## Description of the problem
When "v.redd.it" video are locked on screen and mouse wheel is used to zoom the video the entire page is scrolled up or down.

## Url of the page where the problem occurs (not the image url)
https://old.reddit.com/domain/v.redd.it/

## Steps to reproduce the problem (include image url here)

https://imgur.com/a/h0T4hrm

1.Hover over a "v.redd.it" link.
2.Lock video on screen. (I set "Right Click" as an Action key).
3.Action mouse wheel to zoom video.
4.The entire page scrolling is somehow triggered.

## OS version, extension version
windows 10
Firefox 100
Hover Zomm+ 1.0.190

**Comment by Wassss** [comment]
@extesy any thought about this ?

**Comment by extesy** [comment]
Can't reproduce on Chrome, so perhaps this is a Firefox-only issue. Will need to investigate more.
