### ISSUE TITLE
Can't load images from preview.redd.it

### ISSUE THREAD

**Issue by kbuffington** [extesy/hoverzoom#924]
## Description of the problem

HoverZoom seems to work on every image source on Reddit, except for `preview.redd.it`.

## Url of the page where the problem occurs (not the image url)

https://www.reddit.com/r/gaming/comments/unj1se/it_hurts/

## Steps to reproduce the problem (include image url here)
1. Open Reddit
2. Hover zoom over a link preview.redd.it link (i.e. https://preview.redd.it/qyra0saiowy81.gif?width=750&format=mp4&s=592dfb87dcff3da19ae9223f12576a899594cc4f)
3. Error is thrown in console saying link could not be loaded

## OS version, extension version

OSX, extension version 1.0.190

**Comment by kbuffington** [comment]
This is broken again:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2282004/174723973-3d3518e0-e939-4cc3-9a16-3f01e2e111de.png">

**Comment by kbuffington** [comment]
It doesn't even work for me on this github page.
 
Also, I think that post you linked was removed because I can't see anything :)

**Comment by extesy** [comment]
I linked the same post you linked in your bug description. It opens correctly for me in the browser. The main priority is to make sure reddit preview links work on reddit, not on github.

**Comment by kbuffington** [comment]
Weird. That reddit link doesn't work for me at all. Hovering over any preview.redd.it link doesn't work for me, regardless of page. Here's another reddit page, and they all give the same "failed to load image" error: https://www.reddit.com/r/gaming/comments/vh4sq9/the_sassiest_assassin_arno_dorian_assassins_creed/
