### ISSUE TITLE
Hoverzoom not working on Reddit when users upload using Redgifs website.

### ISSUE THREAD

**Issue by ewok200909** [extesy/hoverzoom#927]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## 

Website Reddit users upload with.

https://www.redgifs.com/

## Steps to reproduce the problem (include image url here)

1. Hovering on any thumbnail on Reddit just shows a small picture, no enlargement.
2.
3.

## OS version, extension version

Windows 10, Microsoft Edge, have also tried on Google Chrome, same problem

Extension version: Version 1.0.190

**Comment by GrosPoulet** [comment]
Hi @ewok200909 
This issue is fixed by #912, but not released yet.
@extesy do you know when 1.0.191 will hit Chrome Web Store ?

**Comment by ewok200909** [comment]
@extesy 

Hi, 

Its updated for Chrome browser but not Edge which is what I use.

Any update on when the 1.0.191 update is coming to edge?

Thanks,

**Comment by extesy** [comment]
@ewok200909 I've uploaded the updates at the same time. Edge is usually much slower to publish the updates. Should become available in a few days.
