### ISSUE TITLE
Save Image hotkey is not working on firefox

### ISSUE THREAD

**Issue by ABCHON** [extesy/hoverzoom#939]
it's only the Save Image hotkey notwork,the other hotkey is working
no problem on EDGE

OS: Firefox 100.0.2（64 bit）

**Comment by extesy** [comment]
@ABCHON Have you tried remapping it to a different key in extension options? Is it just a default key that doesn't work or the save action itself?

**Comment by ABCHON** [comment]
> @ABCHON Have you tried remapping it to a different key in extension options? Is it just a default key that doesn't work or the save action itself?

Yes, i try to remapping different key , it's still not work
no any responding

**Comment by Hachiman65** [comment]
Yup, I'm having the same problem. Please fix it soon.

**Comment by extesy** [comment]
This problem is caused by a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1392624. This bug makes it impossible for an extension to ask for optional permissions, such as the "download" permission required for save image action. This bug is 5-years old so it looks like Mozilla doesn't care about this use case.

**Comment by extesy** [comment]
Can someone please try installing the latest version locally ([instructions](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)) and confirm if the fix works? There is a new option now at the top of the Advanced tab that you need to turn on.

**Comment by extesy** [comment]
Related issue: #732 732

**Comment by Hachiman65** [comment]
Sorry, I know nothing about this programmer stuff. Where do I get that .json file?
I only created this account to comment on the problem.

**Comment by extesy** [comment]
@Hachiman65 Please wait until the official release. Hopefully someone else can confirm in the meantime.

**Comment by Hachiman65** [comment]
Alright

**Comment by ABCHON** [comment]
the new version still not work

**Comment by extesy** [comment]
@ABCHON Please enable download permission in the advanced settings, don't forget to save the permission afterwards.
