### ISSUE TITLE
Reddit posts show a picture of the reddit alien, even if it is a self post (AKA no image in the post)

### ISSUE THREAD

**Issue by alathil22** [extesy/hoverzoom#94]
Whenever I mouse over a self post it loads an image of the reddit alien, even though no image was linked at all. Not a huge issue, but a little annoying to have it pop up every time I try and click on a link.

Edit: So now I realize this may be intentional, as all links to reddit show some image such as a BestOf link showing the picture in the original thread. If this is intentional, I would love an option to disable it for links to reddit. It just gets pretty cluttered when every single link loads an image, especially when that image is a pointless reddit alien.

Edit 2: I found the option to disable it, I'm silly. Sorry, closed the issue.

Here's an example:
![xvadl1n](https://cloud.githubusercontent.com/assets/828755/15708551/15e7a97c-27cd-11e6-86b8-8136313cdee1.jpg)

**Comment by extesy** [comment]
@alathil22 what option have you used to disable this?

**Comment by alathil22** [comment]
@extesy In the plugins section of the options I just unchecked reddit. I don't know if that's going to cause other issues, but I haven't noticed anything wrong yet.

**Comment by extesy** [comment]
Ok, I'll fix it later today.
