### ISSUE TITLE
Viewing Images stored in Google Drive doesn't work

### ISSUE THREAD

**Issue by bnjmn** [extesy/hoverzoom#948]
## Description of the problem

I am unable to get hover zoom to work with files that I have uploaded to my G-drive. I tested this within a Google Sheet I created because my goal is to use Hover Zoom to preview images/pdfs that are linked within a spreadsheet. 

Following a guide online, I used a publicly available image successfully in the spreadsheet and can preview it fully (quite nicely, thank you!) with Hover Zoom.

However, when I tried downloading that same file, uploading it to a folder on my G-drive, and using a link with sharing set to "Anyone with the link".

## Url of the page where the problem occurs (not the image url)

Here is a Google Sheet I created and made accessible to anyone with the link. I will take it down once this issue has been investigated.

https://docs.google.com/spreadsheets/d/1VUSHJZjyr3jNFxRVjtWtaSRqQ1fPMk7pt4FQTQoRg2M/edit?usp=sharing

## Steps to reproduce the problem (include image url here)
1. Upload a file to G-Drive (png, jpg, pdf - tested with both png and pdf without success)
2. Copy the link for the file and set access to "Anyone with the link"
3. Paste the link into a cell in a Google Sheet
4. When hovering over the link, a google link edit box pops up with the link text in blue
5. Hovering over that blue link text should show the Hover Zoom full image (as it does with example image hosted on AWS)
6. Try to use Hover Zoom to preview the file from within the Google Sheet

Expected:

It should show the image full size

Actual:

The image is never shown in full size; there is just a small greenish box with a spinner that is shown.

## OS version, extension version

MacOS Montery Version 12.4
Chrome Version 102.0.5005.115 (Official Build) (arm64)
Hover Zoom Version 1.0.193

Thank you! Seems like a great extension. Would love to get it working for this use-case.

**Comment by bnjmn** [comment]
I also just wanted to add the following:
- [Here is the article](https://sheetaki.com/view-full-images-hover-google-sheets/) that gave me the idea to use Hover Zoom in a google sheet
- I also installed Version 1.0.192 on Firefox 101.0.1 (64-bit) and seemed to have the exact same results as with my tests in Chrome.
Thanks again!

**Comment by extesy** [comment]
Thank you for the excellent description and very helpful repro steps, @bnjmn! This is now fixed and will be available in the next release.
