### ISSUE TITLE
Cannot change anything in the options page..(Solved after Google Chrome Update)

### ISSUE THREAD

**Issue by chella1cm** [extesy/hoverzoom#95]
Started using Hoverzoom+, so far loving it. But i tried to change some option in options page but i cannot change anything. So far i can change the values in the text field, but i cannot affect any check boxes. Please look into it, or am i doing something wrong?..

Also watching youtube just by hovering is cool, but it'll be so much better if there was an option to choose video resolution for Youtube video playback.

**Comment by extesy** [comment]
@chella1cm Could you please open the console (menu -> tools -> developer tools, switch to "console" tab) while you are in extension options window. Are there any errors logged? Also, what's your browser version?

**Comment by chella1cm** [comment]
I am using Chrome dev 52.0.2743.19 dev-m (64-bit). link to console log http://i.imgur.com/DxXbCb3.jpg.

**Comment by chella1cm** [comment]
I am using Chrome dev 52.0.2743.19 dev-m (64-bit). link to console log http://i.imgur.com/DxXbCb3.jpg.

**Comment by chella1cm** [comment]
Everything is working after updating Chrome to 53.0.2756.0 dev-m (64-bit). Thanks everything is fine now.

And in what resolution that the zoomed videos are playing is there anyway to control it?.

**Comment by extesy** [comment]
Videos are played in hd720 resolution if found, otherwise the lowest available.
