### ISSUE TITLE
Panning on locked image doesn't work

### ISSUE THREAD

**Issue by BubiBalboa** [extesy/hoverzoom#993]
**Describe the bug**
When you lock an image the settings say you can pan around. I can't seem to make this work. I tried just using the mouse cursor, holding left-click and the arrow keys to move the image around but it stays centered. I also tried turning off the "center image" setting but that didn't help either. Works fine on Vivaldi.   

**Desktop (please complete the following information):**
 - OS: Win11
 - Firefox 104.0b6

**Comment by LiliaDoe** [comment]
I tested this on the latest version of Firefox (131.0.3) and W10. It's working for me. It zoomed in and out with scroll wheel and panned around as expected.

**Comment by extesy** [comment]
Thank you for confirming, @LiliaDoe! I'll close the issue then.
