### ISSUE TITLE
Add support for : Etejo.com

### ISSUE THREAD

**Issue by pwmcmaho** [extesy/hoverzoom#997]
**What is the URL of the website**
https://etejo.com

**Why we should add support for the website?**
Great image site that I would love to be able to zoom and share images from.

Thanks!

**Comment by LiliaDoe** [comment]
I'm not sure this site allows for zooming of image. I made a plugin which gets the image link and everything, but it shows nothing on mouseover.

**Comment by extesy** [comment]
Implemented by https://github.com/extesy/hoverzoom/commit/c42dd95e3fbd1fd1c13424809b6157dd9f208abc
